### ISSUE TITLE
Remove Google Plus icon in header & footer?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#106]
Related to the Terms of Service (TOS) email chain last week -- we no longer have a gov't TOS for Google Plus. 

Our old posts and comments still exist https://plus.google.com/109077476228639396954 and are still viewable to anyone **_not_** logged in via a GSA account -- however, I get this page (attached photo) when I try to view comments when logged in with my GSA account.

Should we just remove social icons in header & footer?

<img width="1280" alt="screen shot 2017-10-20 at 2 36 41 pm" src="https://user-images.githubusercontent.com/19961574/31961688-7bb70322-b8c9-11e7-96c8-87c9cb48ab1e.png">

- - -

### todo
- [x] Remove google plus link/icon from header
- [x] Remove google plus link/icon from footer

**Comment by jeremyzilar** [comment]
Yes 👍 
We can and should just remove those from the site.

**Comment by thisisdano** [comment]
Up next on my todo list!
