### ISSUE TITLE
Demo: list items with icon need wrap/margin fix

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1062]
Examples:
https://demo.digital.gov/ 
https://demo.digital.gov/resources/ 
https://demo.digital.gov/topics/accessibility/ 

- [x] long lines of text wrap on these list items, but aren't indented past the first line

## it's done when …
- [x] text that wraps is also indented

**Comment by jeremyzilar** [comment]
This should be fixed @ToniBonittoGSA — want to take a look?

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
