### ISSUE TITLE
Add Required links to Anchor + Footer

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1063]
## it should include items from: https://docs.google.com/document/d/1o_rHlQX0y-GmgfGQMaBleMfor2bkobxY-pygJgQlPjk/edit 

- [ ] [About](https://digital.gov/about/) (DG)
- [ ] [Accessibility](https://www.gsa.gov/website-information/accessibility-aids) (GSA)
- [ ] Privacy Policy (DG [Policies](https://digital.gov/policies/)) -- Perhaps use individual anchor links for clarity; Privacy Policy, Linking Policy, Reuse and Copyright, and Comment Policy (when comments are enabled again?)
- [ ] [Freedom of Information Act](https://www.gsa.gov/reference/freedom-of-information-act-foia) (GSA)
- [ ] [No FEAR Act](https://www.gsa.gov/about-us/organization/office-of-civil-rights/notification-and-federal-employee-antidiscrimination-and-retaliation-act-of-2002) (GSA)
- [ ] [USA.gov](https://www.usa.gov/) (text)
- [ ] Cross-agency portals (individual requirements set by agency) -- [18F](https://www.18f.gov), [PIF](https://www.presidentialinnovationfellows.gov/), [CoE](https://coe.gsa.gov/) ?
- [ ]  larger white GSA logo (placement similar to OMB and DG logo on [PRA demo footer](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov-pra/bh-digital-banner/))

## it's done when …
- [ ] above are added

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Is this consistent with the guidance that have on what is required in footers? And do you have a link to that page as well?

**Comment by ToniBonittoGSA** [comment]
Some footer examples: 

https://open.nasa.gov/blog/ 
https://www.hiv.gov/blog/ 
https://www.hhs.gov/blog/ 
https://blog.samhsa.gov/ 
https://www.cdc.gov/ 
https://www.dhs.gov/blog

**Comment by ToniBonittoGSA** [comment]
added NPS above

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
