### ISSUE TITLE
Demo: individual Service pages bug

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1064]
On 
https://demo.digital.gov/services/mobile-application-testing-program/ 
https://demo.digital.gov/services/u-s-digital-registry/ 
https://demo.digital.gov/services/challenge-gov/ 
https://demo.digital.gov/services/dap/ 

## Android
![61918459_10161774983090243_8739161787590508544_o](https://user-images.githubusercontent.com/19961574/58644918-4c836a00-82d0-11e9-9256-ef70591ebf8c.jpg)

## iOS
![61350062_2622012567827699_3682162745186189312_o](https://user-images.githubusercontent.com/19961574/58644940-573dff00-82d0-11e9-9eb0-347d366eb5f0.jpg)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
