### ISSUE TITLE
Demo: Authors and date line are below Feedback box

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1066]
On mobile, authors and date should fall between title/deck and copy

![61287710_10161775253250243_3489331207655653376_o](https://user-images.githubusercontent.com/19961574/58649377-f3b8cf00-82d9-11e9-9337-632814394e10.jpg)

**Comment by jeremyzilar** [comment]
Fix the date in cards on the homepage — they are showing up above the authors

**Comment by jeremyzilar** [comment]
This has been fixed.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
