### ISSUE TITLE
Demo: usa-banner loads open, All Topics page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1070]
On Android, it loads open, and stays open for maybe 5 seconds before it collapses 
https://demo.digital.gov/topics/ 

![Screenshot_20190530-165613_Chrome](https://user-images.githubusercontent.com/19961574/58670423-fe408c00-830c-11e9-8bfe-037b2b423048.jpg)

**Comment by jeremyzilar** [comment]
This can be fixed on our side, and we should update this fix in the USWDS core

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
