### ISSUE TITLE
Demo: In-page menu in wrong place (multiple Resource pgs)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1072]
## fix placement 

Incorrect: 
- https://demo.digital.gov/resources/checklist-of-requirements-for-federal-digital-services/ 
- https://demo.digital.gov/join/ 
- https://demo.digital.gov/resources/federal-social-media-accessibility-toolkit-hackpad/ 
- https://demo.digital.gov/resources/improving-the-accessibility-of-social-media-in-government/ 
- https://demo.digital.gov/resources/guidance-on-the-use-of-challenges-and-prizes-to-promote-open-government/ 
- https://demo.digital.gov/resources/customer-experience-toolkit/ 
- https://demo.digital.gov/resources/contact-center-guidelines/ 
- https://demo.digital.gov/resources/contact-center-guidelines/contact-center-operation-and-management/ 
- https://demo.digital.gov/resources/contact-center-guidelines/contact-center-technologies/ 
- https://demo.digital.gov/resources/style-guides-by-government-agencies/ 
- https://demo.digital.gov/resources/content-management-systems-used-by-government-agencies/ 
- https://demo.digital.gov/resources/crowdsourcing-toolkit-for-federal-agencies/ 
- https://demo.digital.gov/resources/how-to-get-your-open-data-on-data-gov/ 
- https://demo.digital.gov/resources/inventory-data-gov-guide/ 
- https://demo.digital.gov/resources/mobile-application-development-program/ 

There may be a lot more that can be found by searching code 

## it's done when they're in the right place; examples: 
- https://demo.digital.gov/resources/omb-memos-circulars-executive-orders-and-other-policies/ 
- https://demo.digital.gov/resources/guide-create-mobile-friendly-websites/

**Comment by jeremyzilar** [comment]
I will

- [ ] Create a TOC that sits at the top of the page for mobile views
- [ ] adjust breakpoints for column wrapping

**Comment by jeremyzilar** [comment]
This should be fixed now @ToniBonittoGSA
