### ISSUE TITLE
Demo: Mobile SOW pg in-page nav errors

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1073]
https://demo.digital.gov/resources/mobile-sow-and-developer-qualifications/ 
in wrong spot, links not set; may have header errors

![Screenshot_20190530-193748_Chrome](https://user-images.githubusercontent.com/19961574/58672107-6b572000-8313-11e9-973f-0604aa41baea.jpg)

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA before I can work on this post, can you help to change out the headings in this to markdown headings, and help them make sense?

The wording on each heading is strange and I am not sure what to do with it.

Also, we shouldn't have any jump links or `<a name="">` links in the headings. 
![image](https://user-images.githubusercontent.com/395641/70292992-d7787c00-17ad-11ea-88f4-72d843993166.png)
