### ISSUE TITLE
Demo: in-page nav empty, in wrong spot

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1074]
https://demo.digital.gov/resources/mobile-development-strategies/ 

in-page empty, **_developed by_** should go above in-page nav

![Screenshot_20190530-193723_Chrome](https://user-images.githubusercontent.com/19961574/58672633-e28db380-8315-11e9-8d5c-223d4b733546.jpg)

**Comment by jeremyzilar** [comment]
Related to https://github.com/GSA/digitalgov.gov/issues/1074

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
