### ISSUE TITLE
Demo: copy change for sidebar link (all CoP pgs)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1076]
Change
> Listserv admin and archive (link doesn't work)

to two sep links

> Manage Your Listserv Subscription https://digital.gov/communities/manage-your-subscription/ 

> Access the Listserv Archive https://digital.gov/communities/manage-your-subscription#Access-Listserv-Archive

![Screenshot_20190531-100549_Chrome](https://user-images.githubusercontent.com/19961574/58711269-2c18e580-838c-11e9-9515-9d14d6e969fa.jpg)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
