### ISSUE TITLE
Demo: YouTube glitch when scrolling, iOS and Android

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1079]
YouTube player floats over menu bar when scrolling, both iOS and Android

![event stage from iOS](https://user-images.githubusercontent.com/19961574/58713577-dabf2500-8390-11e9-8bee-1d123e29a97b.png)

**Comment by jeremyzilar** [comment]
Thanks! Will fix

**Comment by jeremyzilar** [comment]
This should be fixed now
