### ISSUE TITLE
Migrate all the old posts from Medium into the site

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#108]
We currently have a number of posts in Medium that we need to export and move into Federalist: https://medium.com/@DigitalGov

Once they are exported, we can easily transform them into markdown.
Note: The images might need to be uploaded separately and linked into the posts.

**Comment by ToniBonittoGSA** [comment]
Am adding images here: https://drive.google.com/drive/folders/0B-EvLd5KvVOFZE93bDlOak1JTzg

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Does this still need to happen? If so, I can bulk import them. Let me know.

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA can you pass over the XML file (or any export file) from Medium ? That will help
