### ISSUE TITLE
Create and Open Opportunity for Content Clean-up

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1089]
We have a lot of content cleanup issues in our repo, and we could use some help
https://github.com/GSA/digitalgov.gov/issues?q=is%3Aissue+is%3Aopen+label%3A%22content+cleanup%22

Here is the Open Opps template: https://docs.google.com/document/d/1tEKTE4iynSdi9tZlkxoxenh91bxARpKNxrXTcXo_geI/edit

Here is a previous submission: 
https://docs.google.com/document/d/1to7NUnar0if8maF8f7OduyOxm2IEDg0yP2lUV0XelCk/edit

**Comment by ToniBonittoGSA** [comment]
Folder: https://drive.google.com/drive/u/0/folders/1BYJt7fSleMeQ2AJVbP9I7NigHpDEO6K3
