### ISSUE TITLE
6/13 FEMA app blog draft

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1090]
**Title**: Building Trust with Users Through Open Communication and Feedback

**Summary, Deck**: A look at how the Federal Emergency Management Agency (FEMA) responds to user needs and bugs in their app development

**Topics**: mobile, apps, FEMA, 

**Pub Date**: Thursday, June 13 (Mobile Thursdays)

**Author**: R. (Fitz) Fitzhenry

“If it’s not broke, don’t fix it,” doesn’t work with mobile apps. A patch, update, or platform change upstream often means preventive maintenance downstream. The unavoidable fixes keep things from getting dammed up, even if there’s no sure way to prevent every interruption of the information flow.

There’s a less tangible but equally unavoidable reason for fixing apps that aren’t broken: to keep them interesting for people. Those fixes come in the quest for improvement and they keep the relationship with users healthy.

The Federal Emergency Management Agency (FEMA) recently navigated this realm between advancing technology, user demands, and relationships with its emergency alert and safety information app. The in-demand feature of the app, those emergency alerts, started acting up.

“Hello developers,” posted the_moongirl under her two-star app rating in the App Store in early 2019, “I am a meteorologist and had been recommending this app to all of my friends for robust and reliable weather alerting. Everything about it was great. Within the last couple of months, I stopped getting alerts.”

Even if every technology consumer wants their new, better thing to be glitch free, experience tells reasonable people perfection comes infrequently. There’s room for slack in that reality, though no room for slacking.

FEMA’s response to the_moongirl’s concerns, and to others who’d also lost their alerts, seemed both surprising and encouraging in its normalcy. Their reply reflected reality and was, dare I say it, human. That’s something embraced by the public, if not always natural for government.

In reply to the_moongirl, FEMA wrote, “Thank you for your feedback. We will be releasing an update to the FEMA App (version 2.10.4) in the next week or so. This updated version should address the issue you are experiencing about not receiving notifications. We apologize for the inconvenience. We rely on feedback from users like you to inform future development.”

I reached out to FEMA about their app and their philosophy for relating to the public. I complimented their willingness to reply like a person to the people running their app.

“We listen to our users,” affirmed Daniel Kuhns, Digital Program Manager at FEMA, noting interactions needn’t be faceless. “We want our app to work best for the people who rely on it. And we are transparent about both our limitations and commitments.”

The FEMA app promises to inform people about the risks they face so they know what to do before, during, and after disasters. It simultaneously pushes National Weather Service alerts to users for up to five zip codes a person selects. The key feature amplifies NWS and local notifications, acting as a redundancy, not a replacement.

“We believe in a user-centric process and put user needs first,” Kuhns explained. “The app only matters if it works for real people using it.”

It seems the relationship and the dialogue with users is living up to promises. In 2018, “We implemented daily auto-testing of the alert function after user comments,” said Kuhns. That practice doesn’t pester users with test-alerts, but alerts are visible from the FEMA side.

The two big changes in 2018 users could see were ones they’d asked for. The first swell of demand asked for more control over the alerts. People wanted the ability to customize alerts for each location they entered. FEMA upgraded its app to allow selection or deselection of alerts from more than 100 specific types of alerts organized in 11 categories. From fire weather to frost warnings to fog and other personal concerns, users gained the power to pick and choose.

Last year’s second big change brought functionality beyond NWS alerts to include alerts from the Integrated Public Alert and Warning System. The addition expanded alerts to include evacuations, abductions, law enforcement issuances, and other warnings generated by local authorities. As with NWS alerts, the IPAWS alerts are a redundancy, not a replacement, to benefit the public interested in time-sensitive safety information. Needs don’t get much more personal than that.

Users say the recent bug causes some alerts to only appear as notifications once they open the app. FEMA addressed it in the last release, though it hasn’t been easy to replicate in all scenarios. So the team at FEMA stayed focused on fixing that for the next update, 2.10.5, due in June. June marks the start of hurricane season and also the season of “no big app changes” for FEMA. 

There’s confidence the pending release will address the bug, and FEMA has moved to automatic updates for users who allow it. The move to pushing updates meant finding middle-ground to lessen the number of older app versions running and acting up. FEMA had held off forced updates out of respect for their relationship with users.

“The best user safeguard is for people to make sure they’re running the most recent version,” said Kuhns. “And get in touch with us if they’re experiencing app issues.”

FEMA believes listening drives the best design and communication builds trust. When the technology acts up—which is inevitable—the relationship has the integrity to withstand it. That’s a pretty strong and pretty normal model.

“The best email we can receive is a simple response that says, ‘Thanks! It’s working now,’” said Kuhns.

**Comment by ToniBonittoGSA** [comment]
![FEMA 2019 tablet home screen](https://user-images.githubusercontent.com/19961574/59296680-8f402d00-8c54-11e9-9cb5-32e13353fff5.png)

**Comment by ToniBonittoGSA** [comment]
alt text: A screen capture of three alerts on the FEMA app's Alerts screen.
caption: 

![FEMA 2019 tablet alerts screen](https://user-images.githubusercontent.com/19961574/59296695-98c99500-8c54-11e9-8ae5-0c94a2811d5d.png)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
