### ISSUE TITLE
Make improvements to the Terms of Service Agreements pages

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#111]
The Negotiated Terms of Service Agreements page is one of our most visited pages.
We should make some improvements to these pages so that they are more readable.

- https://demo.digitalgov.gov/resources/federal-compatible-terms-of-service-agreements/
- https://demo.digitalgov.gov/resources/negotiated-terms-of-service-agreements/
- https://demo.digitalgov.gov/resources/agency-points-of-contact-for-federal-compatible-terms-of-service-agreements/

**Comment by thisisdano** [comment]
Related to #119 (Long pages are difficult to navigate)

**Comment by jeremyzilar** [comment]
Closing. Too vague. Also similar to the other vague and open issue: https://github.com/GSA/digitalgov.gov/issues/237
