### ISSUE TITLE
Create internal checklist for YouTube live set-up

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#113]
There are many tasks associated with setting up a YouTube live event and we need a document/checklist with all of those tasks. Some examples of specific tasks:

- requesting title card week prior to event
- immediately publishing the captions
- moderating the live chat questions
- a/v troubleshooting (volume levels change on mics, make sure batteries are fresh.)
- lighting adjustments
- camera adjustments
- presenters logging troubleshooting (grayed out screen and adding them as managers of DG YT account)
- etc.

**Comment by jeremyzilar** [comment]
This is great @jthalls — Maybe this is a good candidate for the Wiki https://github.com/GSA/digitalgov.gov/wiki

**Comment by jthalls** [comment]
here's the doc for review: https://docs.google.com/document/d/14VJbxu-3BQugEIcpSmnB_qeTg_c2HGgmNf63YUSRAt0/edit

**Comment by jeremyzilar** [comment]
Can we add this to the Wiki as well?

**Comment by jeremyzilar** [comment]
We are going to print these out an put them in the studio to test their effectiveness.
