### ISSUE TITLE
Develop a Framework for our Style Guide

### ISSUE THREAD

**Issue by AndreaSigz** [GSA/digitalgov.gov#114]
We have a Style Guide we created for DigitalGov when we launched in 2014. It's been updated a few times since then, but with our move to digital.gov and on the Federalist platform, we should take another look and update. 

We should also include any guidance around our new brand, in the updated Style Guide.
Here is the doc: https://docs.google.com/document/d/1QPSNAa9GGoy_BoaAlQ0yP6uDuIG_eijoYW5x6Qxy7gk/edit#

--- 

## it should include …
- [x] they top, key buckets for our style guide
- [x] recommendations on should be in those buckets

## it's done when …
- [x] it has been presented to the team
- [x] everyone feels like it is ready to start being populated

**Comment by jeremyzilar** [comment]
Yes 🎉 — Here is a link to the style guide in the Wiki https://github.com/GSA/digitalgov.gov/wiki/Style-guide

**Comment by AndreaSigz** [comment]
Nice!

**Comment by AndreaSigz** [comment]
The event page style guide issue #116 is related to this! @jthalls

**Comment by jeremyzilar** [comment]
This has been done 🎉
