### ISSUE TITLE
look at FY18 DGU metrics sheet and re-evaluate the metrics we're collecting

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#115]
We collect information about our DGU classes BUT are we collecting and tracking the right information? How is this information helping us tell a story and measuring impact?

FY17 metrics - https://docs.google.com/spreadsheets/d/1-YmxSGxY3Fz7-PHS4CyYjMTmBEnG_nlsCO1u4uEyYDU/edit#gid=1083370486
FY18 metrics - https://docs.google.com/spreadsheets/d/197hFlT9Rnf00iIs3huf8YlomsKwWAMoKbxT7ooxsZ_Y/edit#gid=1083370486

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
