### ISSUE TITLE
Create three separate videos from cloud.gov workshop

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#117]
Three videos (from: https://youtu.be/bXppIJ1K3GM)

1. the case for cloud.gov 
2. getting set up and 
3. the hands-on labs

- [x] edit videos in iMovie (plus trim out the bit where folks were catching up)
- [x] title cards for all three videos   @thisisdano to create
- [x] captions for videos
- [x] tags and descriptions for each video for YouTube (Peter Burkholder to provide)

**Comment by jthalls** [comment]
@SoncerrayBolling I reviewed the three videos and made comments/notes on your doc:
https://docs.google.com/document/d/1I-ebMKB9PjFDnO84Asx5vcx_X5fFc1U6Yg1mTN06u48/edit

**Comment by jeremyzilar** [comment]
➕ @pburkholder — When you have the tags and descriptions for each video for YouTube, you can paste them here.

**Comment by jthalls** [comment]
Part 1: Case Study for cloud.gov - https://youtu.be/LKb0liZyepA
Part 2: Getting Set-up - https://youtu.be/ip8G_Rafb_c
Part 3: Hands-on Lab - https://youtu.be/G2J8dxSF0-I

**Comment by pburkholder** [comment]
I've watched through all three videos and I'm really happy w/ the editing choices y'all have made. I have just two changes to ask:

[_] From video 3 cut from 07:55 to 09:40. It's me talking to one person about his access to cloud.gov, and not only is it irrelevant, but I give the wrong answer :(.
[_] Change title slide of video 1 to "The Case for cloud.gov"

Thanks! Peter

**Comment by SoncerrayBolling** [comment]
@pburkholder The above-requested video edit and title card change are complete.  When you have the tags and descriptions for each video for YouTube, you can paste them here.

**Comment by jeremyzilar** [comment]
**Why cloud.gov? (27 minutes)**

How cloud.gov enables mission focus, reduced lead time, ensures security, and saves tax dollars while enabling your agency to better provide great public service.

GSA’s cloud.gov is the high-performance Platform-as-a-Service (PaaS) by and for the federal government. Imagine a secure cloud environment where your team can get up and running in minutes, then build, manage, and release applications with a radically shortened path to achieving Authority to Operate from your agency. By practicing DevSecOps with cloud.gov, you and your team can deliver at the “speed of mission.”

Check out what we offer: https://cloud.gov

**Tags:** `PaaS, "cloud foundry", "compliance", "ATO", FISMA, DevOps, webapps, FedRAMP`

---

**Getting set-up with cloud.gov (4 minutes)**

A walk-through of the initial registration process, including the setup of your one-time password application.

GSA’s cloud.gov is the high-performance Platform-as-a-Service (PaaS) by and for the federal government. Imagine a secure cloud environment where your team can get up and running in minutes, then build, manage, and release applications with a radically shortened path to achieving Authority to Operate from your agency. By practicing DevSecOps with cloud.gov, you and your team can deliver at the “speed of mission.”

Check out what we offer: https://cloud.gov

**Tags:** `PaaS, "cloud foundry", "compliance", "ATO", FISMA, DevOps, webapps, FedRAMP`

---

**Hands-on lab (41 minutes)**

Install the Cloud Foundry tools, connect to cloud.gov, and start running applications on cloud.gov: from a static site, to a multi-node application with a data backend. We introduce you to the cloud.gov architecture and concepts, and touch on logging and debugging your running application.

GSA’s cloud.gov is the high-performance Platform-as-a-Service (PaaS) by and for the federal government. Imagine a secure cloud environment where your team can get up and running in minutes, then build, manage, and release applications with a radically shortened path to achieving Authority to Operate from your agency. By practicing DevSecOps with cloud.gov, you and your team can deliver at the “speed of mission.”

Check out what we offer: https://cloud.gov


**Tags:** `PaaS, "cloud foundry", "compliance", "ATO", FISMA, DevOps, webapps, FedRAMP`

**Comment by SoncerrayBolling** [comment]
I have reviewed the descriptions and edits.  Everything looks great!
