### ISSUE TITLE
tabbing/accessibility error -- resource page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1259]
discovered going thru preview for https://github.com/GSA/digitalgov.gov/pull/1257 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/law-notice/resources/required-web-content-and-links/ 

1) When I use the tab key, it goes thru all of the AddThis social media icons, top and bottom, first.
2) If I click on a link, whether it goes to a file or another page, when I hit the back button, the tabbing starts again at the top AddThis icons-- not the section of text I was reading

**Comment by jeremyzilar** [comment]
Closing, as AddThis is no longer on the site
