### ISSUE TITLE
Create/Update DGU email templates

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#128]
create new templates for:

- confirmation email when people register for an event
- reminder emails (day prior, day of) for event
- post-event email

**Comment by jeremyzilar** [comment]
What would you think about putting these in the Wiki?
https://github.com/GSA/digitalgov.gov/wiki

**Comment by jeremyzilar** [comment]
We made some progress here: https://github.com/GSA/digitalgov.gov/wiki/Event-Email-Templates

**Comment by jthalls** [comment]
@SoncerrayBolling I updated the Eventbrite template with the new emails. Also, I added the new post-event eval to the DGU draft box

**Comment by jeremyzilar** [comment]
🎉 This looks great!
