### ISSUE TITLE
Add USWDS "An official gov't website" banner

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#129]
Best example at https://www.usa.gov/ 

18f.gov and many others are missing the newer "Here's how you know" link that expands the banner

**Comment by thisisdano** [comment]
Can anyone think of any reason why we wouldn't want to do this? Anything that we'd want to do before this?

I think it'd be relatively simple to implement.

**Comment by AndreaSigz** [comment]
Nope. It would be great to get this on DigitalGov

**Comment by thisisdano** [comment]
OK, thanks! I'll assign myself and we'll get it done!

**Comment by thisisdano** [comment]
Now, to see how well the USWDS plays with our site...

**Comment by ToniBonittoGSA** [comment]
Howdy... 
I just noticed that the space after the w in know (between know and the down arrow) is linked; it should not be. The same problem is on USA.gov so maybe it's universally incorrect. 
Who can fix that? See attached screen cap 

![screen shot 2017-11-07 at 12 15 06 pm 2](https://user-images.githubusercontent.com/19961574/32507517-a243bdcc-c3b5-11e7-8d5c-32d83141bbe3.png)

**Comment by ToniBonittoGSA** [comment]
and 
![screen shot 2017-11-07 at 12 20 53 pm 2](https://user-images.githubusercontent.com/19961574/32507664-14d42606-c3b6-11e7-8f2f-71488a858b5b.png)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
