### ISSUE TITLE
Links Broken [page error]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1307]
### URL / Link to page
https://digital.gov/2013/10/30/content-management-systems-toolkit/

### What seems to be the problem (1 sentence)
There are three (3) bullet list in first paragraph that all go to the same main page of digital.gov. 

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by saracope** [comment]
Tested and these links are working now. Closing out. Thanks!
