### ISSUE TITLE
Link Goes to Incorrect Page [page error]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1308]
### URL / Link to page
https://digital.gov/2013/11/01/federal-government-challenges-and-contests/

### What seems to be the problem (1 sentence)
The link for Challenge Platforms, in the last paragraph, send user to a GSA library page. 

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by saracope** [comment]
@twgsa16 Where should `Challenge platforms` in this paragraph link to?

> 
**​Challenge platforms** are the online tools that provide a forum for the seeker to post the problem, or call-to-action, and invite a community of solvers to suggest, collaborate on, and judge solutions.
