### ISSUE TITLE
online event: FedRAMP Tailored: Overview of the Finalized New Baseline

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#131]
Online event scheduled for 11/15 1pm - 2pm ET

event page: https://demo.digitalgov.gov/event/fedramp-tailored-overview-finalized-new-baseline/
YouTube live link: https://www.youtube.com/watch?v=MC6GfzTnaNY
FedRelay link: http://www.fedrcc.us//Enter.aspx?EventID=3444144&CustomerID=321
Google forms eval (attendee): https://docs.google.com/forms/d/e/1FAIpQLSflrZpvm3TqdxgsYYMTUNeEvWKm2UkqiujWXh1uVTELMH8H5g/viewform?usp=sf_link

**Comment by jthalls** [comment]
- [ ] post event page on DigitalGov
- [ ] Create YouTube live event
- [ ] Create event in Eventbrite
- [ ] Schedule emails through Eventbrite
- [ ] Schedule real time captioning through FedRelay
- [ ] Track registration and provide event partner weekly registration updates
- [ ] Set up evaluation in Google Forms
- [ ] Schedule tech check with presenters to review online platform and logistics of event
- [ ] Identify moderator for live chat/online questions
- [ ] Schedule post event/training retro
- [ ] Request video title card
- [ ] Add title card immediately following event

**Comment by jeremyzilar** [comment]
Here is the event copy
---
An introduction to the newly released security baseline, FedRAMP Tailored, which is designed for Cloud Service Providers (CSPs) with Low-Impact Software- as-a-Service (LI-SaaS) Systems. The webinar will address what FedRAMP Tailored is, how it was developed, how the finalized version differs from draft versions released for public comment, and other useful information geared toward CSPs, agencies, and 3PAOs. Discussion also address how to begin a FedRAMP Tailored authorization.

**Comment by jeremyzilar** [comment]
Here is the event page on DEMO: https://demo.digitalgov.gov/event/fedramp-tailored-overview-finalized-new-baseline/
