### ISSUE TITLE
Add DGU blurb to the top of events section 

### ISSUE THREAD

**Issue by Schultea** [GSA/digitalgov.gov#1319]
### 

Add DGU blurb to the top of events section above "Upcoming Training & Events". 

It could be: 

**DigitalGov University**
We provide a range of free online and in-person trainings and events for people and teams across the federal government. Many of our events highlight innovations, case studies, tools, and resources. Below you will find upcoming events, and past events with embedded recordings. All of our events are also archived on YouTube.

**Comment by ToniBonittoGSA** [comment]
Looks good! 
Note ~ "Upcoming Training & Events" is the page title; copy would go below that. 

I would just replace `We` with `[**DigitalGov University**](https://digital.gov/digitalgov-university/) (DGU)`

**Comment by jeremyzilar** [comment]
I would make it one line and shorten it to just — 

> **Digital.gov University** provides a range of free, online, and in-person trainings and events for people and teams across the federal government, highlighting the innovations, case studies, tools, and resources people need most. [Learn more »](#)

The events below and the link to YouTube should be obvious through the navigation

**Comment by Schultea** [comment]
Perfect! I think it would be great to include DGU language here.

**Comment by Schultea** [comment]
Hmm, not sure I have the ability to edit that page directly?

**Comment by jeremyzilar** [comment]
yeah, I will need to add that in @Schultea. Will get to that in the coming days!

**Comment by Schultea** [comment]
Perfect!

**Comment by jeremyzilar** [comment]
I would like to push this into the DEMO site as well

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
