### ISSUE TITLE
Social Media Footer Links

### ISSUE THREAD

**Issue by DanielJPino-ux** [GSA/digitalgov.gov#1334]
### What seems to be the problem (1 sentence)

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

The Twitter, Facebook and YouTube links on the footer of the pages for demo.digital.gov do not lead to their respective pages.

However,  links for these sites are correct in page content here: https://demo.digital.gov/about/subscribe/

ALSO we may want to add a link in the subscribe page that says "Follow us on YouTube" in the main body of the page as well: https://www.youtube.com/digitalgov

**Comment by jeremyzilar** [comment]
Nice catch @DanielJPino-ux

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
