### ISSUE TITLE
[Suggestion] Image and Underscores

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1338]

**Comment by evelyntorres1** [comment]
see pull request #1508; removed underscore signs but dont know how to fix image size so issue is still open.

**Comment by ToniBonittoGSA** [comment]
See note by me in the Pull Request, https://github.com/GSA/digitalgov.gov/pull/1508

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
