### ISSUE TITLE
10/10 post: Money Adventure, pt 2

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1361]
For PR https://github.com/GSA/digitalgov.gov/pull/1362 

The Federal Reserve Board’s U.S. Currency Education Program recently launched the _[Money Adventure](https://www.uscurrency.gov/educational-materials/classrooms/money-adventure-mobile-app)_ Android app. _Money Adventure_ is a fun, interactive app that teaches the next generation of cash users about the historical designs and robust security features of U.S. currency. 

![Money-Adventure_Note-Back_Android_Acer-Tablet](https://user-images.githubusercontent.com/19961574/66514291-d4615800-eaaa-11e9-8202-6d5f8c07eda1.png)
**Alt text**: A screen capture of the app's note back explorer in use on an Android tablet. Along the top are buttons for home, and seven bill denominations ($1, $2, $5, $10, $20, $50, and $100) that users can select and explore. Four elements on the back of a $1 bill are circled in white. In the lower right corner is an illustration of Buck the Time-Traveling Dog who guides the user on a quest through the historical events illustrated on the back of U.S. currency.

The iOS version of _Money Adventure_ launched in January 2019. As the Federal Reserve Board’s [first public mobile app](https://digital.gov/2019/03/05/using-augmented-reality-teach-kids-about-currency/), the iOS app increased the value of the central bank’s digital outreach. However, market research revealed that not all educators have access to Apple devices in their classrooms. Many use Android devices, such as Chromebooks, for in-class instruction. To expand the usability of _Money Adventure_ and ensure that as many students as possible have access to the app, the Federal Reserve Board developed an Android version of the app. 

![Money-Advenure-Android_20-dollar-bill-zoom](https://user-images.githubusercontent.com/19961574/66514230-b562c600-eaaa-11e9-9bae-30a0bec8fd0c.jpg)
**Alt text**: A screen capture of the zoom feature in use on the app. It shows the front of a 20 dollar bill, with a circle around a small part of the bill that shows a detailed closeup of that section. 

Similar to the iOS version, the Android version of _Money Adventure_ contains a note front and note back explorer. The note front explorer reveals the unique security features of the $20 bill to students as they interact with the virtual banknote. The Android app contains a 3D note back explorer that allows students to go on a quest through historical events illustrated on the back of U.S. currency. While this experience differs slightly from the augmented reality experience that can be found in the iOS app, students are still able to view 3D images and videos of the historical designs depicted on the back of banknotes. After downloading the app, students can venture through the app on either operating system without an internet connection. 

Download the app in the [Google Play Store](https://play.google.com/store/apps/details?id=com.taoti.moneyadventure) for Android devices or the [App Store](https://apps.apple.com/us/app/money-adventure/id1446642877) for Apple devices! 

{{< youtube Z4XCkDhve20 >}}

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
