### ISSUE TITLE
Editorial [Suggestion]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1379]
### URL / Link to page
https://digital.gov/services/

### Tell us how we can make this page better
I am not a great grammarian but I think the paragraph under the "eCPIC" heading could be broken into two sentences.

**Comment by afeijoo** [comment]
@jeremyzilar and @ToniBonittoGSA - The eCPIC team provided this updated text:

> The Electronic Capital Planning and Investment Control (eCPIC) application was developed to address agency needs for a more organized and transparent approach to IT capital planning. It is a web-based, government-owned, fee-for-service, federal shared software-as-a-service solution. Federal agencies use eCPIC to support their internal IT portfolio management, IT capital planning, and IT governance processes. The eCPIC application also enables agencies to meet their external IT project cost, schedule, risk, and performance reporting requirements to the Office of Management and Budget (OMB) Office of the Chief Information Officer (OFCIO).

**Comment by jeremyzilar** [comment]
Thank you @onelisadunc-dev and @afeijoo, will update!

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
