### ISSUE TITLE
Remove Sites/CMS from Services nav and page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#138]
https://www.digitalgov.gov/services/

**Comment by jeremyzilar** [comment]
There were a number of links to the SITES page from within the site. I just fixed this. Should be good everywhere now.

**Comment by jeremyzilar** [comment]
This is being fixed here: https://github.com/GSA/digitalgov.gov/pull/154

**Comment by thisisdano** [comment]
Fixed by #154
