### ISSUE TITLE
Create DGU event moderator opener/closer script

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#140]
We want to create a moderator script to be sure they cover all necessary information at both the beginning and end of each event. It will also be helpful as a guide for how long introductions of presenters should be and anything else relevant to moderating an online event.

**Comment by jthalls** [comment]
Please review the first draft in google docs @jeremyzilar @SoncerrayBolling:

https://docs.google.com/document/d/1NSVLLZmGo7B5HwABiwi67oNrYr1jx6fLIrxCHmXRkzg/edit 

@AndreaSigz could use your input too!

**Comment by jeremyzilar** [comment]
Once this is ready, can you link this in the Wiki?

**Comment by jeremyzilar** [comment]
This looks great. Let's try to use this for an upcoming event and see how well it works.
