### ISSUE TITLE
1 DGU podcast article is missing

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#141]
6 podcasts are on *iTunes* and *SoundCloud*
https://itunes.apple.com/us/podcast/digitalgov-podcast/id1042016789 
https://www.soundcloud.com/digitalgov (have to be logged out of GSA network to view)

--- 
DigitalGov Podcast: Behind the Scenes of the Social and Behavioral Science Team
https://www.digitalgov.gov/2016/04/04/digitalgov-podcast-behind-the-scenes-of-the-social-and-behavioral-science-team/

DigitalGov Podcast: DAP Delivers Data for 4,000 Websites
https://www.digitalgov.gov/2015/06/29/digitalgov-podcast-dap-delivers-data-for-4000-websites/

DigitalGov Podcast: Leaders Come and Go, But Your Customers Will Remain
https://www.digitalgov.gov/2015/07/17/digitalgov-podcast-leaders-come-and-go-but-your-customers-will-remain/

DigitalGov Podcast: The Secrets Behind CIA Social Media
https://www.digitalgov.gov/2015/08/25/digitalgov-podcast-the-secrets-behind-cia-social-media/

DigitalGov Podcast: Bridging Content and Discovery Through DigitalGov Search
https://www.digitalgov.gov/2015/10/30/digitalgov-podcast-bridging-content-and-discovery-through-digitalgov-search/

**1 is missing on site**:
DigitalGov's Inaugural Podcast: How IVR Supports Contact Centers
https://www.digitalgov.gov/2015/04/30/digitalgovs-inaugural-podcast-how-ivr-supports-contact-centers/

**Comment by ToniBonittoGSA** [comment]
just a side note ~ looks like a lot of sites feature our podcasts

noticed when I googled ["How IVR supports contact centers"](https://www.google.com/search?num=30&newwindow=1&safe=active&ei=NIjzWf2jEcyY0wK5ybHgCQ&q=%22How+IVR+supports+contact+centers%22&oq=%22How+IVR+supports+contact+centers%22&gs_l=psy-ab.3...3717856.3726319.0.3726554.34.24.0.0.0.0.445.3620.2-7j4j1.12.0....0...1.1.64.psy-ab..22.8.2495...0j0i10k1j0i22i30k1j33i22i29i30k1j33i160k1j33i21k1.0.y2gRXkwrwXA) (with quotes)

**Comment by jeremyzilar** [comment]
I think all of these links have been fix and are now working.

**Comment by jeremyzilar** [comment]
Can you verify @ToniBonittoGSA
