### ISSUE TITLE
[images] missing, links take you to image though

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1417]
### all images are not present in article but the links take you to the image.
https://s3.amazonaws.com/digitalgov/_legacy-img/2014/08/948-x-599-OCSE_1a.jpg
https://s3.amazonaws.com/digitalgov/_legacy-img/2014/08/911-x-537-OCSE_2a.jpg
https://s3.amazonaws.com/digitalgov/_legacy-img/2014/08/710-x-744-OCSE_3a.jpg
https://s3.amazonaws.com/digitalgov/_legacy-img/2014/08/837-x-709-OCSE_4a.jpg
https://s3.amazonaws.com/digitalgov/_legacy-img/2014/08/757-x-444-OCSE_5a.jpg
https://s3.amazonaws.com/digitalgov/_legacy-img/2014/08/739-x-545-OCSE_6a.jpg

**Comment by jeremyzilar** [comment]
Thank you, great catch @evelyntorres1 👍
