### ISSUE TITLE
[links] page not found errors

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1418]
### first link: http://www.ptsd.va.gov/public/materials/apps/PTSDCoach.asp, does take you to a VA website but the page not found 404 error pops up in the webpage.

DOL Timesheet app link also, 404 error

**Comment by jeremyzilar** [comment]
Good catch — maybe we can have an automated script that check links for 404s?
This is the correct URL https://mobile.va.gov/app/ptsd-coach

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
