### ISSUE TITLE
Contact Us page has link to .md file

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#142]
https://www.digitalgov.gov/contact-us/ 

Link on article guidelines goes to https://www.digitalgov.gov/join-digitalgov.md 
should be: https://www.digitalgov.gov/join-digitalgov#guidelines (there's an anchor link on the H2)

**Comment by jeremyzilar** [comment]
The former links were pointing to specific IDs within the page. Those came over as
{{< link "join-digitalgov.md#guidelines.md" >}}
and were replaced with:
{{< link "join-digitalgov.md" >}}

There were a number of pages that needed this fix

**Comment by jeremyzilar** [comment]
This is being fixed here: https://github.com/GSA/digitalgov.gov/pull/154

**Comment by thisisdano** [comment]
Fixed by #154
