### ISSUE TITLE
Digital.gov Youtube Site

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1424]
YouTube Channel
- [ ] It would be nice if the tabs on the Youtube site should be filled out. Information in the About, Community, and channels tabs...

**Comment by jeremyzilar** [comment]
@onelisadunc-dev You are talking about our YouTube page here? https://youtube.com/digitalgov

And these are the tabs you're talking about?

![image](https://user-images.githubusercontent.com/395641/69276758-04714000-0bad-11ea-85c8-42332b0d6d65.png)

**Comment by onelisadunc-dev** [comment]
yes, I am suggesting that the ABOUT tab have more information. the line in the about tab is fairly generic. Just a minor suggestion.
