### ISSUE TITLE
Resources page Search Box: inconsistent results accuracy

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#143]
Resources search box on https://www.digitalgov.gov/resources/

1) I searched for *[analytics](https://search.usa.gov/search/docs?utf8=%E2%9C%93&affiliate=digitalgov&dc=1678&query=analytics&commit=Search)* and got 5 pages of results..
a - 32 of 41 results have this in results summary:
_*Challenges & Prizes · Content Management Systems · CrowdSource Mobile Testing · Data.gov · Digital Analytics Program (metrics) · Electronic ... *_
but that text is not anywhere on those pages; it's from the Services drop down menu. 
b - the Resources page is included in results (shouldn't that be filtered out?)

2) I searched for *[Section 508](https://search.usa.gov/search/docs?utf8=%E2%9C%93&affiliate=digitalgov&dc=1678&query=Section+508&commit=Search)* 
Got 1 page of results.. the Resources page is also included in results, but all else is normal; "section 508" appears in text of those pages. 

3) Searched for *[CMS](https://search.usa.gov/search/docs?utf8=%E2%9C%93&affiliate=digitalgov&dc=1678&query=CMS&commit=Search)* 
Got 1 page of results.. 
 - the Resources page is also included in results
 - 2 resource pages don't have anything to do with CMS/content management systems: 
Checklist of Requirements for Federal Websites and Digital Services
https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/
Top 10 Best Practices for Multilingual Websites
https://www.digitalgov.gov/resources/top-10-best-practices-for-multilingual-websites/

**Comment by jeremyzilar** [comment]
I am guessing that this was an issue before moving to Federalist as well, since we did not change anything around how Search is configured.

**Comment by ToniBonittoGSA** [comment]
Not sure; can't recall the last time I used that search box (I usually use the main/site one in the header) - just noted so we can dig into when there's time.
