### ISSUE TITLE
Broken: legacy image, YouTube embed

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1432]
https://digital.gov/2011/11/28/battle-royale-mobile-web-versus-mobile-apps/ 

- [ ] 1 broken image, 
- [x] 1 YT embed needs Hugo shortcode https://github.com/GSA/digitalgov.gov/wiki/Hugo-shortcodes

**Comment by ToniBonittoGSA** [comment]
Alt text: A photo of two fighting Topis (antelopes) head-butt each other, locking horns, in a grassy field.

Caption: Stuart Barr, CC BY-NC-SA 2.0, flickr.com

![Fighting-Topis_antelopes_11-17-08_Stuart-Barr_CC_BY-NC-SA_2 0_3122717154_9a061d4fc5_o](https://user-images.githubusercontent.com/19961574/69659420-24d94880-104c-11ea-9041-b1cf4cc2d898.jpg)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾https://digital.gov/2011/11/28/battle-royale-mobile-web-versus-mobile-apps/
