### ISSUE TITLE
404 page layout (duplicate content)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#146]
https://www.digitalgov.gov/foofoofoofoo 

should be a 1 column page when we're able to, or the right column/sidebar should have different content; as is, Recent Posts is on this page twice

**Comment by jeremyzilar** [comment]
When I make a 1-coluumn template, similar to the one we had on the old site, this will be fixed. Until then, there is not an easy fix.

**Comment by jeremyzilar** [comment]
We might even come up with a whole new 404 page template before then.

**Comment by jeremyzilar** [comment]
This is still needed.
