### ISSUE TITLE
New events and reach out to partners to schedule 

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#148]
Reach out to OPP program leads, DG Community leads, 18F partners to schedule events in the upcoming months:

DAP team
Search team
Innovation Portfolio programs
other OPP programs?
18F partners we've worked with in the past
DG Community Leads

**Comment by AndreaSigz** [comment]
@jeremyzilar Can you give me some additional context around this? Thx!

**Comment by jeremyzilar** [comment]
This is a running list of topics + ideas for interviews, conversations, Q&As, and explainers that we can produce over video. Feel free to add them here.
https://docs.google.com/document/d/1uIGZqm8hqNXiK89Hng8L1cLrFeBXM9pM8jeAb1sfdLU/edit?ts=59fb4b21

Our goal at the start is to get a number of ideas internally, work through the challenges of producing these videos, and do it again. Each video is an opportunity to make our production better and refine our voice and direction.

Once we have a body of videos out there that represent a direction, we can ask others in the community for ideas.

**Comment by jeremyzilar** [comment]
Closing.
