### ISSUE TITLE
[Images]Clean up

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1485]
## Issue

**Title** — **Trends on Tuesday: 8 Ways To Format Tables for Responsive Web Design**
**Demo URL** — https://demo.digital.gov//2014/10/28/trends-on-tuesday-8-ways-to-format-tables-for-responsive-web-design/
**Live URL** — https://digital.gov//2014/10/28/trends-on-tuesday-8-ways-to-format-tables-for-responsive-web-design/

---

**Images have 3 'expand in new window' icons surrounding the image. It looks strange and the images do not have captions throughout the article.

**Comment by Johnny939** [comment]
None of these links are working they go into a 404 Error.

**Comment by evelyntorres1** [comment]
@jeremyzilar @ToniBonittoGSA 
i used the blue, then red buttons to submit all the issues yesterday, 11/13, and it looks like all the links that auto-populated into the issues i submitted, take you to a 404 error message.
