### ISSUE TITLE
Add 2 images to new Event

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1497]
Pls align right at bios on https://digital.gov/event/2019/11/19/socialgov-talk-reaching-small-businesses-in-digital-environment/ 

Paul Lester
![250-x-250_Paul-Lester](https://user-images.githubusercontent.com/19961574/68796763-6b2cb180-0621-11ea-8116-b9932f317477.jpg) 

![250-x-250_Natale-Goriel](https://user-images.githubusercontent.com/19961574/68796764-6b2cb180-0621-11ea-966b-c67edceb38da.jpg)

**Comment by Johnny939** [comment]
The changes from @jeremyzilar look great.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
