### ISSUE TITLE
Consistency in Bullet Points [Suggestion]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1510]
### URL / Link to page
https://digital.gov/services/dap/

### Tell us how we can make this page better
Consistency with bullets. At the top of the page there are 4 bullet points, only the last bullet has a period at then end of the sentence. I would suggest adding periods to all bullet points or remove last period.

**Comment by jeremyzilar** [comment]
Good catch @onelisadunc-dev !

This is the type of thing we could catch with an automated test, which is something I have been exploring.
