### ISSUE TITLE
Update the Hubspot DNS records for email sending domains

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1513]
There are a few things we'd like to accomplish around our integration with Hubspot

---

## 1. We'd like to update the DNS records with the updated Hubspot dedicated IP addresses for all of our sending domains

Can you please help us to understand what we records need to change on our end?

#### Current DNS for digitalgov.gov
I copied out what I believe are all of the relevant DNS records, but you can [see all the DNS records for digitalgov.gov here](https://github.com/18F/dns/blob/master/terraform/digitalgov.gov.tf)

| **Zone**               | **Record**                                                 | **Type** |
|------------------------|------------------------------------------------------------|----------|
| connect.digitalgov.gov | `1962994g44.secure0082.hubspot.net`                          | A        |
| email.digitalgov.gov   | `167.89.86.190`                                              | A        |
| email.digitalgov.gov   | `10 mx.sendgrid.net`                                         | MX       |
| email.digitalgov.gov   | `v=spf1 ip4:167.89.86.190 -all`                              | TXT      |
| support.digitalgov.gov | `216.128.241.47`,`173.252.148.104`                             | A        |
| support.digitalgov.gov | `10 inbound-smtp.us-east-1.amazonaws.com`                    | MX       |
| support.digitalgov.gov | `v=spf1 include:mail.zendesk.com include:amazonses.com ~all` | TXT      |

From @dawnpm who runs the Search.gov team —  
> _"We send email from `support.digitalgov.gov` using AWS SES. We use it to communicate via ZenDesk with customers. We also have our email address for that domain listed in Hubspot, and I select it from the list of possible senders when I put together a newsletter in Hubspot. How hubspot handles the email domains, I don't know."_

---

## 2. We'd like to make sure we can establish a new sending domain in Hubspot for challenge.gov

As noted above, we have two sending sub-domains
- **Digital.gov** / email.digitalgov.gov
- **Search.gov** / support.digitalgov.gov (this is being verified)

We'd like to add in a sending domain for Challenge.gov. Ideally, they'd like to send from emails from the `Challenge.gov` domain _(e.g. team@challenge.gov)_. If that is not possible, they are happy to go with `email.challenge.gov`_(e.g. team@email.challenge.gov)_

[See the current Challenge.gov DNS records are below](https://github.com/GSA/digitalgov.gov/issues/1513#issuecomment-554518439)

---

## 3. Understand how we'd go about changing our root sending domains from `digitalgov.gov`, to `digital.gov`

This is not needed in the coming weeks, but we'd like to understand how we'd go about making this switch over and what steps are needed to happen without losing services.

---

## 4. Email sending settings in Hubspot

Do we need to remove or update the "Email sending domains (DKIM)" in the Hubspot Admin (`In Settings -> Domains and URLs`)?

![image](https://user-images.githubusercontent.com/395641/68974864-bc72a780-07bf-11ea-9fe5-88ff543e890a.png)

**Comment by twgsa16** [comment]
| Host name               | Zone          | Record Value                                       | Record Type |
|-------------------------|---------------|----------------------------------------------------|-------------|
| bcg3et.1962994m         | challenge.gov | 3.210.190.243                                      | A           |
| 1962994m                | challenge.gov | 0 mx.hubapi.com.                                   | MX          |
| 1962994m                | challenge.gov | v=spf1 include:1962994.spf05.hubspotemail.net -all | TXT         |
| hs1._domainkey.1962994m | challenge.gov | 1962994m-challenge-gov.hs01a.dkim.hubspotemail.net | cname alias |
| hs2._domainkey.1962994m | challenge.gov | 1962994m-challenge-gov.hs01a.dkim.hubspotemail.net | cname alias |

**Comment by jeremyzilar** [comment]
From an email from HubSpot — 

> The DNS records look great and have passed validation. No further action is needed on your end to set up the new dedicated IP. 
> Please leave the old records associated with the email.digitalgov.gov SMTP domain intact. These records are needed to keep the old dedicated IP online for the warm-up period.

> The dedicated IP warm-up will happen automatically behind the scenes! All you have to do is send your normal amount of marketing email consistently over the next 30 days. This warm-up plan is designed to steadily increase the volume of email that is sent by your new dedicated IP address. Traffic will be split between the old IP and the new one.

> **Next steps**
> Continue sending marketing email as usual, and keep in mind those email deliverability best practices! 
> *If you're unable to send email during this warm up period, please let me know so I can adjust the warm up dates to optimize for your projected send dates. 
Since the DNS is all set and the IP is now live, it may not be necessary to have a second phone call today. If you have any further, unresolved questions about the DNS for the dedicated IP, please let me know ahead of 12:30 pm.

> **Git: About Email Sending Domains**
> Email sending domains are a way to setup on DKIM authentication for the domains from which you choose to send mail. These domains should match the domain portion of your From: addresses. For example, if you want to send mail from jeremy.zilar@gsa.gov or jeremy.zilar@challenge.gov, then you need to connect gsa.gov and challenge.gov as email sending domains. You can connect as many email sending domains as needed. For additional support with this step, please reach out to HubSpot Technical Support and check out this guide.

**Comment by twgsa16** [comment]
*Receiving a soft bounce message as follows:*

Soft bounced

Your IT team has not authorized HubSpot to send emails on your behalf

DMARC 550 5.7.1 Unauthenticated email from challenge.gov is not accepted due to domain's DMARC policy. Please contact the administrator of challenge.gov domain if this was a legitimate mail. Please visit https://support.google.com/mail/answer/2451690 to learn about the DMARC initiative. n6si14044671ejk.160 - gsmtp

**Comment by jeremyzilar** [comment]
`01/08/2020` — We are having some issues this morning with our HubSpot account. It looks like emails are getting bounced due to the DMARC Authentication settings.

![image](https://user-images.githubusercontent.com/395641/71995339-6bec5900-3208-11ea-824a-1c67dddf19e1.png)

**Comment by Schultea** [comment]
On January 8th, we had 23,110 soft bounces, 14,569 delivers, of 37,911 sent. https://app.hubspot.com/email/1962994/details/24162412929/recipients/sent

**Comment by jeremyzilar** [comment]
This is the specific error:
```Soft bounced
Your IT team has not authorized HubSpot to send emails on your behalf
DMARC 550 5.7.1 Email rejected per DMARC policy for digitalgov.gov (G15)```

Here is the documentation that Hubspot provides:
- **Set up DMARC with HubSpot** https://knowledge.hubspot.com/email/can-i-use-a-dmarc-policy-with-hubspot#troubleshoot-issues-with-dmarc-authentication

**Comment by jeremyzilar** [comment]
CNAME | `hs2._domainkey.digitalgov.gov` | `digitalgov-gov.hs01b.dkim.hubspotemail.net.`
CNAME | `hs1._domainkey.digitalgov.gov` | `digitalgov-gov.hs01a.dkim.hubspotemail.net.`
TXT | `smtpapi._domainkey.digitalgov.gov` | 
```
k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDPtW5iwpXVPiH5FzJ7Nrl8USzuY9zqqzjE0D1r04xDN6qwziDnmgcFNNfMewVKN2D1O+2J9N14hRprzByFwfQW76yojh54Xu3uSbQ3JP0A7k8o8GutRF8zbFUA8n0ZH2y0cIEjMliXY4W4LwPA7m4q0ObmvSjhd63O9d8z1XkUBwIDAQAB
```

**Comment by jeremyzilar** [comment]
We just merged https://github.com/18F/dns/pull/386, so we'll do a test to see if things are working

**Comment by jeremyzilar** [comment]
In the process of adding a new email sending domain `@digitalgov.gov` in the backend of HubSpot, I got alerted that one of the records that we updated yesterday was invalid. It was off by a character. Fixing that here: https://github.com/18F/dns/pull/388

**Comment by jeremyzilar** [comment]
We are still experiencing a few issues from HubSpot around our DNS set up. Here is an issue that has the errors that we are getting https://github.com/18F/dns/issues/389

**Comment by jeremyzilar** [comment]
**Update:** We are still having sending issues from the `@digitalgov.gov` domain.
Test emails are not coming through from `email@digitalgov.gov`.


In order to be able to get any information back about why emails are not going through, I created a new static list "Digital.gov Testers" that contains 8 contracts (people on our team, some GSA addresses, some gmail addresses.

Then I created a new TEST email and sent it to ONLY the "Digital.gov Testers" list (on 01/08/2020 at 12pm ET)

Here is the performance page for that email: https://app.hubspot.com/email/1962994/details/24544109584/performance

Still waiting to receive the test email.

**Comment by jeremyzilar** [comment]
The **soft bounce** error we received after our **Jan 18 test email**:
```
Soft bounced

Rejected by recipient's email security filter

IP_REPUTATION 550-5.7.1 [3.210.190.243 12] Our system has detected that this message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked. Please visit 550-5.7.1 https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1 for more information. y31si20056409qtd.296 - gsmtp
Ask the recipient to whitelist your sending IP addresses.
```

**Comment by afeld** [comment]
Note that we have [Agari](https://www.agari.com/) available, which may be helpful.

**Comment by jeremyzilar** [comment]
From Hubspot:
```
For SPF, you’ll need to authorize HubSpot to send mail on behalf of sending domains to help meet DMARC alignment requirements. Your SPF records value can be found in the Domain Manager Under Advances options. For ease of use, the full record value is “include:1962994.spf05.hubspotemail.net”
@Jeremy - you’ll want to update this in the public DNS. The current entry mentioned in the Git issue is incorrect. 
```

**Comment by jeremyzilar** [comment]
The DNS side of this appears to be fixed. Now we're on to fixing our sender reputation for our email (which is a whole other issue). Closing this.
