### ISSUE TITLE
"Move Your Way" Case Study photos

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1516]
For: 

Logo, 1200 x 715

![1200-x-715_Move-Your-Way_logo](https://user-images.githubusercontent.com/19961574/69064514-5028bb80-09ec-11ea-9aa2-a6cf0493a4dd.png)

600 x 358 

![600-x-358_Move-Your-Way_logo](https://user-images.githubusercontent.com/19961574/69064594-6b93c680-09ec-11ea-9566-34fa2a8f65aa.png)

**Comment by ToniBonittoGSA** [comment]
Alt text: A screen capture of the bilingual Move Your Way Activity Planner website in English shows the first nine of more than 50 aerobic and strength-training activities that are available in the Planner. The user has options to personalize activity settings, and filter activities by type. On the right, are reminders that users should aim for 150 minutes of moderate-intensity aerobic activity and two days of muscle-strengthening activity each week. Also on the right is a "Review your week" button--which is inactive until a user sets up their plan. 

<img width="1426" alt="Move-Your-Way_Activity-Planner_Aerobics-options" src="https://user-images.githubusercontent.com/19961574/69064757-a990ea80-09ec-11ea-84f9-a354fe08a830.png">

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
