### ISSUE TITLE
Answers to: Building the Elements That Earn Trust

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1517]
<img src="https://user-images.githubusercontent.com/395641/69074112-bf0e1080-09fc-11ea-948d-cb3809e3d2f9.png" width="150px">

**From our blog post on Digital.gov: "Building the Elements That Earn Trust"**
[https://digital.gov/2019/11/18/building-elements-that-earn-trust/](https://digital.gov/2019/11/18/building-elements-that-earn-trust/) 

> **Help us identify a trustworthy experience**
> 
> We’d like to get your help in defining the elements that we all need to have in place to start earning trust, and what actions federal digital teams need to take to get there.

---

### In your words, help us complete these two sentences.
There are no right or wrong answers, and you’re welcome to submit as many times as you’d like.

```
1. To deliver an experience that is trustworthy, we need to _____________.

2. To perform this action, we need _______________.
```

### 👇 **To submit**, enter your answers in the comment box below.

_If you’re having trouble submitting, send your answers to us at [digitalgov@gsa.gov](mailto:digitalgov@gsa.gov)._

**Comment by Johnny939** [comment]
1. Communicate
2. Collaborate and understand software platforms with help of mentors.

**Comment by ToniBonittoGSA** [comment]
1. To deliver an experience that is trustworthy, we need to:
provide a means of verifying that our social media accounts and mobile products are legitimate federal government properties (which can help protect the public from phishing scams and other malicious activities). 

2. To perform this action, we need:
to register -- and maintain -- all of our social media accounts and mobile products on the U.S. Digital Registry ([https://digital.gov/services/u-s-digital-registry/](https://digital.gov/services/u-s-digital-registry/)).

**Comment by djharrity** [comment]
1. To deliver an experience that is trustworthy, we need to provide comprehensive, correct and current content.
2. To perform this action, we need to have plans in place to focus resources on delivering and maintaining quality content, including functionality to request and respond to customer input as a driver for improvements to design and functionality of the customer experience.

**Comment by afomi** [comment]
1. To deliver an experience that is trustworthy, we need to `provide clarity on the process (game being played) (goals, parameters, constraints), convey context (including lifecycle and current state), and communicate affordances (what can i do at what point in time?)`

2. To perform this action, we need `to set expectations` and `be responsive`

**Comment by nicopapafil** [comment]
1. Be transparent
2. Communicate efficiently, effectively, and in plain language

**Comment by thecapacity** [comment]
I liked @ToniBonittoGSA 's template so I copied and changed for my answers below;

1. To deliver an experience that is trustworthy, we need to:
        - provide value to users in a way that is definitive (e.g. be clear it's an estimate when it's an estimate, clear expectations on timeliness, certainty that it's authoritative, etc)
        - meaning we can't leave them feeling uncertain about our answer vs. what they read on another federal site

2. To perform this action, we need:
       - to identify key questions and create government-wide answers for the public and public servants, unconstrained by a single project or agency mission.

**Comment by durland18F** [comment]
To deliver an experience that is trustworthy, we need to:
- establish a cadence for reviewing content and provide proof for the fact that the content is current

To perform this action, we need:
- to establish (or re-establish, or certify) governance for content

**Comment by SarahCraneGSA** [comment]
To deliver an experience that is trustworthy, we need to:

earn referrals and citations from trusted, well-known  sources

To perform this action, we need:

a comprehensive and thoughtful SEO strategy

**Comment by joshuakfarrar** [comment]
1. To deliver an experience that is trustworthy, we need to use inclusive language and protect customer and citizen data from unauthorized access and use.

2. To perform this action, we need a digital citizens' bill of rights, defining how the government asks permission to use our data, and strictly limiting the uses of our data to those uses which are authorized or provide for the welfare of the general public.

**Comment by willcahoe** [comment]
1. To deliver an experience that is trustworthy, we need to emphasize that we understand the user's needs and relay to them that what they want to accomplish is possible and that we will help them accomplish that thing.

2. To perform this action, we need to communicate in an affirming manner, use plain language, and offer hope to our users.

**Comment by edmullen** [comment]
1. To deliver an experience that is trustworthy, we need to be a supportive force for people during the process of applying/maintaining benefits to which they may be/are entitled, helping them unlock support to help them survive.

2. To perform this action, we need stop assuming fraudulent intent of people accessing their benefits and creating hostile impediments to access.

**Comment by dawnpm** [comment]
1. To deliver an experience that is trustworthy, we need to provide plain language help in the form of process design (initiation of the process, status check, closure), clear presentation of the information in the context consumed (website, voice, social media post, etc), and differentiation between the information provided by the government and information available from other sources, and why those differences exist. 

2. To perform this action, we need governance and enforcement of plain language and human centered design, requirements to include but not limited to:
* date last reviewed, in metadata as well as present in the body of the content
* structured content that follows best practices for machine consumption and reuse (SEO methods and beyond)
* evidence in the text that we're aware of the informational landscape and the other sources the person may be consuming - and whether those sources are derived from gov info, separate from but in agreement with gov info, or in conflict with gov info, and why the person should choose to trust the gov over the conflicting source.
* a plain language tone that remains professional, and avoids gimmicks.
* usability testing of process (re)designs prior to development - modularization of contracts to have process design and usability testing completed as a distinct effort prior to a build contract beginning.

**Comment by Karentrebon** [comment]
To deliver an experience that is trustworthy, we need to...deliver services that work as intended. 

To perform this action, we need...to tell people **what** **to** **expect** and hold ourselves to our word. If we can't navigate the "white space" between our agency and another government agency, tell the citizen what they need to do.

**Comment by afomi** [comment]
1. To deliver an experience that is trustworthy, we need to `communicate in plain language` and `consider user experiences that span across multiple agencies and/or jurisdictions`

2. To perform this action, we need `to deliver services that are coherent and cohesive from a citizen's perspective` and `coordinate to deliver public services effectively across agency and jurisdictional silos`

**Comment by afomi** [comment]
1. To deliver an experience that is trustworthy, we need to `deliver services that are comprehensible, streamlined, and accountable.`

2. To perform this action, we need `to design efficient, stateful workflows, reduce duplication in law and policy via modularization, and consider a blockchain to enable auditable, trustworthy citizen identity and logged interactions within and across agencies`

**Comment by cmajel** [comment]
1. To deliver an experience that is trustworthy, we need to `talk to users about what they expect from an agency or service, and hear from them how they decide if they are in the right place (or not).`

2. To perform this action, we need to..
* `talk to people who are having trouble, listen to their stories, and share what we learn with our teams, so that there is shared knowledge of what problems exist`.
* `establish a regular research cadence to talk with users and observe them using our tools and content so that we can see how properties work in action`.
* `provide feedback channels to the public so that they can tell us when something doesn't work as expected`
* `document the problem (or the user story) that we're trying to address first before deciding how to solve it.`

**Comment by ecayer** [comment]
To deliver an experience that is trustworthy, we need to have a strong visual identity that is uniquely ours. To perform this action, we need to prevent others from copying it.

**Comment by ecayer** [comment]
To deliver an experience that is trustworthy, we need people to feel confident that they will get all the way through the task they have come for. To perform this action, we need to structure services around the specific needs of the public and ensure that we are tracking task completion and satisfaction.

**Comment by austinhernandez** [comment]
To deliver an experience that is trustworthy, we need to understand that humans are largely governed by unconscious thought and [automatic cognitive processing)](https://www.nngroup.com/articles/first-impressions-human-automaticity/), so a person's initial reaction to the way a website looks greatly influences their perception of trust and credibility.

To perform this action, we need to design visually appealing interfaces that look easy-to-use, then validate the design with usability testing.

**Comment by austinhernandez** [comment]
To deliver an experience that is trustworthy, [prominence-interpretation theory](https://www.nngroup.com/articles/prominence-interpretation-theory/) suggests that people determine a site’s trustworthiness by judging the most prominent element.

To perform this action, we need to establish visual prominence on an interface, then conduct usability tests to validate that the most prominent element is interpreted as positive.

**Comment by copywritepaste** [comment]
To deliver an experience that is trustworthy, government entities need to be timely on social media and authentic during direct engagements.
To perform this action, the review/approval process must be streamlined and the internal guidelines for tone and voice must be clearly stated and followed but the social media handlers.

**Comment by afeld** [comment]
1. To deliver an experience that is trustworthy, we need to **respond to user needs**.
2. To perform this action, we need **to not treat a launch as being "done"**.

**Comment by jasonflaherty** [comment]
1. To deliver an experience that is trustworthy, we need to deliver and support the product created. 

2. To perform this action, we need to form a transparent working relationship within the agreed upon project scope.

**Comment by michaelhortongsa** [comment]
1. To deliver an experience that is trustworthy, we need to **ensure that _everyone_ can participate**.

2. To perform this action, we need **to integrate accessibility requirements into our workflows and ensure that our information and technology has been verified as accessible _before_ distribution**.

**Comment by javonneg** [comment]
To deliver an experience that is trustworthy, we need to _truly understand our customers, provide positive experiences in our service interactions, and create digital products that effectively meet their needs._  

To perform this action, we need to: 
- actively listen to our customers' needs
- be accountable and give insight on how the customers' feedback improved our products
- provide customer service beyond their expectations
- have transparent communication and high-quality content in plain language
- be engaged and responsive with our audiences
- align with industry standards for user interface (UI) and user experience (UX) design 
- protect data and users through cyber security 
- continue to implement modern technologies and foster innovation in the public sector

**Comment by SMTullis** [comment]
1. To deliver an experience that is trustworthy, we need to be transparent with our public data and be responsive to customers.

2. To perform this action, we need to:

- redesign our websites to increase user friendliness and incorporate search features to make publicly available information easy to find and use;
- provide open source APIs to enhance integration of third party systems into existing federal systems;
- provide world-class customer service by responding to customer inquires quickly and accurately;
- invest funds into system enhancements so we are no longer using 1990's software in a 21st century world.

**Comment by NCC1701C** [comment]
1. To deliver an experience that is trustworthy, we need to _set clear expectations and achieve them_.

2. To perform this action, we need _a culture that values, monitors, and enforces professional competence, commitment to the truth, courage to measure and correct, and cohesion as an organization working to achieve a common goal._

**Comment by mariamarrero** [comment]
1. To deliver an experience that is trustworthy, we need to design information and services that are easy to use, reliable and inclusive.

2. To perform this action, we need to:
    1. Focus on our users and their needs
    2. Provide ways for our users to provide feedback
    3. Design quality products that reflect professionalism
    4. Provide comprehensive, correct and up to date content
    5. Iterate our products based on research and usability test

**Comment by ToniBonittoGSA** [comment]
Submitted by email, from: **Melanie McLean, DVM** | FDA’s Center for Veterinary Medicine

> 1. To deliver an experience that is trustworthy, we need to clearly and concisely communicate to the public.
> 2. To perform this action, we need to write in a way regular people understand and not hide behind jargon and governmentese.

**Comment by mpeterz** [comment]
1. To deliver an experience that is trustworthy, we need to provide the services and information people need in a way that's useful and usable.

2. To perform this action, we need to do research with real users and test our designs, our content, and our technology to make sure they work for the people we serve.
