### ISSUE TITLE
CoE Apprenticeship photos

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1520]
![USDA_Family](https://user-images.githubusercontent.com/19961574/69179844-3665a200-0ada-11ea-91c1-ff413ac7bbde.jpg)
Alt text: Eight smiling people, USDA Apprentices and a GSA employee, standing together in a group. 

---

![20190718_142112_002](https://user-images.githubusercontent.com/19961574/69179659-dec73680-0ad9-11ea-9381-6be079fad448.jpg)
Alt text: An intimate working session in a conference room where two USDA Apprentices (seated center, and right) are collaborating on a project with a GSA employee (seated on the left). 

---

![100819_IT_Modernization_Showcase_57-1](https://user-images.githubusercontent.com/19961574/69172676-4a0a0c00-0acc-11ea-94f5-19b05630f4c1.jpg)
Alt text: 
Leaders from the Centers of Excellence and USDA come together for a photo at the 2019 IT Modernization Showcase at GSA. These are the people who are the leadership stewards of operational innovation. From left to right, the four are: USDA’s CIO Chief of Staff Tonya L. Judkins; GSA’s Deputy Director, Centers of Excellence, Brian Whittaker; USDA’s CIO, Gary Washington; and USDA’s Deputy Chief Financial Officer, Lynn Moaney. 

---

![Mod_squad](https://user-images.githubusercontent.com/19961574/69179654-de2ea000-0ad9-11ea-8e8c-b5445b1ee73e.jpeg)
Alt text: Six USDA Apprentices walk through the GSA atrium.

---

![Farmersround](https://user-images.githubusercontent.com/19961574/69179656-dec73680-0ad9-11ea-95f8-48095c7169b2.jpg)
Alt text: Photo of a large group of diverse USDA stakeholders and customers are seated around many small, connected tables that form a rectangle in a conference room. At the far end of the room, a large, ceiling-mounted screen displays a presentation. The meeting, run by a GSA employee and USDA Apprentices, represents an opportunity to collapse boundaries between different stakeholders to foster diverse relationships. 

---

![20190605_121230](https://user-images.githubusercontent.com/19961574/69179653-de2ea000-0ad9-11ea-8f57-75c1c1385d4e.jpg)
Alt text: A photo of a USDA Apprentice leading a human-centered design workshop. Three people are working at a table on an activity, and one person is standing in front of a customer journey map and a tall, dark board with colorful sticky notes of ideas from a brainstorming session.
 ** also use as featured image 

---

![20190911_120652](https://user-images.githubusercontent.com/19961574/69179658-dec73680-0ad9-11ea-97e5-bab24a5b1de1.jpg)
Alt text: An intimate working session in an office where one USDA Apprentice is collaborating on a project with three GSA employees.

**Comment by jeremyzilar** [comment]
These have all been added to https://github.com/GSA/digitalgov.gov/pull/1519
