### ISSUE TITLE
Github Desktop & Hugo

### ISSUE THREAD

**Issue by Johnny939** [GSA/digitalgov.gov#1522]
Does anyone have or can make instructions on how to use Hugo to make edits on a forked digitalgov to then summit to master for reviews.

Would it be possible to use NotePad++ or some other editor vs not having to use Hugo?
Note: Using Github desktop on a personal computer. I can't use none of these platforms on my work computer. 

Thanks for the info!

**Comment by jeremyzilar** [comment]
Hey @Johnny939 — the people on our team that edit and work on Digital.gov locally on our computers use ATOM https://atom.io/ to edit the project files.

To run the site, you do need to run HUGO. That is the static site generator that builds the HTML pages, and there are some instructions for getting that installed locally in our readme https://github.com/GSA/digitalgov.gov/blob/master/readme.md Let us know how we can make those better.

I would like to put the site in Docker, which is much much easier to load up locally. That is something I'll try doing in the coming week, now that I know there is more need for it.
