### ISSUE TITLE
As an editor, I would like an automated way of getting the Federalist preview link in a GitHub Pull Request

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1529]
As an editor, I would like an automated way of getting the Federalist preview link in a GitHub Pull Request.

I would like to explore doing this through Circle CI.

**On each new pull request, CircleCi would:**
1. Get the branch name for the PR
2. comment back to the PR with a pre-formatted Federalist Preview URL

**Comment by jeremyzilar** [comment]
Related: https://github.com/18F/federalist/issues/2350

**Comment by saracope** [comment]
A github action was added for this.
