### ISSUE TITLE
New Blog Post: 10X Federal Grant Reporting

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1553]
This is a new blog post on the 10X Federal Grant Reporting project

User story for the project:
> Grant management team members from federal agencies (program analysts, managers etc.) need a quick and simple way to get all the relevant single audit data into their agency’s audit resolution workflow so they can quickly communicate with grantees if necessary to resolve audit findings within the required time period.

**Expected publish date:** 
Early December

**Google Docs URL:** 
https://docs.google.com/document/d/1wGYzONIgFpr0mTpNeijTc1I8TyIMRJFV76wNyhEfwjA/edit

➕ @bpdesigns

**Comment by jeremyzilar** [comment]
@bpdesigns Do you have screenshots that you can provide? Drop them here in the issue

**Comment by bpdesigns** [comment]
hi @jeremyzilar, @ToniBonittoGSA. I must have missed this last week. Here is a gif and a few screenshots in order of relevance. Thanks  

### Comments added to a finding review
[Gif](https://user-images.githubusercontent.com/3209501/60308048-f835cf00-98fb-11e9-8431-dc7488d3898b.gif) of comments being added to a review of findings. 

### Findings overview
![SAFR Overview](https://user-images.githubusercontent.com/15329140/70076808-945fb280-15cd-11ea-9e0b-aa0f70923490.png)

### Finding dashboard 
![SAFR Findings Dashboard](https://user-images.githubusercontent.com/15329140/70076795-8c077780-15cd-11ea-931d-206eedcfd7c4.png)

### Subscribe to notifications
![SAFR Findings Notifications](https://user-images.githubusercontent.com/15329140/70076811-96c20c80-15cd-11ea-9541-978f2eb13006.png)
