### ISSUE TITLE
Bug: legacy image shortcode

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1558]
**Describe the bug**
https://digital.gov/2011/11/28/battle-royale-mobile-web-versus-mobile-apps/ 

the `legacy-img` shortcode is not working for this image, or maybe this image is not on the server.

This is the code that references the image, and it should be at the top of the blog post

```
{{< legacy-img-right src="2011/11/250-x-167-Stuart-Barr_Fighting-Topis_Nov17th2008_Creative-Commons-BY-NC-SA-2.jpg" alt="A photo of two fighting Topis (antelopes) head-butt each other, locking horns, in a grassy field." caption="Photo by Stuart Barr, Creative Commons BY-NC-SA 2.0" >}} 
```

Here are the images and captions
https://github.com/GSA/digitalgov.gov/pull/1556

**Comment by ToniBonittoGSA** [comment]
It exists 

https://s3.amazonaws.com/digitalgov/_legacy-img/2011/11/250-x-167-Stuart-Barr_Fighting-Topis_Nov17th2008_Creative-Commons-BY-NC-SA-2.jpg

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
