### ISSUE TITLE
images for 12/3 blog post

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1590]
for https://github.com/GSA/digitalgov.gov/pull/1562 

alt text: Move Your Way logo

![1200-x-715_Move-Your-Way_logo](https://user-images.githubusercontent.com/19961574/70080043-dc81d380-15d3-11ea-9bf4-55c8a133004b.png)

---
Alt text: A screen capture of the bilingual Move Your Way Activity Planner website is shown in English. It displays the first nine of more than 50 aerobic and strength-training activities that are available in the Planner. The user has options to personalize activity settings and filter activities by type. On the right, are reminders that users should aim for 150 minutes of moderate-intensity aerobic activity and two days of muscle-strengthening activity each week. Also on the right is a "Review your week" button--which is inactive until a user sets up their plan.

![MYW activity planner](https://user-images.githubusercontent.com/19961574/70080790-3b941800-15d5-11ea-9e8b-ec3b55c60bcd.PNG)

---
alt text: An early wireframe of the Activity Planner shows a layout of where the different elements and filters appear on the page. 

<img width="600" alt="MYW wireframe 1" src="https://user-images.githubusercontent.com/19961574/70086993-756b1b80-15e1-11ea-924d-f24fb4ec6b32.png">

---

**Comment by ToniBonittoGSA** [comment]
alt text: A screen capture of the Yardwork activity shows that it counts as aerobic activity and strength-training. 

<img width="536" alt="MYW Yardwork" src="https://user-images.githubusercontent.com/19961574/70091750-cf241380-15ea-11ea-9395-fe68caa8bbfc.PNG">

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
