### ISSUE TITLE
Create image to add as a branding watermark to YouTube videos

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#162]
We have the ability to add a branding watermark to our YouTube videos. I'd like to explore how this would look and see if it is something we want to add.

@thisisdano - I added you to this since I'm assuming this is something you might design. I'm going to explore how this would work and what it would look like.

**Comment by jeremyzilar** [comment]
Maybe we want to look into doing this after we change our logo? @thisisdano
