### ISSUE TITLE
Update Contribute form on New site (demo)

### ISSUE THREAD

**Issue by saracope** [GSA/digitalgov.gov#1638]
**Describe the bug**
The form on https://demo.digital.gov/about/contribute/ has a few formatting issues.

**Steps to Reproduce**
1. Go to https://demo.digital.gov/about/contribute/
3. Scroll down to the heading `Please fill out our form to get started`
4. See that the `How would you like to contribute?*` section has bullets and checkboxes
1. See that the Captcha is overlapping the Submit button
1. The form could use some additional spacing between elements

**Screenshots**
<img width="670" alt="Screen Shot 2019-12-13 at 7 44 46 AM" src="https://user-images.githubusercontent.com/2197515/70801448-eb5b4980-1d7c-11ea-822f-ae6de9c3ca6a.png">

Tested on Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by jeremyzilar** [comment]
Still an issue. Will fix
