### ISSUE TITLE
Update YouTube channel metadata

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#164]
Currently our channel keywords say - DigitalGov GSA "social media" "gov 2.0" "Web Manager University" "Federal Web Managers Council" "federal government" "government customer service"

These should be updated.

@jeremyzilar & @AndreaSigz - suggestions?

- [x] Update Keywords
- [x] Update Page Description
- [x] Update google profile

**Comment by AndreaSigz** [comment]
Can you find out what people are searching on in the channel? If not, you can look at our search list

**Comment by jthalls** [comment]
good idea @AndreaSigz! I will see what I can find but I'm guessing the DG search list might be better.

**Comment by jthalls** [comment]
@AndreaSigz here's what I was able to pull regarding search terms in YT: https://docs.google.com/spreadsheets/d/1txykdUQyxCPFEi8mp98x2LO1cJG4lF9fhREUNSSJtwA/edit#gid=0

Only 9.8% of our total mins watched was from the YouTube search in the last 30 days (last 6 months it was 7.4%). It doesn't drill down to the search on our specific channel, but the top keywords (past 30 days) people searched for in YouTube that brought them to our videos are:


- fedramp
- fisma
- security assessment and authorization process
- social media policy yammer
- api open data download

Top YT search terms in last 6 months:

- fedramp 
- fisma
- fedramp security assessment framework
- fedramp explained
- dap 2.0 training

**Comment by jthalls** [comment]
@AndreaSigz @jeremyzilar -

Given that the top search terms in YouTube that lead folks to our videos are consistency about FedRAMP, wondering if we should work with the FedRAMP team on producing a short video (or series of videos) on FedRAMP topics.

**Comment by jthalls** [comment]
@jeremyzilar please review this document and add your comments: https://docs.google.com/document/d/1eIJoVEnTAnxbb-RvQHiNlykSwhT98sHZkHVZVAM-2qg/edit

I'll update the keywords and description once you add your edits.

**Comment by jeremyzilar** [comment]
Did you update this @jthalls ? If so, this can be closed.

**Comment by jthalls** [comment]
@jeremyzilar yes, closing now.
