### ISSUE TITLE
Bug: mild spacing issues on contribute page

### ISSUE THREAD

**Issue by gbinal** [GSA/digitalgov.gov#1640]
On the [contribute page](https://demo.digital.gov/about/contribute/), there appears to be some missing spacing for me around the form.  Specifically around the checkboxes and around the submit button at the bottom.  

I'm on Chrome on macOS.  

<img width="697" alt="Screen Shot 2019-12-13 at 11 08 39 AM" src="https://user-images.githubusercontent.com/633088/70814269-223f5880-1d99-11ea-8b72-e11664bdb935.png">

**Comment by jeremyzilar** [comment]
Duplicate to https://github.com/GSA/digitalgov.gov/issues/1638. Closing
