### ISSUE TITLE
social links

### ISSUE THREAD

**Issue by DanielJPino-ux** [GSA/digitalgov.gov#1643]
## Issue
Links for social media do not seem to be working

**Title** — **U&#46;S&#46; Web Design System&#58; November Monthly Call**
**Demo URL** — https://demo.digital.gov//event/2019/11/21/us-web-design-system-november-monthly-call/
**Live URL** — https://digital.gov//event/2019/11/21/us-web-design-system-november-monthly-call/

---

**Please describe the issue clearly. Include a screenshot if needed**

**Comment by saracope** [comment]
This was fixed (and tested). Closing out.
