### ISSUE TITLE
Email for USWDS Pages

### ISSUE THREAD

**Issue by DanielJPino-ux** [GSA/digitalgov.gov#1644]
## Issue
Email should go to: uswds@gsa.gov

**Title** — **U&#46;S&#46; Web Design System&#58; November Monthly Call**
**Demo URL** — https://demo.digital.gov//event/2019/11/21/us-web-design-system-november-monthly-call/
**Live URL** — https://digital.gov//event/2019/11/21/us-web-design-system-november-monthly-call/

---

**Please describe the issue clearly. Include a screenshot if needed**

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
