### ISSUE TITLE
Search Page is using old DG branding

### ISSUE THREAD

**Issue by Adriennelg** [GSA/digitalgov.gov#1656]
https://find.digitalgov.gov/search?utf8=%E2%9C%93&affiliate=digitalgov&query=&commit=

### Search Page is using old DG branding in header/footer, I searched from the Events page.

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by jeremyzilar** [comment]
This is all set! https://find.digitalgov.gov/search?utf8=%E2%9C%93&affiliate=digitalgov&query=agile&commit=
