### ISSUE TITLE
Merge the Lost and Found page with Resources

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#167]
The **Lost and Found – Mapping Page** is one of our most visited pages on the site

We should merge the content on this page with the main Resources page
https://www.digitalgov.gov/about/lost-and-found-mapping-page/

Then redirect the old URL to the main resources page.

**Comment by jeremyzilar** [comment]
**Q.** — Is there a need or an opportunity here to figure out where this traffic is coming from? I have a suspicion that it is from intranets.

We can also put a `note` at the top of the page, asking people "why" they are coming to this page and what they are looking for.

**Comment by AndreaSigz** [comment]
- [ ] Combine items from each page

- [ ] Add items from other sites: PL.gov, 508.gov, usability.gov, USWDS, etc.

- [ ] Research new labels

- [ ] Add tag line for each label
