### ISSUE TITLE
OPP instead of TTS Solutions on "Contribute" page

### ISSUE THREAD

**Issue by Adriennelg** [GSA/digitalgov.gov#1673]
### It reads: "Digital.gov is part of the Innovation Portfolio of the Office of Products and Programs" 

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by saracope** [comment]
I think we can remove this section of the page since the footer now has similar text: 

> Digital.gov is a product of GSA’s Technology Transformation Services, and managed by the Office of Solutions.

Any objections to that?
@jeremyzilar @ToniBonittoGSA

**Comment by jeremyzilar** [comment]
That sounds like the right edit 👍.
