### ISSUE TITLE
Card-quote is missing bg color, spacing, different font

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1686]
The background color, spacing, and font is missing/different for card-quotes in _This Week's IDEA_ posts (and maybe others?)

Original: http://web.archive.org/web/20191213182707/https://digital.gov/2019/12/11/an-introduction-accessibility/ 

New: https://digital.gov/2019/12/11/an-introduction-accessibility/

**Comment by saracope** [comment]
Looks like this was fixed with a PR. Closing out.
