### ISSUE TITLE
Anchor: double line on 2 links

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1688]
when we hover, a double line appears on the DG email and GSA about page links: 

<img width="394" alt="anchor double line DG email link" src="https://user-images.githubusercontent.com/19961574/70838312-a1528200-1dd5-11ea-8298-428522305153.png">

<img width="394" alt="anchor double line GSA about link" src="https://user-images.githubusercontent.com/19961574/70838313-a1eb1880-1dd5-11ea-9bad-4b1f727e8b5f.png">

--- 

the others in the bulleted list look ok 

<img width="394" alt="anchor OIG underline ok" src="https://user-images.githubusercontent.com/19961574/70838329-b202f800-1dd5-11ea-807d-6341053a340f.png">

**Comment by saracope** [comment]
Still an issue.
