### ISSUE TITLE
Manage Subscription pg: empty column on left

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1689]
Original: http://web.archive.org/web/20190115142855/https://digital.gov/communities/manage-your-subscription/  

New: https://digital.gov/communities/manage-your-subscription/ 

It's not set as a guide, so not sure why the column.. 
Also, page weight is 0 -- isn't that hidden? (shouldn't be hidden)

I saw a link to this page at the bottom of the left column here https://digital.gov/resources/intro-accessibility/ (that column is also a bug)

**Comment by saracope** [comment]
Looks like this was fixed by PR. Closing out.
