### ISSUE TITLE
Update copy, and # of members and # of CoP

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1691]
Orig: http://web.archive.org/web/20191213192428/https://digital.gov/communities/ 

Deck: 
> Come together, learn from others in government

Copy: 
> Our communities are where people in government come together to learn, share and collaborate to build solutions to common problems and challenges.
> 
> There are more than 10,000 people participating across government in 22 areas. Our members share resources, work on solutions together and serve as a catalyst for change in government.

New: https://digital.gov/communities/ (no edit link) 

Deck: 
> Come together, learn from others in government

Copy: 
> Our communities are where people in government come together to learn, share and collaborate to build solutions to common problems and challenges.
> 
> There are more than **XX,XXX** people participating across government in **XX** areas. Our members share resources, work on solutions together and serve as a catalyst for change in government.

**_Note_**: there will be 24 CoP once VR/AR is back in, and RS said today's total # of members is 15,649

**Comment by saracope** [comment]
No longer an issue.
