### ISSUE TITLE
New Blog Post: 12/17, UX Documentation

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1699]
**What is this post about? 1-2 sentence summary:**
If you want to make worthwhile investments in the way you interact with customers, think UX. Here are some ways to communicate user experience to key stakeholders and gain support for UX improvement projects. 

**Expected publish date:**
12/17

**Topics**: Design, UX, Stakeholder Engagement

**Google Docs URL:**
(or drag/drop a word doc here)

**Images**
(drag/drop any images you'd like added to this blog post, or attach them in the comments below)

# UX Documentation: Convince Them the Problem Is Real

_If you want to make worthwhile investments in the way you interact with customers, think UX._

Want to improve the way your organization interacts with customers? Start with your website. With so much business being done online, your website is often the first—and sometimes only—way that customers interact with your agency or brand. You want their experience (no matter how long or how often they visit) to be a positive one. 

A good user experience (UX) lets your customers easily search, find, and use the information on your site. Bad UX...doesn’t. Bad UX on one area of your site can impact the way a user feels about the entire experience, so, it’s imperative to make sure your users can navigate your site and complete the tasks they came for.

You might have an idea what UX changes are needed (cough, CONTENT, cough), but there can be a big gap between knowing and fixing. Large-scale UX improvements take time, money, and people power, and you’re just one person! What about everyone else who needs to get on board before you can take action?

## Build Stakeholder Buy-In

Your stakeholders—usually some combination of clients, content managers, developers, executives, product owners, and users—may take some convincing. To build buy-in, you’ll need to communicate UX issues clearly to a variety of people that care about very different lines of business. 

[Get to know them](https://digital.gov/2016/07/01/build-empathy-with-stakeholder-interviews-part-1-preparation/). Are they focused on the bottom line? Customer service metrics? Time commitments required for a UX upgrade? Determine what aspects of a UX project are most important to each stakeholder and deliver your message accordingly. 

## Document Your Users' Experience

It can be tough to get your organization to prioritize UX, but the right documentation can help make the case for improved user experience and better content. Qualitative data from user research—especially hard-to-contest proof like verbatim comments or videos showing your users struggling to use elements of your site—can help convey UX issues to stakeholders who aren’t as close to the action.

There are lots of UX documents out there—your goal is to choose the ones that help you tell your user’s story, address pain points, and get the team on board with your UX improvement recommendations. It helps if your documentation establishes a clear business case (costs avoided, money saved, potential increases in revenue) for those improvements, but don’t speculate if you don’t have the numbers to back it up.

**[Personas](https://digital.gov/2015/01/09/personas-101/)** are normally represented visually as a cluster of mocked-up “user” profiles that can help teams understand user needs, behaviors, and use context. You may have seen personas that use funny photos or unnecessary details—don’t do this. It distracts and detracts from the purpose of a persona: to act as a stand-in for a real user and help the team design toward real user needs. Personas should be created early in the project so your team can better target your designs and content. 

**Good for**: framing design and content around users and their needs

**[Journey maps](https://blog.usa.gov/journey-mapping-our-customer-experience)** depict a user’s experience completing a task over time and across channels. They can diagnose UX issues and confusion points in existing products by mapping out the channels visited and time spent on tasks, which helps teams understand and improve the user journey from beginning to end. Journey maps can help convince business-minded stakeholders of the need for UX intervention. 

**Good for**: understanding the pain points a user faces on an omnichannel journey

**[Prototypes](https://www.usability.gov/how-to-and-tools/methods/prototyping.html)** show how a user interface might function in a proposed design and can be tested with users, developers, and clients at all levels. A prototype should be two-dimensional representation of your final project, but you determine what level of detail to include. Prototypes can be time-consuming to make and are best used in conjunction with more detailed UX documentation. 

**Good for**: seeing how users interact with proposed design; comparing proposed interfaces when you’re testing more than one

**[Wireframes](https://www.usability.gov/how-to-and-tools/methods/wireframing.html)** show structure (minus all the design details you might see in a prototype), giving users a feel for the function of a design. Wireframes can help explain how navigation will work and where content will go. Use real content whenever possible to ensure your designs will work with the actual text and images on your site. Wireframes can be abstract, so be ready to walk your stakeholders through anything that needs additional context. 

**Good for**: explaining function quickly and cheaply—can be as simple as a napkin sketch

Even if you aren’t trying to sell stakeholders on major improvements, documenting UX can help you improve the usability of your content right now: 

- Create a few [personas representative of your users](https://digital.gov/2017/06/20/improving-customer-experience-with-digital-personas/) and rewrite one of your pages based on their needs. Does it change the way you lay out and explain information? 
- Have you [user tested](https://digital.gov/2017/09/28/finding-usability-testers-tips-from-an-army-recruiter/) your content? Gather your feedback from those tests and create a visual presentation that tells the user’s story and the issues they faced. 
- If you’re considering changing your app’s interface, test it first with a few colleagues using a [paper prototype](https://digital.gov/2014/05/22/how-to-make-a-mobile-paper-prototype/). You may learn about usability issues before investing in a full technical redesign.

## Recommended Reading

From the vault! This great DigitalGov post that explains (and visualizes!) [the difference between UX and CX](https://digital.gov/2014/07/07/user-experience-ux-vs-customer-experience-cx-whats-the-dif/).

**Comment by ToniBonittoGSA** [comment]
alt text: An open sketchbook shows wireframes and handwritten notes.
caption: WireStock, iStock, Getty Images Plus

![Wireframes-handwritten-notes-in-sketchbook_WireStock_iStock_Getty-Images-Plus-1153683057](https://user-images.githubusercontent.com/19961574/71028850-17a7fa80-20dc-11ea-9542-d7e7fbeca15c.jpg)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
