### ISSUE TITLE
Create a Service Design Resource page

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1701]
We'd like to create a Service Design resource page and topic on Digital.gov.
https://digital.gov/resources/

**For the MVP** _(minimum-viable page)_ it should be a page that has a clear, short description of service design is, and when it is used. I should be able to send the link to someone when they want to know more about service design.

---

**User Stories**

> "As a reader who is new to service design, I need a clear, short description of service design is, and when it is used."

> "As a reader, I need a checklist or to-do list to help me get started doing a service design workflow."

---

**Comment by saracope** [comment]
Could one of the guilds pick this up? @jeremyzilar

**Comment by NorahMaki** [comment]
@jeremyzilar what's the status of this? anything we can do to help get it over the line?
