### ISSUE TITLE
H2 id code for in-page anchor links

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1716]
using a relative path for URLs with an anchor link wasn't working (https://github.com/GSA/digitalgov.gov/pull/1715)

JZ said: 

> We should make it so that there is a little link icon next to each H2 so that it is easier to get that ID for an H2

**Comment by ToniBonittoGSA** [comment]
other H2 IDs are in http://web.archive.org/web/20190712151323/https://digital.gov/communities/manage-your-subscription/ (view page source to see)

**Comment by jeremyzilar** [comment]
See: https://www.bryanbraun.com/anchorjs/
and https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/8
