### ISSUE TITLE
Desktop: only some elements hit right edge of column

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1724]
### Description

Example: https://digital.gov/2019/12/11/an-introduction-accessibility/ 
(may be related to https://github.com/GSA/digitalgov.gov/issues/1725)

Images and other elements do hit the right side, but the copy does not. Two screen caps: 

<img width="1440" alt="Screen Shot 2019-12-18 at 11 25 26 AM" src="https://user-images.githubusercontent.com/19961574/71104102-45974880-2189-11ea-8d22-b19122c5b54b.png">

and 

<img width="1440" alt="Screen Shot 2019-12-18 at 11 25 42 AM" src="https://user-images.githubusercontent.com/19961574/71104101-45974880-2189-11ea-8366-39b2702a20af.png">

**Comment by saracope** [comment]
Still an issue. Added some help wanted labels.
