### ISSUE TITLE
Bug: width of highlighted box or policy box

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1725]
The width of the Policy boxes and text used to be full-width, like the _suggested text_ box above it

<img width="1440" alt="Screen Shot 2019-12-18 at 11 30 49 AM" src="https://user-images.githubusercontent.com/19961574/71104568-01f10e80-218a-11ea-9a16-c60edf5506b2.png">

may be related to https://github.com/GSA/digitalgov.gov/issues/1724

**Comment by saracope** [comment]
Still an issue. Adding help wanted labels.

**Comment by saracope** [comment]
This is viewable on https://digital.gov/resources/required-web-content-and-links.
Card policy shortcode: https://github.com/GSA/digitalgov.gov/blob/main/themes/digital.gov/layouts/shortcodes/card-policy.html
Card policy styles: https://github.com/GSA/digitalgov.gov/blob/ae1994352b11cc750e7f16d6cb1bbfbf7b133e8e/themes/digital.gov/src/scss/new/shortcodes/_card-policy.scss

**Comment by timscodebase** [comment]
I am looking into this issue.

**Comment by doamatto** [comment]
Since #3368 was merged, this issue can be closed

**Comment by brunerae** [comment]
@ToniBonittoGSA it looks like this issue can be closed! Thank you!
