### ISSUE TITLE
Bug: bg, formatting of form boxes

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1726]
**Describe the bug**
There was a tan colored background for the forms on 

https://digital.gov/about/contribute/ 
https://digital.gov/about/subscribe/ 

originals -- 
http://web.archive.org/web/20191213183021/https://digital.gov/about/contribute/ 
http://web.archive.org/web/20191213183021/https://digital.gov/about/subscribe/ 
(form isn't showing but the box is)

**Comment by jeremyzilar** [comment]
Duplicate to https://github.com/GSA/digitalgov.gov/issues/1638. Closing
