### ISSUE TITLE
Update the DGU About page

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#174]
https://demo.digitalgov.gov/digitalgov-university/

**Comment by jeremyzilar** [comment]
@Schultea can you double check this? https://demo.digital.gov/digitalgov-university/

**Comment by jeremyzilar** [comment]
Need to fix the email address on the page

**Comment by Schultea** [comment]
Created a pull request.

**Comment by saracope** [comment]
Can this be closed now?

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
https://digital.gov/digitalgov-university/
