### ISSUE TITLE
Establish a monthly call or meeting series calendar and post it publicly

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1758]
Establish a monthly call or meeting series calendar and post it publicly.
This can simply be a list of dates/times for the next 6 months out.

**It needs to be clear:**
- we are having meetings and conversations on a regular basis
- it is easy for people to ask questions or request topics

Agendas for each don't need to be posted right away.

**Comment by saracope** [comment]
@jeremyzilar Does the USWDS monthly call satisfy this need?
