### ISSUE TITLE
Bigger Alert for DEMO Site

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#177]
When you land on the DEMO site, I would like to make it more clear that you have arrived on the DEMO (beta) version of the site.

I worry about the URLs getting out there, being shared, etc...

**Comment by thisisdano** [comment]
This would be in addition to the yellow banner? Do we have a sense that this banner isn't doing its job?

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
