### ISSUE TITLE
Capitalization [Content Cleanup]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1778]
https://digital.gov/services/mobile-application-testing-program/

This line seems to have too many capital letters. 
You Tell Us Your Top Tasks for your mobile website –

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by evelyntorres1** [comment]
corrected line 43, extra capitalization. closing issue.
