### ISSUE TITLE
location of side bar "In this page"

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1807]
on this page the side bar, "In this page" and everything under, is on the right side of the page rather than on the left like all the other pages on digital.gov.  

**Title** — **Mobile User Experience Guidelines**
**Demo URL** — https://demo.digital.gov//resources/mobile-user-experience-guidelines/
**Live URL** — https://digital.gov//resources/mobile-user-experience-guidelines/

---

**Please describe the issue clearly. Include a screenshot if needed**

**Comment by saracope** [comment]
For this page, the sidebar is on the right side which is appropriate for Resource pages. The Guides and News pages use a left sidebar while the Events and Resources pages use a right sidebar. Not sure of the history of those decisions, but I wouldn't say this is a template bug.
