### ISSUE TITLE
Bold font - unnecessary?

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1811]
Not sure the words Product and product need to be bold in the sentence: Product management is different from project management., from the second paragraph.

**Title** — **Government Product Managers Play a Key Role in UX**
**Demo URL** — https://demo.digital.gov//2015/11/27/government-product-managers-play-a-key-role-in-ux/
**Live URL** — https://digital.gov//2015/11/27/government-product-managers-play-a-key-role-in-ux/

---

**Please describe the issue clearly. Include a screenshot if needed**

**Comment by doamatto** [comment]
I agree that this seems like an odd use of bold. I've made a PR bringing the weight back to normal.

See #4247
