### ISSUE TITLE
Bold font - unnecessary?

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1812]
Several words, physical, everyone, everything, very, and them are bold and i'm not sure that they need to be unless they are supposed to be links to other web pages??

**Title** — **Best Practices for Remote User Experience Research**
**Demo URL** — https://demo.digital.gov//2015/12/10/remote-user-experience-information-gathering-best-practices/
**Live URL** — https://digital.gov//2015/12/10/remote-user-experience-information-gathering-best-practices/

---

**Please describe the issue clearly. Include a screenshot if needed**

**Comment by doamatto** [comment]
I agree that some of these words don't need emphasis and sound weird when spoken out loud with it. I've changed some of the words to a normal weight, but left some with emphesis as I think they still should have it.

See #4248
