### ISSUE TITLE
Image links and bold font Gaming Apps

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1813]
All 5 image links are broken and the paragraph after the 5th image is all in bold font (I dont think that it is supposed to be).

**Title** — **Designing User-Friendly, Educational and Engaging Mobile Gaming Apps**
**Demo URL** — https://demo.digital.gov//2016/02/19/designing-user-friendly-educational-and-engaging-mobile-gaming-apps/
**Live URL** — https://digital.gov//2016/02/19/designing-user-friendly-educational-and-engaging-mobile-gaming-apps/

---

**Comment by doamatto** [comment]
I've fixed the issue with the header and its paragraph not being split properly in #4249. However, I'm not sure how I would go about fixing the images. On my computer, they return a 403, so resolving that would require someone with access to the S3 bucket to fix those requests.

**Comment by Calohash** [comment]
Ok I'm thankful I'm learning not Shure if I'm doing this right
