### ISSUE TITLE
[Suggestion] - PRA

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1829]
### URL / Link to page
https://pra.digital.gov/additional-resources/

### Tell us how we can make this page better
The headings on this page are all Title Capped. The other pages have The first word capped only.

**Comment by saracope** [comment]
Issue moved to [GSA/digitalgov-pra #279](https://github.com/GSA/digitalgov-pra/issues/279) via [**ZenHub**](https://www.zenhub.com/)
