### ISSUE TITLE
Email address update

### ISSUE THREAD

**Issue by DanielJPino-ux** [GSA/digitalgov.gov#1832]
Please update the email address on the USWDS Community Page to uswds@support.digitalgov.gov as we are cutting over to a new email address. Thank you!

## Issue

**Title** — **U.S. Web Design System**
**Demo URL** — https://demo.digital.gov//communities/uswds/
**Live URL** — https://digital.gov//communities/uswds/

---

**Please describe the issue clearly. Include a screenshot if needed**

**Comment by saracope** [comment]
This was updated. Thanks!
