### ISSUE TITLE
[Suggestion] - Contribute page

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1833]
### URL / Link to page
https://digital.gov/about/contribute/

### Tell us how we can make this page better
Under the Heading: Collaboration there are 3 bullet points. It may be redundant but a link for the second bullet point that links the user to an email or submission page would be nice.

**Comment by jeremyzilar** [comment]
Related to https://github.com/GSA/digitalgov.gov/issues/1638

**Comment by saracope** [comment]
Since this page is the submission page for content, it would be redundant to link to itself.
