### ISSUE TITLE
[Suggestion] - Contribute page

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1834]
### URL / Link to page
https://digital.gov/about/contribute/

### Tell us how we can make this page better
The paragraph under the Collaboration heading has two redundant sentences. I suggest cleaning up the paragraph. 
People are interested in participating in spaces where they can more seamlessly communicate and share ideas between teams, with ‘points of contacts’ designated on various topics. They are interested in participating in spaces where people can more seamlessly communicate and share ideas between teams, with ‘points of contacts’ designated on various topics.

**Comment by jeremyzilar** [comment]
Related to https://github.com/GSA/digitalgov.gov/issues/1638 and https://github.com/GSA/digitalgov.gov/issues/1833
