### ISSUE TITLE
Bug: Email Link broken

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1839]
**Describe the bug**
The link to email on the top left opens an email with a blank To: field and the Subject needs a rework. 
**Steps to Reproduce**
1. Go to: https://digital.gov/2019/12/03/healthgovs-move-your-way-activity-planner-a-case-study/
2. Click on 'Email'
3. See error

**Screenshots**

**Comment by jeremyzilar** [comment]
This is helpful, thank you @onelisadunc-dev
