### ISSUE TITLE
Add Release Notes page to site

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#186]
Let's have a page that tells what we've done to the site, and perhaps tees up future work

**Comment by thisisdano** [comment]
So I'd imagine this is very much a timeline style page:

- - -

`date`
`perhaps something about our next sprint of work`

- - -

`date`
`some things that we did`
`links to github issues`
`maybe some comments`

- - -

`...`

**Comment by thisisdano** [comment]
Is there any reason not to do this exclusively in Github right now? 
What might we want to communicate that we can't communicate in Github?
If we _do_ do this in Github, how do we link to GH from our site?

**Comment by jeremyzilar** [comment]
I think we are doing this in GitHub just fine at the moment https://github.com/GSA/digitalgov.gov/releases

I wonder if there is a place where we can link to the release notes from the page or footer, so we can make it more "official"

**Comment by ToniBonittoGSA** [comment]
I like that idea.. footer link

**Comment by thisisdano** [comment]
Yeah, let's focus on Github release notes for now, and just add a link to the footer!
