### ISSUE TITLE
SUGGESTION - Author page

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1860]
### Description
https://digital.gov/authors/dan-williams/

The 3rd post down does not appear as the other posts do. I suggest breaking the text so that it fits under the heading as the other posts are formatted.

**Comment by jeremyzilar** [comment]
Ahh yes. These are our "short posts" that link off to other pages.
See: https://digital.gov/news/

I think on author pages, we should add that light background that will make the cards more visible.
We can probably also do some signaling to better indicate that these items link off to other places

**Comment by jeremyzilar** [comment]
Will fix!
