### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1868]
**Describe the bug**
1. Events are displaying out of chrono order on main events page
2. the event that should be first on the main Events page is missing from the DG homepage

**Steps to Reproduce**
https://digital.gov/events/ 
https://digital.gov/ 

**Screenshots**
Two: 

<img width="1440" alt="Screen Shot 2020-01-21 at 7 18 25 PM" src="https://user-images.githubusercontent.com/19961574/72857177-d383b900-3c8a-11ea-9a9c-4a2d716f4065.png">

<img width="1440" alt="Screen Shot 2020-01-21 at 8 16 16 PM" src="https://user-images.githubusercontent.com/19961574/72857208-f1e9b480-3c8a-11ea-83ee-771e17e73ba0.png">

**Comment by jeremyzilar** [comment]
Fixed. I removed the "weight" from the page all together.
I will need to go through and reset how that "weight" setting is used and applied
