### ISSUE TITLE
Explore possible designs for a new resources page

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#188]
The current layout that we are using for resource pages needs to be improved upon.
At the moment, we are using the same page layout for blog posts as we are for resource pages, and that layout is not very fitting for our resource pages.

The new resource page design needs to support the most basic resource pages, which might have as little as 1-2 sentences of text while providing a foundation for larger, more robust pages to build off of it.

The new design should aim to:
- strip away the blog/category navigation on resource pages
- remove the right column (sidebar)
- Add in breadcrumbs that always link back to the main resources page
- Allow for larger block elements to go full-width if they need.
- Add in a time stamp that shows when the page was last updated
- Give readers the ability to provide us with feedback about that page via email 

---

![image](https://user-images.githubusercontent.com/395641/33279688-81974cfc-d36d-11e7-8642-df5feb85a58f.png)

**Comment by ToniBonittoGSA** [comment]
hmmm..  

 - Love the timestamp and feedback options! Def. need breadcrumb...

 - This is an example of the ones Alycia and Rodnika (old intern) did for Resource files: https://www.digitalgov.gov/resources/plain-writing-act-of-2010/ 
I like the 'Related' list (these, too, were one-column in WordPress/Solostream theme)

 - Stripping the Category menu will make the pages inconsistent with the rest [majority] of the site. That would 1) lead to confusion for people with Accessibility needs, and 2) require users to perform an extra step or two to get back to the Categories (if we want to redo navigation altogether, maybe architecture should be done separately?)

thx!

**Comment by jeremyzilar** [comment]
Here is a working version of the new resource page template that we can build off of:
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/u-s-digital-registry/

At the moment, this will only show up on pages where we add `type: resource` to the front matter. 

Here it is applied to the main **Resources** page: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/

Here is a community page:
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/communities/web-content-managers/

**Comment by jeremyzilar** [comment]
I am thinking that we should just apply these changes to ALL the pages on the site (resources, community pages, services, etc...)

The benefit would be that we wouldn't have to update all the pages with new front matter data to see the changes and all the pages would then benefit from the a better design.

**Comment by ToniBonittoGSA** [comment]
Header and copy font size is bigger.. toggle between
https://www.digitalgov.gov/communities/web-content-managers/ 
and
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/communities/web-content-managers/

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA yeah, I made a number of smaller changes to the page. I listed them out above. I am currently testing to see if we can just apply these changes to every page (resources, services, communities). Essentially every page except blog posts and events.

**Comment by ToniBonittoGSA** [comment]
Oh - I just saw the post in Slack

**Comment by thisisdano** [comment]
#### Secondary nav

While I tend to support the thought behind removing the categories nav from certain types of pages, I don't 100% know if we're ready to do it just yet.

One problem is that we don't really have a top-level nav item for news. While, functionally, the home page is the "News" page, we've kinda used that secondary nav as a proxy for a "news" landing page. I don't think it's an accessibility/usability issue to only show that secondary nav on news pages, but it _is_ an issue that the primary content type of the site has no representation in the navigation, nor a dedicated landing page of its own.

I'd be inclined to keep the secondary nav for now — and get rid of it once we have a "news" page. (And then, perhaps, we can also get rid of that giant logo in the main content area as well!)

I would also be inclined to scope typography changes tightly for now, see how it's working, then slowly apply to other page types.

- - -

#### Breadcrumbs

Oh man, I love breadcrumbs. In this implementation I find the hierarchy indicator `>` to be a little distracting. I wonder if making it gray (like https://www.gov.uk/claim-benefits-abroad) could improve its presentation and keep the focus on the links and not the hierarchy indicator.

Eventually we'll also want to change its shape, too, as the raw angle bracket is kinda galumphy.

**Comment by jeremyzilar** [comment]
Re: breadcrumbs — yeah, that angle bracket is not the greatest. I tried a number of HTML chars in that spot, and they all seemed slightly worse. I wasn't prepared to start drawing up an icon, making that work and be accessible. Figured this was suitable for now.

**Comment by jeremyzilar** [comment]
Re: nav — I didn't remove the category nav. @ToniBonittoGSA's comment was spot on. We'll address that later. 

Here is the template that would apply to all pages: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/u-s-digital-registry/

**Comment by ToniBonittoGSA** [comment]
_Click images to view properly in case the display is distorted here (for some reason, in Preview, the smaller phone screenshots appear much bigger than the desktop one)_

Hmm.. the fonts look "too big" on my Mac laptop, and the page doesn't feel as balanced... should we also bump up the size for menu navs & logo? 

<img width="1280" alt="screen shot 2017-12-01 at 4 33 40 pm" src="https://user-images.githubusercontent.com/19961574/33504452-837fbae0-d6b5-11e7-8534-dbeed44c73bf.png">


but, I do really like how the larger font sizes look on my phone **_:-D_** It's cleaner, and I think improves readability 👍 

![24172773_10159649794990243_7503239360832407353_o](https://user-images.githubusercontent.com/19961574/33504387-40fa359c-d6b5-11e7-97e1-89a3dcfd7005.jpg)

![24254897_10159649795880243_8622851578004889557_o](https://user-images.githubusercontent.com/19961574/33504395-49bb9856-d6b5-11e7-89fd-4b27fcf65d2f.jpg)

**Comment by jeremyzilar** [comment]
@thisisdano @ToniBonittoGSA — 

I removed all of the type style changes for the pages.
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/u-s-digital-registry/

So they now inherit the same type styles as all the other pages, with the exception of the width of the content (which is set to `650px`) and a few responsive adjustments for mobile.


### What was improved
- added breadcrumbs to pages
- ~~increased the font-size of headings to 36px from 32px on pages only~~
- ~~increased the font-size of body copy to 18/30 from 16/21 on pages only~~
- ~~shifted the text color to `#222` from `#555`~~
- added three distinct divs within `.entry` — `.entry-head`, `.entry-content`, `.entry-meta`
- set the `.entry-content` width to `650px` on desktop
- adjusted the styles for mobile to allow for smoother reading experience on all devices
- created an `entry.css` file for all styles relating to `.entry`
- adjusted the spacing for list-items on all pages and posts
- added "Last Updated" text, indicating when the last commit to this page was made
- linked the "Last Updated" text to the commit history page for that file.
- added "Feedback" text, giving readers the ability to email feedback on a specific page

---

I would like to apply these changes to all the "pages" on the site.
This would prevent us from having to add additional front-matter data to all the pages (e.g. `type: resource`). And this would make this the base template for building off of, till we get the USWDS installed across the site.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
