### ISSUE TITLE
Bug: Indexing stub pages in search.gov

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#1887]
**On Digital.gov**, we have a lot of "items" in our site that link directly to other resources (URLs) around govt. Let's call these "stubs" (because we haven't figured out a better name)

## About stub pages

At the top of our resources page, we have 5 links: https://digital.gov/resources/
- Two of these links take you to another website.
- Each of the links that take you to another site has a "stub page" in Digital.gov that has all the meta data about this page (e.g. [here is the USWDS Maturity Model file](https://github.com/GSA/digitalgov.gov/edit/master/content/resources/uswds-maturity-model.md))
- each of the stub pages generates a an html page that has a bit of redirect code in the `<head>` (you can see it if you "view source" on that URL `view-source:https://digital.gov/resources/uswds-maturity-model/`)
- each of the stub pages are included in [our sitemap](https://digital.gov/sitemap.xml). The URL for them are the pages on Digital.gov (e.g. `https://digital.gov/resources/uswds-maturity-model/`)

![image](https://user-images.githubusercontent.com/395641/73080557-04830a00-3e94-11ea-8713-c2b4b0a22162.png)

## The issue

**These stub pages are not being included in our search.gov index.** I am guessing because there is redirect code in the head for each of these pages that is the causing the bots to skip over them.

Example: https://find.digitalgov.gov/search?utf8=%E2%9C%93&affiliate=digitalgov&query=USWDS+Maturity+Model&commit=

Any thoughts on how we can get around this?

**Comment by jeremyzilar** [comment]
I will note that wherever possible, we are outputting the link to the URL we are linking to in the `href`, and not the stub page on Digital.gov.

**Comment by jeremyzilar** [comment]
Maybe we can put a 3 sec delay on the redirect in the head?

**Comment by dawnpm** [comment]
Our indexer follows both server side and client side redirects, but we also do not follow redirects into another domain. So yes, the redirect is the reason why those pages aren't showing up in the results, for those two reasons. I'm not sure if a delay would fool the indexer.

Possible ideas for getting around this:
- set up your stub pages as Best Bets
- set up an RSS feed of your stub pages - our RSS indexer only works off of the feed itself without rendering the pages, so it would not see the redirect. However, you would need a description block to go with the page title in order for this method to work. Do the stub pages have any description text?

**Comment by jeremyzilar** [comment]
Thank you @dawnpm 

Re: RSS feed of stub pages — Yeah, they have titles, descriptions, and keywords, etc... They are regular pages without body copy. 

I will try the delay first to see if that works.

**Comment by jeremyzilar** [comment]
This is still an issue, and I need to work on it soon.

**Comment by dawnpm** [comment]
@saracope let me know if you'd like some background on this issue. I'm leaving the Stale label for now, but if the need/desire is still there to index these pages, let me know.
