### ISSUE TITLE
Redirect HowTo.gov to DigitalGov.gov

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#190]
- [x] Transfer ownership to @jeremyzilar through the DotGov team
- [x] Make sure that the domain is paid for
- [x] add both the `www` and non-`www` redirect to the domain

**Comment by jeremyzilar** [comment]
Here is how we can track the traffic from howto.gov

We start by changing the existing redirect to go to:
`https://www.digitalgov.gov/about/lost-and-found-mapping-page/?utm_source=howto.gov`
This will put the tracking code in GA consistently for that URL.

**Comment by AndreaSigz** [comment]
Is https://www.digitalgov.gov/ redirecting to https://demo.digitalgov.gov/ yet @jeremyzilar ?

**Comment by jeremyzilar** [comment]
@AndreaSigz no. 

`https://www.digitalgov.gov/` and `https://digitalgov.gov/` are the live site (or the master branch in GitHub) 

Demo is the BETA/Preview site `https://demo.digitalgov.gov/` and will not redirect.

I know they look the same now, but when we start beta testing different versions of the site with our users, we'll be able to point them to DEMO and then back again to the main site to show the differences.

**Comment by jeremyzilar** [comment]
I just requested a DNS export of `howto.gov` from GSA IT so that we don't inadvertently break something when we make changes to the `howto.gov` DNS.

**Comment by jeremyzilar** [comment]
There are a few records tied to the Search Program in the Howto.gov DNS records.
Next step — figure out if they are needed or if we can get rid of them.

| Name | Type | Record |
|------|------|--------|
| usasearch | CNAME | http://usasearch.github.io/ |
| mail.usasearch | MX | [20] mx1.emailsrvr.com |
| mail.usasearch | MX | [10] mx1.emailsrvr.com |

**Comment by dawnpm** [comment]
@jeremyzilar we do still use the MX records. Are you just trying to clean up, or are you trying to deprecate the domain entirely?

If you want us to move off of howto entirely, please give us a timeframe so we can prioritize.

**Comment by jeremyzilar** [comment]
Thanks @dawnpm — First we are renewing the domain so we do not loose it, second, we are making sure we don't break anything should we decide to move the DNS from GSA IT to Route53. We will let you know if we are moving it.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
