### ISSUE TITLE
Add the Short URL field to New Post form

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1904]
**Is your feature request related to a problem? Please describe.**
The short URL code/line is missing from front matter; have forgotten a couple of times to add it

**Describe the solution you'd like**

Add the `short_url: `&nbsp; line in the front matter on https://workflow.digital.gov/new/posts/ 
The empty space should be a reminder to also get the short URL from https://go.usa.gov/ when done publishing a post.

**Comment by jeremyzilar** [comment]
Done. https://workflow.digital.gov/new/posts/

You can also get the full URL from the front matter and create the `short_url` before the post publishes.
