### ISSUE TITLE
CSS Bug: Image captions wrap too short

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#1906]
**Describe the bug**
Like a similar CSS issue last week, the captions under images are wrapping too short

**Steps to Reproduce**
1. Go to https://digital.gov/2020/01/22/10-employee-engagement-experiences-foster-collaboration/ 
2. Scroll down to images
3. See error

**Screenshots**

<img width="849" alt="Screen Shot 2020-01-28 at 12 56 35 PM" src="https://user-images.githubusercontent.com/19961574/73291370-07506880-41ce-11ea-9dde-baac75400b4f.png"> 

<img width="837" alt="Screen Shot 2020-01-28 at 12 56 43 PM" src="https://user-images.githubusercontent.com/19961574/73291371-07506880-41ce-11ea-9fed-a036e48920be.png">

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
