### ISSUE TITLE
data.gov resource pages are broken; content stretching across columns

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#192]
Idris Odunewu from Data.gov sent these 2:

https://www.digitalgov.gov/resources/how-to-get-your-open-data-on-data-gov/ 
https://www.digitalgov.gov/resources/inventory-data-gov-guide/ 

there are some other pages and/or posts that would have used those as well (not many, but I know it was more than just 2)

**Comment by jeremyzilar** [comment]
It looks like these pages never got rendered properly by the HTML to Markdown converter.

I am making a first pass at fixing these pages.
First step. I went through and converted the HTML to markdown using: https://domchristie.github.io/to-markdown/

I also cleaned up a lot of the formatting issues that were apparent.
- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/how-to-get-your-open-data-on-data-gov/
- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/inventory-data-gov-guide/

Going to take another pass at cleaning up broken anchor links.

**Comment by jeremyzilar** [comment]
I fixed the broken anchor links in these two resource pages

- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/how-to-get-your-open-data-on-data-gov/
- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/inventory-data-gov-guide/

There are likely still a number of smaller, formatting and markdown issues with these pages.

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Can you take a look at the preview links and let me know if this is good to go.
This way, we can push up the changes to fix the page, then maybe go back in for another pass and clean up the smaller, formatting items on the pages.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar 
For https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/how-to-get-your-open-data-on-data-gov/ 

- There are 45 underscores. About half are supposed to be there, so, I think the extras occurred because the underscore is within text that is italicized.

- The anchor links aren't lined up properly; category nav overlay blocks view. We had to add CSS padding in WordPress as a work-around, see https://docs.google.com/document/d/1Wr7dk2cbWSZbJ31C7DZUXFiWGuJeKv3oSSuloKRBlk8/edit#bookmark=id.ivkw21tsscnc 

--- 
For https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/inventory-data-gov-guide/ 

- Same anchor link/CSS issue

- YouTube vid needs embed

> [youtube=http://www.youtube.com/watch?v=ciLYjDsF4lo&w=600]

- 3 sample URLs should not be linked in this section: 

> Redacted Inventory (PDL)
> 
> http -v POST https://inventory.data.gov/organization/[organization-id]/redacted.json Authorization:xxx-your-api-key-xxx Content-Type:application/x-www-form-urlencoded Cookie:auth_tkt=foo
> 
> Unredacted Inventory (EDI)
> 
> http -v POST https://inventory.data.gov/organization/[organization-id]/unredacted.json Authorization:xxx-your-api-key-xxx Content-Type:application/x-www-form-urlencoded Cookie:auth_tkt=foo
> 
> You’d need to replace xxx-your-api-key-xxx with your actual API key which you can get in the bottom of the left sidebar of your user account, e.g. https://inventory.data.gov/user/[username]

**Comment by jeremyzilar** [comment]
Ok, I feel like these should be good enough to get out and live. 

- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/how-to-get-your-open-data-on-data-gov/
- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/inventory-data-gov-guide/

Future changes can be made to these pages to make them a lot better.

**Comment by jeremyzilar** [comment]
Ok, I feel like these should be good enough to get out and live. 

- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/how-to-get-your-open-data-on-data-gov/
- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/inventory-data-gov-guide/

Future changes can be made to these pages to make them a lot better.

**Comment by jeremyzilar** [comment]
@philipashlock —
During out migration, two of the data.gov pages did not get converted to markdown:
https://www.digitalgov.gov/resources/how-to-get-your-open-data-on-data-gov/
https://www.digitalgov.gov/resources/inventory-data-gov-guide/

We have fixed theses two pages, and restored them to their working order
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/how-to-get-your-open-data-on-data-gov/
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/inventory-data-gov-guide/

These will go live tomorrow morning.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar there are extra underscores in 2 URLs on https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/bug-192/resources/how-to-get-your-open-data-on-data-gov/ 

1: Under **Resources & Tools**, and **Resources**, remove 2 underscores in the last bullet:

> Metadata Recommendations Supporting Data Discovery and Use in Data.gov and GeoPlatform.gov (&#95;add link when documented is updated at https://cms.geoplatform.gov/sites/default/files/document&#95;library&#95;)

a - remove underscore at: (&#95;add 
b - remove 2nd/last underscore in both the visible URL, and the link code so it ends with /document&#95;library); not: document&#95;library&#95;)

---
2: There is a numbered list in the section called, "Getting geospatial metadata into Data.gov" and at number 3 it has:

> Data without a Geospatial Harvest Source — Public Data Listing Requirements (for GeoPlatform.gov and Data.gov) Lastly, to prevent duplication on Data.gov, all agencies that provide a CSW geospatial harvest source to GeoPlatform.gov and Data.gov should create an additional JSON file (called /&#95;data-nonspatial-harvest.json)&#95;

Originally, the **/data-nonspatial-harvest.json** part was italicized, but it can be changed to:

(called: /data-nonspatial-harvest.json)

or, maybe using HTML for ( and ) will work?:

&#40;called _/data-nonspatial-harvest.json_&#41;

**Comment by jeremyzilar** [comment]
These pages have been fixed.
