### ISSUE TITLE
Default meta image is distracting

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#194]
The default meta image that appears in things like slack is bright and distracting.

<img width="414" alt="screen shot 2017-11-07 at 9 09 22 am" src="https://user-images.githubusercontent.com/11464021/32507058-422f07d0-c39b-11e7-8659-4a5269dcf1e6.png">

Can we try something a little more minimal?

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
