### ISSUE TITLE
TYPO on Page [Content Cleanup]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1940]
### URL / Link to page
https://designsystem.digital.gov/maturity-model/#level-2-follow-user-experience-guidance

### What seems to be the problem (1 sentence)
Under the Heading: Level 2: Following User... 
"You should follow the UX guidance **even it you** don’t use USWDS code." 

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by saracope** [comment]
Great catch. Will transfer this Issue over to the design system site repo for the [@uswds/core](https://github.com/orgs/uswds/teams/core) team to look at.

**Comment by saracope** [comment]
Here's the related Issue on uswds/uswds-site: 
https://github.com/uswds/uswds-site/issues/857

Closing this one out.
