### ISSUE TITLE
Bug: Pages are Editable

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#1951]
**Describe the bug**
There is for me, a blue circle on the bottom right of every page. When clicked, a red circle displays above it and all boxes on the page are lined in yellow with yellow circles that say: "edit" when hovered over. 

**Steps to Reproduce**
1. Go to 'Digital.gov'
2. Click on blue circle on bottom right of screen
3. See error

**Screenshots**
Unable to add screenshots, I continue to get an error. I will try again if necessary

**Comment by ToniBonittoGSA** [comment]
Hi

They've always been editable -- since we moved to GitHub (but the round blue button is new; since our redesign launch in December)
Are you getting an error when you click one of the 'edit' links?

**Comment by onelisadunc-dev** [comment]
I apologize for the false bug report. I never noticed the blue circle before today. I am not getting an error, no. I thought that it was an error to be able to edit the pages.

**Comment by ToniBonittoGSA** [comment]
fantastic! :-) 
Closing
