### ISSUE TITLE
Bug: Low Contrast on Contact USA.gov Footer Button

### ISSUE THREAD

**Issue by greensteph** [GSA/digitalgov.gov#1955]
**Describe the bug**
Low Contrast on Contact USA.gov Footer Button

**Screenshots**

![Screen Shot 2020-02-04 at 1 11 10 PM](https://user-images.githubusercontent.com/11343071/73783156-62dfa080-4750-11ea-839d-200e2f76885a.png)

![Screen Shot 2020-02-04 at 1 13 58 PM](https://user-images.githubusercontent.com/11343071/73783083-4cd1e000-4750-11ea-9b56-58764cf8ed13.png)

**Comment by jeremyzilar** [comment]
Still working on this.
