### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by evelyntorres1** [GSA/digitalgov.gov#1992]
**Build Empathy With Stakeholder Interviews, Part 2: Conversation**
https://digital.gov/2016/07/29/build-empathy-with-stakeholder-interviews-part-2-conversation/

---
1st link does not work: https://speakerdeck.com/andrewmaier/foster-the-people-building-empathy-with-stakeholder-interviews; site cannot be reached message.

**Comment by ToniBonittoGSA** [comment]
The link is working today.. closing. 
Thanks, @evelyntorres1 !
