### ISSUE TITLE
Green bar appearing at the right edge of nav dropdown menus

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#201]
I could have sworn I fixed this as I was adding the gov banner, but here there you have it 😭 

<img width="660" alt="screen shot 2017-11-07 at 3 39 45 pm" src="https://user-images.githubusercontent.com/11464021/32523804-c95aa5bc-c3d1-11e7-9cab-e0069aa4e758.png">

### todo
- [x] remove green border from the right side of dropdown menus

**Comment by jeremyzilar** [comment]
Or we can just not have dropdown navigation in the site... which ever comes first

**Comment by jeremyzilar** [comment]
This has been fixed.
