### ISSUE TITLE
12/15 Event: Location and Venue info does not match, both incorrect

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#203]
For https://www.digitalgov.gov/event/workshop-making-government-websites-with-github-federalist-us-web-design-standards/ 

## Location/Venue info

**The above page has at top:** (I just submitted pull request with address fixed, but the 121212121 was not in the front matter)

Location
The General Services Administration121212121
1800 F St.
Washington, D.C. 20006
Room: 4150
Map: https://goo.gl/maps/bFWBD6QfDLA2 

**and at bottom:**

Venue

The General Services Administration
1800 F St. 
Washington, D.C. 20006 USA https://goo.gl/maps/bFWBD6QfDLA2

1) **Both should be:**

U.S. General Services Administration
1800 F Street NW
Washington, D.C. 20405

2) Just FYI: for Venue, the map link is on the same line as the city & zip; in browsers, it just appears to be on a new line b/c the column is narrow and the text wraps.

**Comment by ToniBonittoGSA** [comment]
<img width="1280" alt="screen shot 2017-11-08 at 9 38 15 am" src="https://user-images.githubusercontent.com/19961574/32554672-95dccf02-c468-11e7-83c7-da30b5ade333.png">
<img width="1280" alt="screen shot 2017-11-08 at 9 38 26 am" src="https://user-images.githubusercontent.com/19961574/32554673-95fe358e-c468-11e7-87a0-baae9ed25e81.png">

**Comment by jeremyzilar** [comment]
Yes, there is a typo at in event location. We will push that out.
In addition, I will also change the event form to reflect the correct date.

**Comment by jeremyzilar** [comment]
This has been fixed. Closing
