### ISSUE TITLE
Fix broken links on Resources page

### ISSUE THREAD

**Issue by AndreaSigz** [GSA/digitalgov.gov#204]
Below are the categories where the links are bad.

Contact Centers
G3C link: https://demo.digitalgov.gov/resources/tmp

2011 Federal Contact Center Survey, Final Report: https://demo.digitalgov.gov/resources/CDN/files/2014/07/2011-Federal-Contact-Center-Survey-Final-Report-Sept30th2011-Prepared-for-GSA-OCSIT.pdf

Customer Experience
Report of the Citizen Service Levels Interagency Committee: https://demo.digitalgov.gov/resources/CDN/files/2014/07/Report-of-the-Citizen-Service-Levels-Interagency-Committee-CSLIC-2005.doc

Digital Strategy
Putting Citizens First: Transforming Online Gov: 
https://demo.digitalgov.gov/resources/CDN/files/2013/11/Federal-Web-Managers-White-Paper.pdf

Social Media
Barriers and Solutions to Implementing Social Media in Government:
https://demo.digitalgov.gov/resources/CDN/files/2013/11/Social-Media-Fed-Govt-Barriers-Potential-Solutions.pdf

Website Management
Interagency Committee on Government Information—Recommended Policies:
https://demo.digitalgov.gov/resources/CDN/files/2014/07/Recommended-Policies-and-Guidelines-for-Federal-Public-Websites-2004.pdf

ICGI Report Attachments:
https://demo.digitalgov.gov/resources/CDN/files/2014/07/Report-Attachments-ICGI-Policies-and-Guidelines-for-Federal-Public-Websites-2004-HowToGov.pdf

ICGI Summary and Background:
https://demo.digitalgov.gov/resources/CDN/files/2014/07/Summary-and-Background-ICGI-Recommendations-for-Federal-Public-Websites-2004-HowToGov.pdf

**Comment by thisisdano** [comment]
It looks like all these files should be linked to `https://s3.amazonaws.com/digitalgov/_legacy-img/``DDDD/MM/filename`

I tried it with a couple and that worked

**Comment by thisisdano** [comment]
Is `https://www.digitalgov.gov/communities/government-contact-center-council/` the proper link for the G3C?

**Comment by thisisdano** [comment]
Workin' on this now

**Comment by thisisdano** [comment]
Workin' on this now

**Comment by thisisdano** [comment]
Workin' on this now

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
