### ISSUE TITLE
Event details not showing in workflow

### ISSUE THREAD

**Issue by DanielJPino-ux** [GSA/digitalgov.gov#2044]
Trying to update website via workflow but details are missing when making edits. 

**USWDS Monthly Call: Website Standards Panel Discussion**
https://digital.gov//event/2020/02/20/uswds-monthly-call/

---

**Please describe the issue clearly. Include a screenshot if needed**

**Comment by saracope** [comment]
It looks like there are a lot of CORS errors in the console.
Could that be the issue? @jeremyzilar 

`Access to XMLHttpRequest at 'https://digital.gov/event/2019/07/25/machine-learning-how-bureau-labor-statistics-did-it/index.json' from origin 'https://workflow.digital.gov' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by jeremyzilar** [comment]
Here is where the CORS issues are showing up: https://workflow.digital.gov/edit/posts/?page=https://digital.gov/2019/12/19/a-new-digitalgov/

**Comment by saracope** [comment]
This is working now. The federalist team needed to re-enable CORS for our sites after they did an internal migration.
