### ISSUE TITLE
TYPO [Suggestion]

### ISSUE THREAD

**Issue by onelisadunc-dev** [GSA/digitalgov.gov#2049]
### URL / Link to page
https://digital.gov/2017/09/28/finding-usability-testers-tips-from-an-army-recruiter/

### Tell us how we can make this page better
There is a typo in the following sentence: "Talk to everyone. Never let an opportunity to recruit **passes** you by."

**Comment by ToniBonittoGSA** [comment]
Thanks, Lisa!

**Comment by ToniBonittoGSA** [comment]
PR https://github.com/GSA/digitalgov.gov/pull/2174
