### ISSUE TITLE
Update to the latest Hugo release

### ISSUE THREAD

**Issue by saracope** [GSA/digitalgov.gov#2055]
We're currently several versions behind and the [latest release](https://github.com/gohugoio/hugo/releases) [v.65](https://gohugo.io/news/) has features work looking at/implementing.

**Comment by saracope** [comment]
Started in https://github.com/GSA/digitalgov.gov/pull/2052

**Comment by jeremyzilar** [comment]
It would be helpful to get an RSS feed of the HUGO releases in Slack

**Comment by jeremyzilar** [comment]
Upgrading to 0.66.0 here, and it was not that hard.
https://github.com/GSA/digitalgov.gov/pull/2164
