### ISSUE TITLE
Bug: fix encoding for apostrophe

### ISSUE THREAD

**Issue by afeijoo** [GSA/digitalgov.gov#2077]
**Describe the bug**
Apostrophe is appearing as `&#39;`

**Steps to Reproduce**
1. Go to https://digital.gov/authors/russell-oneill/
3. Scroll down to the heading, `Russell O&#39;Neill`

![image](https://user-images.githubusercontent.com/400690/75686390-31cc9000-5c6a-11ea-9521-6c7f87ee2da4.png)

**Comment by saracope** [comment]
Same issue on: https://digital.gov/authors/kristen-onell/

**Comment by saracope** [comment]
@DanielJPino-ux Can you take a look at these? The markdown for these authors needs updated.

**Comment by saracope** [comment]
Do you think this issue is coming from the workflow tool @jeremyzilar?

**Comment by jeremyzilar** [comment]
Fixing over here for all the names 🌈  https://github.com/GSA/digitalgov.gov/pull/2161

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
