### ISSUE TITLE
End of year Round-Up piece

### ISSUE THREAD

**Issue by AndreaSigz** [GSA/digitalgov.gov#212]
Create a new piece (aim to publish week of 11/28) that asks our communities to tell us, "What did you learn this year?" (or something to that effect). 

This post will show how agencies can contribute to our GitHub efforts, in a fun way.

**Comment by AndreaSigz** [comment]
Here's the link to the Call for Community Input doc: https://docs.google.com/document/d/1n6mxIxv3VJ3LW7dZj_E7OuC2HpNkMck1nhV0Gq_2SP8/edit

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
