### ISSUE TITLE
Bug: No visible text or indicator in Search button

### ISSUE THREAD

**Issue by hallmedia** [GSA/digitalgov.gov#2145]
**Describe the bug**
Search Submit button has a hidden text node of “Search” for assistive technology, but lacks a visible text label or indicator. The CSS uses a background image of an SVG icon, however the path to the resource contains an extra ‘/’, so no image is displayed.

**Steps to Reproduce**
1. Go to https://digital.gov/communities/accessibility/
2. Inspect source of Button
     ```<button class="usa-button" name="commit" type="submit"><span class="usa-sr-only">Search</span></button>```
3. Observe the <span> is hidden
4. Observe the img src does not load via CSS

**Screenshots**
(attached)
<img width="360" alt="Screen Shot 2020-03-04 at 1 06 43 PM" src="https://user-images.githubusercontent.com/3154739/75909599-654e1c80-5e1a-11ea-8543-be5ede14bc71.png">

**Comment by saracope** [comment]
Thanks!
