### ISSUE TITLE
User can provide feedback about a given page.

### ISSUE THREAD

**Issue by afomi** [GSA/digitalgov.gov#2148]
**Is your feature request related to a problem? Please describe.**

As a user,
I want to leave feedback on a site,
So that I can express how it did not meet my expectations or needs.

As a webmaster,
I want to allow users to leave feedback on a page,
So that I can improve the site accordingly

**Describe the solution you'd like**

See the "Is this page useful?" widget on https://www.gov.uk/email/subscriptions/new?topic_id=service-manual-service-standard.

## Deliverables

* [ ] @afomi to allow Touchpoints to provide an HTML version of the thumbs up/down form component
* [ ] @jz to create default set of .scss styles that can be included in the a site that is running USWDS 2.0

**Comment by afomi** [comment]
inspiration:

![image](https://user-images.githubusercontent.com/67984/75917572-1058d900-5e0f-11ea-99d0-c8bb3003f598.png)

**Comment by jeremyzilar** [comment]
@afomi How can we get something like this running through Touchpoints and onto a preview branch where we can style it?

**Comment by afomi** [comment]
very rough working sketch here

![rough-css](https://user-images.githubusercontent.com/67984/75917885-9543f280-5e0f-11ea-8aba-332514add788.png)

**Comment by afomi** [comment]
and yes @jeremyzilar, can get it out on a branch soon, so you can work with the html and styles

**Comment by afomi** [comment]
Here's the HTML-only from the Gov UK widget, as reference.

![content-only](https://user-images.githubusercontent.com/67984/75917965-ba386580-5e0f-11ea-9c97-e611a8457070.png)

**Comment by afomi** [comment]
![Screen Shot 2020-03-04 at 2 29 43 PM](https://user-images.githubusercontent.com/67984/75929078-a0ede400-5e24-11ea-9a51-cd4c9ed13d98.png)

**Comment by jeremyzilar** [comment]
Yeah, if you can create a means for me to get this on our site as raw HTML, I will create a SCSS file based off the USWDS that can be used for it.

**Comment by jeremyzilar** [comment]
Related PR https://github.com/GSA/digitalgov.gov/pull/2167

**Comment by saracope** [comment]
Current PR #2182
