### ISSUE TITLE
Add screenshots to Markdown formatting page

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#215]
@ToniBonittoGSA Use this issue to upload screenshots via drag-and-drop. Then use the URL from the uploaded image (or images) in this issue in the wiki entry.

For instance, the following code can be seen in edit mode for the image below.

```
<img width="781" alt="screen shot 2017-11-14 at 1 24 54 pm" src="https://user-images.githubusercontent.com/11464021/32805704-10e3340e-c93f-11e7-9973-d6cd1ffc3967.png">
```

<img width="781" alt="screen shot 2017-11-14 at 1 24 54 pm" src="https://user-images.githubusercontent.com/11464021/32805704-10e3340e-c93f-11e7-9973-d6cd1ffc3967.png">

Use `https://user-images.githubusercontent.com/11464021/32805704-10e3340e-c93f-11e7-9973-d6cd1ffc3967.png` as the url in the wiki!

**Comment by thisisdano** [comment]
That said, looking at the wiki page itself, I believe you can force characters to appear as characters (and not markdown formatting) by preceding them with a `\` character.

If I type `\_the\_ file name` in markdown it will appear as \_the\_ file name as opposed to _the_ file_name

See https://daringfireball.net/projects/markdown/syntax#backslash

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA do you need this issue? Can this be closed?
