### ISSUE TITLE
Update the Federal CrowdSource Mobile Testing Program Page

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#216]
This program is great, however this landing page doesn't tell the story of the program as well as it could

https://www.digitalgov.gov/services/mobile-application-testing-program/
We need to make time with @jpgsa to focus page up

**Comment by jeremyzilar** [comment]
Next step — We need to ask @jpgsa or David Fern to take a look at this page on DEMO  and let us know what needs updatingL: https://demo.digital.gov/services/mobile-application-testing-program/

**Comment by saracope** [comment]
Email David Fern and @jpgsa to review this page and ask for updates.
