### ISSUE TITLE
⚠️  Don't upgrade to Hugo 0.66.0

### ISSUE THREAD

**Issue by afomi** [GSA/digitalgov.gov#2162]
Hugo 0.64.0 works well.
Hugo 0.66.0 throws 102 `ambiguous` errors when trying to resolve links.

Just a heads up.

References

* https://discourse.gohugo.io/t/problem-with-new-0-65-x-getpage-relative-lookups/23598/17
* https://github.com/gohugoio/hugo/pull/6951

**Comment by afomi** [comment]
Just a note that I wasn't sure if/how https://github.com/GSA/digitalgov.gov/blob/master/.hugo-version would affect Hugo. It didn't seem to make a difference in my case.

**Comment by jeremyzilar** [comment]
Thank you @afomi, yes I have been looking at that :/
https://github.com/GSA/digitalgov.gov/pull/2052

And will note the Hugo version in the README.

**Comment by jeremyzilar** [comment]
Will be updating over here: https://github.com/GSA/digitalgov.gov/issues/2055
