### ISSUE TITLE
Can we resize embedded videos?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#217]
In WordPress, we sized all videos at 600 pixels wide (relative height) to fit the 2-column layout for Posts. We also sized them to be the same dimensions as Featured Images, 301 x 212, for Community pages 

As other GitHub templates are created, it would be nice to be able to size them as needed to fit sidebar, breakout boxes, or whatever else comes up in DG's redesign.

**Comment by jeremyzilar** [comment]
This is a great idea. We will do this in the new post templates.

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
