### ISSUE TITLE
Replace M-05-04 with link to M-17-06

### ISSUE THREAD

**Issue by RachelF** [GSA/digitalgov.gov#2173]
### Replace the reference to M-05-04 with a link to M-17-06. 17-06 is the latest version of fed web policies, and 05-04 was rescinded when it was issued.
[M-17-06: Policies for Federal Agency Public Websites and Digital Services](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf) (PDF, 1.2MB, 18 pages, Nov 2016)

There may be other pages on the site that still link to 05-04; can you please make sure it's updated everywhere?
Thanks!

**Comment by jeremyzilar** [comment]
@RachelF — Are you suggesting that we scrub M-05-04 from all the pages, and reference M-17-06 in it's place? 

Including taking down this page: https://digital.gov/resources/policies-for-federal-agency-public-websites-m-05-04/ and redirecting it to https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf

**Comment by afeijoo** [comment]
@jeremyzilar & @RachelF 

Yes, take down https://digital.gov/resources/policies-for-federal-agency-public-websites-m-05-04/. I suggest redirecting it to https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/.

**Comment by ToniBonittoGSA** [comment]
Adding redirect https://github.com/GSA/digitalgov.gov/pull/2412

**Comment by ToniBonittoGSA** [comment]
replaced m-05-04 on privacy act page https://github.com/GSA/digitalgov.gov/pull/2413

**Comment by ToniBonittoGSA** [comment]
related https://github.com/GSA/digitalgov.gov/issues/2419
