### ISSUE TITLE
Revise site policies?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#218]
Do our Site Policies need revision? 

DG: https://www.digitalgov.gov/about/policies/ 

GSA’s (various) https://www.gsa.gov/reference-overview

**Comment by jeremyzilar** [comment]
Here is an example of how the Design System links to outside sites: https://designsystem.digital.gov/getting-started/developers/#browser-support

**Comment by saracope** [comment]
Next steps: Move `Reuse and Copyright` to the top and move `Comments` to the bottom.
