### ISSUE TITLE
Add This Week's IDEA posts to the 21cIDEA resource page

### ISSUE THREAD

**Issue by afeijoo** [GSA/digitalgov.gov#2183]

**Comment by saracope** [comment]
Those posts show on the 21c topic page. We could add a link to the 21c resource page with something like `more info...` and then link to it: https://digital.gov/topics/21st-century-idea/

That way we're not duplicating

**Comment by afeijoo** [comment]
Yes, you're right! Instead of jumping to the solution, I'm rewriting as a user story 😄 

As a visitor to the 21cIDEA resource page at https://digital.gov/resources/21st-century-integrated-digital-experience-act/
I would like to read other timely content 
So that I can learn more about 21cIDEA and stay current
