### ISSUE TITLE
Create workflow for submitting new content

### ISSUE THREAD

**Issue by AndreaSigz** [GSA/digitalgov.gov#219]
Once we have a new case study template for content submissions, we should map out/write down the flow for what it looks like for agencies to submit content—who reviews, if we make any edits (and would then have to send it back to the agency for review again), when it gets posted, etc.

Also, do we want to keep proactively making broad asks of agencies for content or do we want to reach out to specific ppl on the listservs, when we see an interesting story crop up?

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
