### ISSUE TITLE
About Us page: 1 of 2 bulleted lists is not displaying correctly

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#222]
On https://www.digitalgov.gov/about/ 

Instead of a bulleted list, the text for "We’ve found that agencies need: " is showing as a paragraph.

> We’ve found that agencies need: - Guidance on implementing digital policies and initiatives - Open access to modern methods, practices, policies, and tools - Focused trainings and events that help teams learn and adopt new concepts - Easy access to collaborate with others across government who are working on the same problems

When I went to the Edit page, the code looks ok (dashes for a bulleted list) and it displayed as a list in the Preview tab: 

> We’ve found that agencies need:
> - Guidance on implementing digital policies and initiatives
> - Open access to modern methods, practices, policies, and tools
> - Focused trainings and events that help teams learn and adopt new concepts
> - Easy access to collaborate with others across government who are working on the same problems

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
