### ISSUE TITLE
Update the Connected Govt Act  page to use `usa-accordion card-policy`

### ISSUE THREAD

**Issue by afeijoo** [GSA/digitalgov.gov#2234]
On https://digital.gov/resources/connected-government-act/, it currently includes an image of the PDF of the Act. 

Update it to use the new `usa-accordion card-policy` component for the Act (like the accordion on https://digital.gov/resources/21st-century-integrated-digital-experience-act/)

**Comment by saracope** [comment]
The accordion uses `{{< card-policy >}}`.

**Comment by afeijoo** [comment]
Sorry, let me try rewriting the user story to be more clear 😄 

As a visitor to https://digital.gov/resources/connected-government-act/
I expect to see an inline view of the law instead of the [current screencap image](https://s3.amazonaws.com/digitalgov/hr2331-connected-govt-act_w800.png)
So that I can read the full text of the law in HTML and find keywords in context

**Comment by saracope** [comment]
@ToniBonittoGSA is going to look at it. Thanks!

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/digitalgov.gov/pull/2296
