### ISSUE TITLE
UX Summit 2020 

### ISSUE THREAD

**Issue by Schultea** [GSA/digitalgov.gov#2243]
https://digital.gov/event/2019/05/15/2019-government-ux-summit/

Strike language of call for participation (ended March 9). 

Add that submissions are now in review. The date change will be announced soon. And the event will be all virtual.

**Comment by saracope** [comment]
Here's the correct post: https://digital.gov/2020/02/27/call-for-government-ux-summit/

**Comment by saracope** [comment]
@Schultea Go ahead and make these changes then submit as a Pull Request. @ToniBonittoGSA or I can review it.
