### ISSUE TITLE
URL does not wrap, breaks across column

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#225]
On https://www.digitalgov.gov/resources/how-to-get-your-open-data-on-data-gov/ 

> Metadata Recommendations Supporting Data Discovery and Use in Data.gov and GeoPlatform.gov (add link when documented is updated at https://cms.geoplatform.gov/sites/default/files/document_library)

related issue: https://github.com/GSA/digitalgov.gov/issues/192

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
