### ISSUE TITLE
Bug: broken link to the checklist on the homepage

### ISSUE THREAD

**Issue by afeijoo** [GSA/digitalgov.gov#2279]
**Describe the bug**
The link to `Checklist of Requirements for Federal Websites and Digital Services` on the Digital.gov homepage leads to a 404 error.

**Steps to Reproduce**
1. Go to https://digital.gov/
1. Scroll down to '....'
1. Click on the link for `Checklist of Requirements for Federal Websites and Digital Services`
1. Note that the link is https://digital.gov/%3cnil%3e?dg (the expected link is https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/?dg)
1. See 404 error

**Screenshots**
<img width="1040" alt="Screen Shot 2020-03-24 at 8 18 49 AM" src="https://user-images.githubusercontent.com/400690/77424814-1dcb0880-6da8-11ea-842a-61ac4c505e0e.png">

**Comment by afeijoo** [comment]
Update: This is now affecting several of the links on the homepage in the top `Popular Guides and Resources` section.

**Comment by saracope** [comment]
We're looking at it. Thanks. It's a wider issue.
