### ISSUE TITLE
Update Services>Search page w/new name; Search.gov -

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#228]
https://www.digitalgov.gov/services/search/ 

page URL is fine, but title and copy should now use Search.gov instead of "DigitalGov Search"

**Comment by ToniBonittoGSA** [comment]
Google doc - https://docs.google.com/document/d/1dTxq3shcAgKGJRl3VUEi3xykvZGZEhht5Mxh8OPtzRQ/edit

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
