### ISSUE TITLE
Bug: remove circular link on the service directory page 

### ISSUE THREAD

**Issue by afeijoo** [GSA/digitalgov.gov#2318]
**Describe the bug**
As a user on https://digital.gov/services/directory/, 
When I click on `Directory of services, tools, and teams`
I expect to go to a new, different page instead of staying on the same page going in circles.

**Steps to Reproduce**
1. Go to 'https://digital.gov/services/directory/
2. Click on `Directory of services, tools, and teams`
3. Notice how the URL is the same as the page you're already on.

**Screenshots**
<img width="556" alt="Screen Shot 2020-04-02 at 8 24 26 AM" src="https://user-images.githubusercontent.com/400690/78249354-316b2300-74bc-11ea-91df-0234dbb76d1d.png">

**Comment by jeremyzilar** [comment]
Oooh thanks @afeijoo 🍎
