### ISSUE TITLE
Bug: Blank page when using edit button on topics (Workflow, and live site)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#2344]
**Describe the bug**
There's a bug when I try to edit a topic-- from the live site, and from the Workflow site.

1 - Live site
When I hit the yellow edit button on https://digital.gov/topics/firstnet/ 

<img width="1440" alt="Screen Shot 2020-04-10 at 9 03 38 AM" src="https://user-images.githubusercontent.com/19961574/78993168-15dec880-7b0b-11ea-814e-51320dfef19b.png">

it launches another tab -- and the URL there is: 

> https://workflow.digital.gov/edit/topics/?page=https://digital.gov/topics/firstnet/ 

but the page is empty.

<img width="1440" alt="Screen Shot 2020-04-10 at 9 03 47 AM" src="https://user-images.githubusercontent.com/19961574/78993204-30b13d00-7b0b-11ea-9c46-10ac13d400df.png">

---

2 - Workflow
Similar bug/error, but different URL:

In https://workflow.digital.gov/topics/ I hit the purple edit button for `Firstnet` 

<img width="1440" alt="Screen Shot 2020-04-10 at 9 12 38 AM" src="https://user-images.githubusercontent.com/19961574/78993334-80900400-7b0b-11ea-9842-b9f8d9bc9ce5.png">

and get this different URL (in the same tab, not a new one)

> https://workflow.digital.gov/edit/topics/?page=https://digital.govundefined

that also loads a blank page

<img width="1440" alt="Screen Shot 2020-04-10 at 9 12 47 AM" src="https://user-images.githubusercontent.com/19961574/78993359-8a196c00-7b0b-11ea-9520-1ca4298b0d44.png">

**Comment by jeremyzilar** [comment]
Sorry, the ability to edit topics was not added into Workflow. :/ We will likely be transitioning to NetlifyCMS where this will work
