### ISSUE TITLE
New option(s) for Source/Website needed for short posts in Workflow

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#2352]
**Is your feature request related to a problem? Please describe.**

In https://workflow.digital.gov/new/news/ the spot to credit the source program/website needs additional options. I need to add one from Section508.gov, but it is not an option in the drop down list.

**Describe the solution you'd like**
Pls add Section508.gov as an option for Source/Website

<img width="1440" alt="Screen Shot 2020-04-10 at 4 31 54 PM" src="https://user-images.githubusercontent.com/19961574/79021202-e64eb100-7b48-11ea-9c10-9a8545f88d57.png">

If someone shows me where that code is, I can add others as they come up.

**Comment by saracope** [comment]
JZ did this recently in https://github.com/GSA/digitalgov.gov/pull/2276. Would love to pair on the update.

**Comment by jeremyzilar** [comment]
I can look at this.

**Comment by ToniBonittoGSA** [comment]
@saracope Also need one for FedRamp
Image: 
![fedramp-logo-circle-stamp](https://user-images.githubusercontent.com/19961574/84811474-e94b9f00-afda-11ea-9130-085b9e202eaf.png)

**Comment by jeremyzilar** [comment]
Let me know if you want to pair on setting this up in Netlify CMS. I’ve been using it for the last few months, and it’s solid.
