### ISSUE TITLE
Discovery: Understand the usage of the Negotiated Terms of Service Agreements page

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#237]
Our **Negotiated Terms of Service Agreements** page is one of the most visited resource pages on DigitalGov. https://www.digitalgov.gov/resources/negotiated-terms-of-service-agreements/

We should find out how we can keep this page up to date, and make the experience page better.

---
Here are the main pages:

- **Negotiated Terms of Service Agreements** https://www.digitalgov.gov/resources/negotiated-terms-of-service-agreements/
- **Federal-Compatible Terms of Service Agreements** https://www.digitalgov.gov/resources/federal-compatible-terms-of-service-agreements/
- **Agency Points of Contact for Federal Compatible Terms of Service Agreements** https://www.digitalgov.gov/resources/agency-points-of-contact-for-federal-compatible-terms-of-service-agreements/
- **Antideficiency Act Implications of Certain Online Terms of Service Agreements** https://www.digitalgov.gov/resources/antideficiency-act-implications-of-rtain-online-terms-of-service-agreements/

----

### What we know so far

- **There is a clear need** — This page is one of the more popular resource pages on DigitalGov.
    - Roughly, **750** people visit this page each month
    - Only a few are making it to the lower, company sub-pages for each agreement (https://github.com/GSA/digitalgov.gov/issues/231)
- **This page is hard to keep updated** — Right now, we have one person in the GSA who receives emails about the content of this page.
- **The quality of the information on the page is questionable** — The terms of service that companies provide can change without us knowing. How can we work to keep those pages updated and/or make the quality of the information more clear to readers

### A view of the traffic over 30 days
![image](https://user-images.githubusercontent.com/395641/33108043-18bade74-cf08-11e7-80a1-da196454f9f7.png)

### What we need to move forward
- **Understand the need** — Why are people visiting this page? 
    - Anecdotally through our research, we are hearing that because the GSA is a trusted agency, people in Govt are looking to us to provide a list of companies/tools/services that are worth using in their own agencies. Also, having the terms of services available and in the open and on DigitalGov helps agencies to advance the cause within their own agency to use these tools.

**Comment by jeremyzilar** [comment]
FYI - There is a separate issue that we are working on related to this.
- **Redirect the Individual Terms of Service pages to the main terms of service page** https://github.com/GSA/digitalgov.gov/issues/231

**Comment by jeremyzilar** [comment]
We are going to put a feedback box at the top of the Terms of Service pages, signaling to readers know that we are making some changes to the pages and would like their feedback https://github.com/GSA/digitalgov.gov/issues/285

**Comment by jeremyzilar** [comment]
We should look into the traffic on these pages to determine what to do next.

**Comment by saracope** [comment]
Current traffic:
<img width="1184" alt="Screen Shot 2020-03-20 at 12 49 17 PM" src="https://user-images.githubusercontent.com/2197515/77186420-3c2fbc00-6aa9-11ea-9be1-278461ffbc25.png">

**Comment by saracope** [comment]
Latest spike: 
<img width="1385" alt="Screen Shot 2020-04-07 at 1 58 34 PM" src="https://user-images.githubusercontent.com/2197515/78703325-f6138e80-78d7-11ea-92d3-ce2fce1b1be7.png">
