### ISSUE TITLE
Bug: Workflow, Edit News -- Source / Website field

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#2370]
**Describe the bug**

1) Sometimes the drop down has no choices (code on the right says `null` but should be 18F)

<img width="1440" alt="Screen Shot 2020-04-13 at 1 59 14 PM" src="https://user-images.githubusercontent.com/19961574/79145968-91e94280-7d8f-11ea-8eae-1b54a6f9aa34.png">

***

2) Sometimes it's appears "stuck" on Login.gov

When I open the page

<img width="1440" alt="Screen Shot 2020-04-13 at 2 00 25 PM" src="https://user-images.githubusercontent.com/19961574/79146072-c957ef00-7d8f-11ea-8cc4-23abf81ab2cd.png">

and when I click the drop down, the correct source is selected/highlighted, but won't change from displaying Login.gov in the form (is correct in the code on the right).

<img width="1440" alt="Screen Shot 2020-04-13 at 2 00 39 PM" src="https://user-images.githubusercontent.com/19961574/79145970-9281d900-7d8f-11ea-9017-04d52a62c6e7.png">

**Comment by saracope** [comment]
Issue moved to [GSA/digitalgov-workflow #38](https://github.com/GSA/digitalgov-workflow/issues/38) via [**ZenHub**](https://www.zenhub.com/)
