### ISSUE TITLE
Change DigitalGov Search Page to Search.gov

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#240]
I noticed that this page still references DigitalGov Search, not Search.gov: https://www.digitalgov.gov/services/search/

- [ ] update page with Search.gov (referenced in the heading and twice in the description)

**Comment by ToniBonittoGSA** [comment]
I sent a doc to Ashley and Dawn last week https://docs.google.com/document/d/1dTxq3shcAgKGJRl3VUEi3xykvZGZEhht5Mxh8OPtzRQ/edit  
~ awaiting input on any additional changes to the copy on that page

**Comment by jthalls** [comment]
cool @ToniBonittoGSA. I've been pulling information from various programs for our YouTube playlist descriptions so that's why I stumbled upon it.

**Comment by dawnpm** [comment]
@ToniBonittoGSA I updated the text - some light changes in addition to the name update. Do you need a new logo file?

**Comment by ToniBonittoGSA** [comment]
@dawnpm  Yes, please - as large as possible; just email to me, thx!

**Comment by jeremyzilar** [comment]
Here is where this work is taking place: https://github.com/GSA/digitalgov.gov/pull/274
