### ISSUE TITLE
Bug: alias redirect not working

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#2419]
**Describe the bug**
re: https://github.com/GSA/digitalgov.gov/issues/2173 

Redirect directions on https://github.com/GSA/digitalgov.gov/wiki/Redirects 

I added 

> /resources/policies-for-federal-agency-public-websites-m-05-04/ 

in the `aliases` list in the front matter for 

https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/ 

<img width="1232" alt="Screen Shot 2020-04-20 at 3 10 37 PM" src="https://user-images.githubusercontent.com/19961574/79790264-7cd55c00-8319-11ea-9621-16fb48297c36.png">

**_but_** https://digital.gov/resources/policies-for-federal-agency-public-websites-m-05-04/ 
does not redirect to https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/

**Comment by jeremyzilar** [comment]
You need to also remove the page (file) that you redirecting.

If the file for this page still exists, https://digital.gov/resources/policies-for-federal-agency-public-websites-m-05-04/ then it will not redirect the page. 

Give that a try in a PR and tag me in it before pushing it live.

**Comment by ToniBonittoGSA** [comment]
That worked! 😄
