### ISSUE TITLE
[Content Cleanup] Fix linkedin info on author pages

### ISSUE THREAD

**Issue by saracope** [GSA/digitalgov.gov#2440]
### What seems to be the problem (1 sentence)
Folks should be entering their Linkedin username only on author pages. Not the whole URL. Need to scan the site and check for author pages that include "http" in the Linkedin value.

example: https://digital.gov/authors/bridget-fields/

**Comment by thumbsupep** [comment]
Is this still needed? if so I'd like to contribute

**Comment by thumbsupep** [comment]
I've written a node script and determined it's 
amin-mehr
bridget-fields
jada-jones
joseph-castle
michelle-mcnellis
nikki-zeichner
omid-ghaffari-tabrizi
who need updates. I will make a PR
