### ISSUE TITLE
Bug: Workflow.Digital.gov Author Page - Social Accounts

### ISSUE THREAD

**Issue by RhettSkelton** [GSA/digitalgov.gov#2442]
**Describe the bug**
The fields do not provide appropriate instructional text. If a user inputs the full URL to their social media account, then Federalist will add in a prefixed URL in front of the field input, creating a broken link. Example: an input of www.linkedin.com/in/me will build as www.linkedin.com/in/www.linkedin.com/in/me.

Users also cannot input a link to a group or company instead of their personal account, since the prefixed URL for personal pages is https://www.linkedin.com/in/, while a company is https://www.linkedin.com/company/.

**Steps to Reproduce**
1. Go to 'https://workflow.digital.gov/edit/authors/?page=https://digital.gov/authors/rhett-skelton/'
2. Input a full URL into the LinkedIn field
3. Copy the text
4. Submit a pull request with the update
5. Check the Federalist build
5a. Open preview
5b. Click on the author headshot
5c. Test the LinkedIn icon link

**Sample Pull Request*
https://github.com/GSA/digitalgov.gov/pull/2436

**Comment by jeremyzilar** [comment]
Good catch!

**Comment by saracope** [comment]
@hursey013 Brian, can you add in the appropriate text to the Author collection in Netlify to make this more clear.
