### ISSUE TITLE
Blockchain Join Us Buttons

### ISSUE THREAD

**Issue by RhettSkelton** [GSA/digitalgov.gov#2496]
**Blockchain**
https://digital.gov/communities/blockchain/

---

I think both of the "Join Us" buttons are not correct on the Blockchain page.
https://digital.gov/communities/blockchain/

The first button should have a custom email where it's bold below.

_To join, email **listserv@listserv.gsa.gov** with Blockchain listserv in the subject._

The issue seems to be that requesting subscribe in the body text (with nothing in the subject) requires sending to a custom email for the LISTSERV. However, current text and button say the following. I think the bolded email needs to be corrected to the blockchain specific email. The auto-generated body text when clicking the button also leaves the period on the end of BlockchainPublic, which could be causing another issue. The part that I don't understand about this one is why not just do the subscribe in a standard way per Mark's guidance below.

_To join, email **listserv@listserv.gsa.gov** with nothing in the subject and SUB BlockchainPublic. in the body._

Mark's Guidance
LISTSERV only accepts commands in the Body, except when it sends a ticketed response back to a list owner who can click the link or reply with "ok." LISTSERV also supports command aliases (i.e. messages sent to a email aliases like LISTNAME-unsubscribe-request@listserv.gsa.gov), which will remove the sender from the LISTNAME list. With command aliases, subject and body are ignored and the message header is used to determine the address requesting removal.

**Comment by jeremyzilar** [comment]
Yes, most of the methods for signup across communities should be standardized.

This is less of a technical fix for the platform, and more of a community liaison task.

1. go around to each community lead and let them know that the method for how their community gets sign-ups is going to change (_just a weee bit_) and how it'll affect them. Most will appreciate the easier method.
2. Then the join copy should be removed from the post body of the community pages.

**Comment by jeremyzilar** [comment]
To fix the "public" blockchain listserv, I would:

1. Go here https://github.com/GSA/digitalgov.gov/edit/master/content/communities/blockchain.md
2. Edit the page
3. Find `subscribe_email_body: "SUB BlockchainPublic."` and remove the period.
4. Then change `subscribe_email_body` to `subscribe_email_subject` 👈 
5. Commit the change, create a PR, get it approved, and merge.

I am guessing this was a typo when we produced the page, not a specific desire to make the public listserv work differently than the non-public one.

**Comment by jeremyzilar** [comment]
Take a look at the community page settings: https://workflow.digital.gov/new/communities/
Also playing around with the specific settings for each page would also help explain the fields that make those Join boxes work, and what the options are.
https://github.com/GSA/digitalgov.gov/edit/master/content/communities/blockchain.md

**Comment by RhettSkelton** [comment]
Adding @jeremyzilar link to the recommendation. We should update it to only a few options as Mark noted.

https://github.com/GSA/digitalgov.gov/wiki/Listserv-Signup-Options

**Comment by its-a-lisa-at-work** [comment]
This issue seems to be across all communities; I tried to sign up for the DevOps community but wasn't able to either because the button isn't working. 

cc: @pburkholder

**Comment by saracope** [comment]
@Schultea Can you look at this? It seems these still need to be updated.

**Comment by Schultea** [comment]
@saracope created a PR here: https://github.com/GSA/digitalgov.gov/pull/3859
