### ISSUE TITLE
Issues related to PR 247; the Negotiated TOS list

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#251]
Glad all redirects work. 👍 https://github.com/GSA/digitalgov.gov/pull/247 got published before I finished checking on info online, old emails.. 
Notes below are for the Neg. TOS page https://www.digitalgov.gov/resources/negotiated-terms-of-service-agreements/ 

Good catch, Dan; looks like **News Genius** should now be just **Genius**
the link for the original TOS page http://news.rapgenius.com/static/government_terms redirects to https://genius.com/static/government_terms; should update as well.

---
JZ, [**Pop** was absorbed into another company](https://blog.marvelapp.com/pop-joins-marvel/) and the TOS page just added https://marvelapp.com/terms/ looks like a regular TOS; not a gov't TOS or gov't amendment - so I'm not sure we should swap the agreement for Pop to Marvel. If Pop's TOS was different than Marvel's, someone (Betsy? Legal?) may need to review -- especially since it has [paid levels](https://marvelapp.com/plans/).

If we _can_ use this Marvel TOS, it will have to be renamed on the page as _[Marvel](https://marvelapp.com/) (formerly POP)_ and _[Marvel TOS](https://marvelapp.com/terms/) (online)_

> _Just for records, original:_
> 
> [POP](https://popapp.in/) 
> Prototyping on paper 
> [POP TOS](https://popapp.in/en/terms/government-users)  (online)

---
We created the bottom No Longer In Use section because people need to know which agreements ended, and why. True.. not all have a _why_ [and it could be worded better] ~ but that info always came from Betsy, if she had it. I believe the thinking was that if they just disappear, it would create confusion.

**Measured Voice** TOS page no longer exists, but homepage says that they've closed and provides contact email; it should be moved to 'No Longer In Use' at the bottom as: 

> [Measured Voice](http://www.measuredvoice.com/) is no longer in service. Please [contact them via email](info@measuredvoice.com) if you need further assistance.
> 
> Social media productivity tool	
> 
> [Measured Voice TOS](http://www.measuredvoice.com/terms/) (online)

---

The **(PDF)**'s should not be linked

**Comment by jeremyzilar** [comment]
This has been completed.
