### ISSUE TITLE
Add relevant resources to Multilingual Community page

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#260]
In the previous version of the site, we had links on the page to the best Mutlingual resources within DigitalGov.

Here is the old version: https://web.archive.org/web/20170704155625/https://www.digitalgov.gov/communities/government-multilingual-websites-community/

They did not look so great in the old version, but they were there. Now they are not.

We can easily add them back, but they will be a list of links to resources — not a feed from the `multilingual` tag page like before.

By making it a list of resources, we (or the community manager) will be able to hand-pick the resources/blog-posts/tools that are the most valuable for the community.

---

Here are the links that were there.

### Getting Started
- [Top 10 Best Practices for Multilingual Websites](https://www.digitalgov.gov/resources/top-10-best-practices-for-multilingual-websites/)
- [Agencias y Departamentos del Gobierno Federal](https://gobierno.usa.gov/agencias-federales/a)
- [Spanish Language Style Guide and Glossaries](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/)
- [Accessibility Editorial Guidelines for Videos](https://www.digitalgov.gov/2012/08/01/accessibility-editorial-guidelines-for-youtube/)
- [Lost in Translation](https://www.digitalgov.gov/2012/10/01/automated-translation-good-solution-or-not/)

### Featured Articles
- [A Guide to Publishing Multilingual Digital Content](https://www.digitalgov.gov/2014/07/01/multilingual-digital-content/)
- [Multiple Languages, Single Platforms: the World Digital Library](https://www.digitalgov.gov/2015/04/09/multiple-languages-single-platforms-the-world-digital-library/)
- [Trends on Tuesday: Hispanic Millennials Provide Insight on Mobile Future](https://www.digitalgov.gov/2014/05/27/trends-on-tuesday-hispanic-millennials-provide-insight-on-mobile-future/)
- [Persona Development Case Study: NCI and Spanish Language Outreach](https://www.digitalgov.gov/2015/03/02/persona-development-case-study-nci-and-spanish-language-outreach/)
- [More on Multilingual »](https://www.digitalgov.gov/tag/multilingual/)

**Comment by jeremyzilar** [comment]
The next step is to have Laura look over the links above and see if there are any other tools, resources, links, articles that she would like to link to. They don't have to be links to things on digitalgov.gov. 

Any links that are there, should the most valuable links for people in the multilingual community.

The current headings "Popular articles" and "Getting Started" can change. Maybe they can be one list? Maybe they should be grouped differently.

Let us know in the comments below 👇

**Comment by lggsa** [comment]
Hi Jeremy, 
I'll work on deciding which articles to link to later this week - the first part of the week is pretty full for me.  Would like to hear from others about which articles they find most useful, so I may consult a bit before making a decision.  Will get back to you in a few days with a list of best resources.  FYI, several of these resources were looked at and updated and what may seem common knowledge to other communities, in the multilingual world, we're still helping people make the case for multilingual pages or sites to a monolingual audience (their bosses), which may need very basic info.

**Comment by jeremyzilar** [comment]
@lggsa Great! There is no pressure to get it right the first time. You can just pick the best 3-4 articles or resources to link to, then we can add/remove/change it as we go. It will be really easy to update.

**Comment by lggsa** [comment]
Sounds good, thanks, Jeremy!

On Dec 10, 2017, at 11:57 PM, Jeremy Zilar <notifications@github.com> wrote:

@lggsa <https://github.com/lggsa> Great! There is no pressure to get it
right the first time. You can just pick the best 3-4 articles or resources
to link to, then we can add/remove/change it as we go. It will be really
easy to update.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GSA/digitalgov.gov/issues/260#issuecomment-350622660>,
or mute the thread

**Comment by jeremyzilar** [comment]
OK! 🎉 

I am going to update the page with these links:

### Getting Started
- [Top 10 Best Practices for Multilingual Websites](https://www.digitalgov.gov/resources/top-10-best-practices-for-multilingual-websites/)
- [Agencias y Departamentos del Gobierno Federal](https://gobierno.usa.gov/agencias-federales/a)
- [Spanish Language Style Guide and Glossaries](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/)
- [Accessibility Editorial Guidelines for Videos](https://www.digitalgov.gov/2012/08/01/accessibility-editorial-guidelines-for-youtube/)
- [Lost in Translation](https://www.digitalgov.gov/2012/10/01/automated-translation-good-solution-or-not/)

### Featured Articles
- [A Guide to Publishing Multilingual Digital Content](https://www.digitalgov.gov/2014/07/01/multilingual-digital-content/)
- [Multiple Languages, Single Platforms: the World Digital Library](https://www.digitalgov.gov/2015/04/09/multiple-languages-single-platforms-the-world-digital-library/)
- [Trends on Tuesday: Hispanic Millennials Provide Insight on Mobile Future](https://www.digitalgov.gov/2014/05/27/trends-on-tuesday-hispanic-millennials-provide-insight-on-mobile-future/)
- [Persona Development Case Study: NCI and Spanish Language Outreach](https://www.digitalgov.gov/2015/03/02/persona-development-case-study-nci-and-spanish-language-outreach/)
- [More on Multilingual »](https://www.digitalgov.gov/tag/multilingual/)

**Comment by lggsa** [comment]
Thanks, Jeremy!!




Laura Godfrey
Agency Partnerships and Multilingual Strategies Lead
Office of Products and Programs
Technology Transformation Services, GSA
202.536.8968

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
