### ISSUE TITLE
Add `governance` as topic to 2 resources

### ISSUE THREAD

**Issue by afeijoo** [GSA/digitalgov.gov#2633]
### URL / Link to page

* https://digital.gov/resources/2012-digital-government-strategy/
* [OMB-M-17-06 short post](https://github.com/GSA/digitalgov.gov/edit/master/content/resources/omb-m-17-06.md)

### Tell us how we can make this page better

M-17-06 (section 1) and the 2012 Digital Strategy require "every agency must establish a plan for governing its digital services." These two resources on Digital.gov should be tagged with `governance`.

Also note that https://digital.gov/resources/2012-digital-government-strategy-2/ appears to be a duplicate of https://digital.gov/resources/2012-digital-government-strategy/. One of the two should probably be removed.

**Comment by saracope** [comment]
Created a new issue for the duplicate pages
https://github.com/GSA/digitalgov.gov/issues/2648
