### ISSUE TITLE
Bug: "Skip to main content" link broken for several layouts

### ISSUE THREAD

**Issue by kingcomma** [GSA/digitalgov.gov#2642]
**Describe the bug**
The "Skip to main content" link points to `#main-content` but several layouts do not have an element with that ID attribute. This results in a non-functioning link and users must tab through the header content to navigate to the main content.

I have not done exhaustive testing, but so far only the [homepage](https://digital.gov/) appears to function properly.

**Steps to Reproduce**
Steps to reproduce the behavior (written for Chrome):
1. Go to https://digital.gov/2020/05/12/promote-continuity-better-support-customer-journeys/
2. Press `tab` to focus the "Skip to main content" link
3. Press `enter` or click the link
4. The URL updates to include #main-content but the user is not taken anywhere and focus remains on the skip link.

**Screenshots**
<img width="1110" alt="Screen Shot 2020-05-14 at 2 41 27 PM" src="https://user-images.githubusercontent.com/3246955/81972999-7b821100-95f1-11ea-8425-c61a1446b457.png">

**Comment by saracope** [comment]
Fixed in #2986
