### ISSUE TITLE
Mark article about Search.gov's old DNS as outdated

### ISSUE THREAD

**Issue by dawnpm** [GSA/digitalgov.gov#2677]
### URL / Link to page
https://digital.gov/2016/09/12/dnssec-vs-elastic-load-balancers-the-zone-apex-problem/

### Tell us how we can make this page better
As of a week ago, we no longer use the DNS solution mentioned in this article, and I'd like to indicate that somehow. Do you have a standard way of marking things as archived or superceded?

**Comment by saracope** [comment]
@dawnpm Are you wanting the entire article archived or just parts of it updated?

**Comment by dawnpm** [comment]
The whole thing - what do you all do with content that's archived?

**Comment by saracope** [comment]
@dawnpm Wondering if we can archive this entire [5-part series](https://digital.gov/2016/08/18/the-right-tools-for-the-job-re-hosting-digitalgov-search-to-a-dynamic-infrastructure-environment/?=dg):

- The Right Tools for the Job: Re-Hosting DigitalGov Search to a Dynamic Infrastructure Environment
- Quality, Speed, and Lower Costs: Yes, You Can Have It All
- A Domain by Any Other Name: CNAMES, Wildcard Records and Another Level of Indirection
- Let’s Encrypt those CNAMES, Shall We?
- DNSSEC vs. Elastic Load Balancers: the Zone Apex Problem


If anything is worth saving, we should review and update.

**Comment by dawnpm** [comment]
Hi Sarah, yes I think all this can be archived. Will the content be taken down, or marked as archived, or moved to a different folder?

There may be other articles on digital.gov from the search team that can be archived as well.

**Comment by saracope** [comment]
They will be marked as expired (in the page front matter) and will no longer be included in the production builds. The content location in the repository won't change.
