### ISSUE TITLE
Blog post URL ends with .md

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#276]
In updating Resource pages, came across this error

The URL for this page ends with .md 
https://www.digitalgov.gov/2014/12/08/from-taste-testers-to-explorers-developing-personas-for-open-opportunities.md/ 

It should be 
https://www.digitalgov.gov/2014/12/08/from-taste-testers-to-explorers-developing-personas-for-open-opportunities 
 ~ but I get the 404/Page Not Found

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾

**Comment by jeremyzilar** [comment]
The old URL should redirect to the new one.

**Comment by saracope** [comment]
Looks like this was fixed. Closing out.
