### ISSUE TITLE
Create and post monthly Inter-agency Federal Emerging Citizen Technologies meeting

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#287]
### Description of event:

GSA’s Emerging Citizen Technology program is hosting its new monthly meeting. This is an in-person and online meeting is for government employees only.

Second Wednesday of every month from 10:30am-12:00pm

first meeting: https://www.digitalgov.gov/event/interagency-federal-emerging-citizen-technologies-forum/

---

### Next Steps

- [ ] coordinate with Justin for blurb about monthly meetings
- [ ] create eventbrite registration pages
- [ ] create page on DG
- [ ] update eventbrite + event page on DG with specific location (since meetings will rotate at different agencies) 
- [ ] monitor registration to ensure federal employees only are registered (must register with a .gov or .mil email address)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
