### ISSUE TITLE
Bug: Fix the layout shift being caused by the top gov banner

### ISSUE THREAD

**Issue by saracope** [GSA/digitalgov.gov#2894]
**Describe the bug**
The gov banner loading on the page is causing a big [content layout shift](https://web.dev/cls) which is having a negative impact on usability.  It's contributing to a failing CLS core on [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=digital.gov&tab=desktop).  
 
[`Cumulative Layout Shift (CLS)  0.12`](https://github.com/GSA/digitalgov.gov/files/4886717/screencapture-developers-google-speed-pagespeed-insights-2020-07-07-15_06_40.pdf)

In Chrome devtools, we can see that the CLS is coming from the gov banner expanding then contracting.
<img width="1850" alt="Screen Shot 2020-07-07 at 3 07 35 PM" src="https://user-images.githubusercontent.com/2197515/86830718-074d7200-c064-11ea-95f3-b9ea8bcca0b3.png">

**Comment by DanielFlaum** [comment]
The gov banner appears on other sites (e.g. code.gov) and seems to use the same implementation. Does the gov banner have its own project? Will look around.

**Comment by DanielFlaum** [comment]
It looks like the gov banner is implemented using a https://designsystem.digital.gov/components/accordion/ (based on the `.usa-accordion` class in the markup on digital.gov). Its possible that a proper fix involves modifying how the accordion works. Its also possible that a proper fix involves not using the accordion and using some other technique instead.

**Comment by saracope** [comment]
We do implement the gov banner from [USWDS](https://designsystem.digital.gov/). You can see the implementation in [`themes/digital.gov/layouts/partials/core/usa-banner.html`](https://github.com/GSA/digitalgov.gov/blob/20556c6dd4fb8bc34887a47037577fc43b90748b/themes/digital.gov/layouts/partials/core/usa-banner.html). Everysite that uses the banner doesn't have this issue so I feel like it's something going on with our implementation and we _should_ be able to make a fix for it.

**Comment by DanielFlaum** [comment]
The files there are of USWDS 2.5.x, and `styles.scss` appears to have last been updated for USWDS 2.4.x. The current version is 2.9.x. Perhaps this is a bug that has been addressed in a newer version of USWDS, and upgrading will solve this issue?

**Comment by saracope** [comment]
@DanielFlaum Yeah, entirely possible!
