### ISSUE TITLE
Create a partial to display our Code of Conduct language

### ISSUE THREAD

**Issue by saracope** [GSA/digitalgov.gov#2927]
Feedback received from the community managers meeting indicated a need for a code of conduct.
Research pulling this language together and then creating a partial to include it in community pages.

**Comment by saracope** [comment]
We currently have the language added to each Community page individually. https://digital.gov/communities/a-b-testing-community/

This is still needed as a partial.

**Comment by Schultea** [comment]
New language to use for CoP page footer: 

The Communities of Practice are hosted by digital.gov, a service of the Technology Transformation Services (TTS) within the General Services Administration (GSA). GSA is a federal agency subject to the Freedom of Information Act (FOIA) and must comply with requests for records made under FOIA. As a result, all communications made on this Communities of Practice LISTSERV are subject to release under FOIA.

When participating in this CoP, follow [Digital.gov Community Guidelines](https://digital.gov/communities/manage-your-subscription/).
