### ISSUE TITLE
Event: Marketing-as-a-service promoting the Digital Partnership Toolkit 

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#300]
# Marketing-as-a-service promoting the Digital Partnership Toolkit

**Date:** Tuesday, March 27, 2018 2pm-3pm ET

**Summary** 

**Description** working description: 
https://docs.google.com/document/d/1RxhFaqxge4hMlZUIq6b5DtEu7fP3TIwWRV6b5oBsTSg/edit

---

- [x] 30min meeting w/ presenters (scheduled for 1/4/18)
- [x] Send calendar invite once event date has been determined
- [ ] Request video title card
- [ ] Create event in Eventbrite
- [ ] Create event in YouTube live
- [ ] Post event page on DigitalGov
- [ ] Schedule emails through Eventbrite (Iink to FedRelay)
- [ ] Schedule real time captioning through FedRelay (link to FedRelay)
- [ ] Identify moderator for live chat/online questions and send moderator script
- [ ] Schedule tech check with presenters to review online platform and logistics of event
- [ ] Work with DG team to promote via Social Media platforms
- [ ] Track registration and provide event partner weekly registration updates
- [ ] Set up evaluation in Google Forms(link to Google form)
- [ ] Update metrics spreadsheet
- [ ] Schedule post event/training retro
- [ ] Add title card immediately following event
- [ ] Send post-event email with link to video, evaluation, and any additional resources
- [ ] Share evaluation results with event partner and presenters
- [ ] Conduct retro

**Comment by jthalls** [comment]
First will be a recorded video and then a live video two weeks later

**Comment by thisisdano** [comment]
![marketing-as-a-service](https://user-images.githubusercontent.com/11464021/38383739-26704882-38c2-11e8-96f8-ef63ef761804.png)
