### ISSUE TITLE
Accommodation statement for Digital.gov event pages

### ISSUE THREAD

**Issue by Schultea** [GSA/digitalgov.gov#3108]
https://digital.gov/events/

- Adding an accommodation statement to Digital.gov event pages 

https://docs.google.com/document/d/1UWHvAsnAheJ-5NBTTQBAZxYKkDIs_Cp6v9hpbP1CcFY/edit

**Comment by saracope** [comment]
@Schultea Can this be closed?

**Comment by Schultea** [comment]
Looks like it never made it to our event pages. Could we add it until we move away from Eventbrite? 

If we could replicate the box below under the register button at the top of each page that could work. 
<img width="848" alt="A11Y" src="https://user-images.githubusercontent.com/44302460/95083631-c90b3180-06ea-11eb-9bcc-18561d8608b4.png">

<img width="769" alt="A11Y2" src="https://user-images.githubusercontent.com/44302460/95083875-15ef0800-06eb-11eb-9e18-d1d1930d3021.png">

**Comment by ToniBonittoGSA** [comment]
I'll have to hunt for that page template..

**Comment by saracope** [comment]
No. We already have a rather lengthy box under the registration button for the platform. So, this either needs to be incorporated into that or moved elsewhere.

<img width="1073" alt="Screen Shot 2020-10-05 at 9 36 09 AM" src="https://user-images.githubusercontent.com/2197515/95086225-3a98af00-06ee-11eb-9229-17be8f8dbd32.png">

**Comment by ToniBonittoGSA** [comment]
It can be the last line in that box.. in each event stage file (zoom, google, adobe connect)

**Comment by saracope** [comment]
Those are located in https://github.com/GSA/digitalgov.gov/tree/main/themes/digital.gov/layouts/events
