### ISSUE TITLE
[Netlify CMS] Support media filenames without extensions

### ISSUE THREAD

**Issue by hursey013** [GSA/digitalgov.gov#3170]
Reference:
https://community.netlify.com/t/is-it-possible-to-use-an-image-filename-as-the-slug-in-netlifycms/13865

Digital.gov is structured to read image filenames from frontmatter without a file extension. For example:
```
primary_image: "uswds-2-illio-feature-image"
```

When creating new posts, we use the media library widget (to allow choosing a photo) and a preSave hook to remove the extension from the file name when it's added to the frontmatter. The problem comes in when the post is later edited because the media library widget is expecting a filename with an extension, so we get a broken image preview:
![Screen Shot 2020-08-27 at 10 48 55 AM](https://user-images.githubusercontent.com/1178494/91457946-f5fa3800-e852-11ea-8ca9-64f5088f31df.png)

This won't actually affect the published post, but it's not a great editing experience since content editors may get confused and think the image is broken when it's really not.

Based on the community support link posted above, it may be possible to work around this issue by developing a custom widget.

**Comment by jeremyzilar** [comment]
Ha! looks like you are following all of the breadcrumbs here (hello friends 👋)

So if you look here in `/content/media/`, you will see that I made a "media" content type https://github.com/brooklynrail/brooklynrail-platform/tree/master/content/media/2020

This is not that different than what you have in the `/data/images/` folder: https://github.com/GSA/digitalgov.gov/tree/main/data/images

You could:
- move all of the image `.yml` files to a `/content/media/` folder
- put the `---` at the start and end of all these files
- then edit the gulp script to create future files in this DIR
- create "media" in your netlifyCMS
- media will be available as objects to reference when making a post/event page

Hope that helps
