### ISSUE TITLE
Gather a list of all the Mobile videos

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#326]
We need to:
- list all the mobile videos we've done
- pick the videos we'd like to include a mobile guide page

**Comment by SoncerrayBolling** [comment]
Link to list of videos in YT MobileGov playlist. There are 24 videos currently in the playlist and approximately 8-10 videos t/b added to the playlist.

https://docs.google.com/spreadsheets/d/16Xv_DxX_bBqCaAVwpeZ1IVNsjfyAxvH6naMid-QbHOs/edit?usp=sharing
