### ISSUE TITLE
Apply missing URL redirects from WordPress

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#334]
For various Pages, Events, and Posts -- and one shortcut/vanity URL (# 13): 

1. **Redirect**: /services/social-media-registry/
 **_To_**:  https://www.digitalgov.gov/services/u-s-digital-registry/ 
(done in https://github.com/GSA/digitalgov.gov/issues/363 )
(in https://github.com/GSA/digitalgov.gov/pull/412 )

2. **Redirect**: /services/the-federal-mobile-apps-registry/
 **_To_**:  https://www.digitalgov.gov/services/u-s-digital-registry/
(https://github.com/GSA/digitalgov.gov/pull/391 )
(in https://github.com/GSA/digitalgov.gov/pull/412 )

3. **Redirect**: /resources/dot-gov-domain-freeze-and-waivers/
 **_To_**:  https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/#dotgov-domain-freeze-update
(https://github.com/GSA/digitalgov.gov/pull/392 )

4. **Redirect**: /communities/web-managers-forum/web-content-managers-listserv/
 **_To_**:  https://www.digitalgov.gov/communities/manage-your-listserv-subscription/
(https://github.com/GSA/digitalgov.gov/pull/393 )

5. **Redirect**: /resources/digitalgov-user-experience-program/
 **_To_**:  https://www.digitalgov.gov/digitalgov-user-experience-resources/ (is now https://www.digitalgov.gov/resources/digitalgov-user-experience-resources/ )
(is https://github.com/GSA/digitalgov.gov/pull/414 )

6. **Redirect**: /2012/08/12/top-10-best-practices-for-multilingual-websites/
 **_To_**:  https://www.digitalgov.gov/resources/top-10-best-practices-for-multilingual-websites/ 
Already done

7. **Redirect**: /resources/federal-social-media-analytics-toolkit-hackpad/
 **_To_**:  https://www.digitalgov.gov/2013/04/19/social-media-metrics-for-federal-agencies/
(in https://github.com/GSA/digitalgov.gov/pull/415 )

8. **Redirect**: /resources/2012-digital-government-strategy-2/ (12/3/15)
 **_To_**:  https://www.digitalgov.gov/resources/2012-digital-government-strategy/ (9/29/15)

9. **Redirect**: /communities/digital-audio-video-community-of-practice/
 **_To_**:  https://www.digitalgov.gov/communities/video-production-pros-community-of-practice/ 
(in https://github.com/GSA/digitalgov.gov/pull/416 )

10. **Redirect**: /event/online-far-faqs-expert-answers-your-questions-on-running-competitions-in-line-with-law/
 **_To_**:  https://www.digitalgov.gov/event/online-far-faqs-contracting-expert-shares-best-practices-for-running-competitive-challenges/ 
Old event; not live (yet?)

11. **Redirect**: /2017/09/06/five-ways-federal-leaders-can-build-the-will-skill-and-velocity-needed-for-digital-transformation/
 **_To_**:  https://www.digitalgov.gov/2017/09/06/how-federal-leaders-can-build-the-will-skill-and-velocity-needed-for-digital-transformation/ 
(in https://github.com/GSA/digitalgov.gov/pull/417 )

12. **Redirect**: /2017/09/07/usdas-foodkeeper-app-update-features-food-safety-recall-information/
 **_To_**:  https://www.digitalgov.gov/2017/09/07/usda-foodkeeper-app-update-expands-content-offerings/
(in https://github.com/GSA/digitalgov.gov/pull/418 )

13. **Redirect**: /resources/checklist/
 **_To_**:  https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/ 
(in https://github.com/GSA/digitalgov.gov/pull/413 )

**Comment by ToniBonittoGSA** [comment]
For number 4:

1. Why was /communities/manage-your-listserv-subscription/ [title of page, good SEO] shortened to just /communities/manage-your-subscription/ ? this could be confused with our newsletter subscription page

2. Why is this old CoP page /communities/web-managers-forum/web-content-managers-listserv/ set to redirect to https://www.digitalgov.gov/communities/manage-your-listserv-subscription/ instead of the new CoP page https://www.digitalgov.gov/communities/web-content-managers/ ?

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Do you need help with this?

**Comment by jeremyzilar** [comment]
I will untangle this knot
