### ISSUE TITLE
Update post count on author page

### ISSUE THREAD

**Issue by saracope** [GSA/digitalgov.gov#3388]
When viewing an Author page, a post # is included for the items they have authored. This content pulled into the page includes posts and events so this number is confusing. See https://digital.gov/authors/dan-williams/. It shows 8 posts but 2 pages of total content. 

Fix:
Update the `posts` number to include all content authored by the contributor

<img width="1094" alt="Screen Shot 2020-10-27 at 9 54 32 PM" src="https://user-images.githubusercontent.com/2197515/97381334-40be1d80-189f-11eb-88dc-0076c76e0bfe.png">

**Comment by saracope** [comment]
Same on topic pages: https://digital.gov/topics/21st-century-idea/
Need to look at the partial generating these.

**Comment by jeremyzilar** [comment]
Wonderful! I meant to do that. Thank you!
