### ISSUE TITLE
Federal Social Media Accessibility Toolkit Hackpad (note, CoP update?)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#3406]
### Description
https://digital.gov/resources/federal-social-media-accessibility-toolkit-hackpad/ 
this was created by Justin Herman and SocialGov, 2014-ish. We sometimes get emails about outdated info or broken links

Should we 

1) add a note at the top saying the content was initially created in 2014, that some links may not work (and that the content is under review..?)
2) ask Gabbie P. if SocialGov CoP can take on content audit and update this?

**Comment by saracope** [comment]
Ask if the community wants to update it. If not, we can retire.

**Comment by seomanager63** [comment]
Ask if the community wants to update it.

**Comment by afeijoo** [comment]
The hackpage page has a lot of redudant content with the Improving the Accessibility of Social Media in Government toolkit at https://digital.gov/resources/improving-the-accessibility-of-social-media-in-government/. We could:
1. Archive the [hackpad](https://digital.gov/resources/federal-social-media-accessibility-toolkit-hackpad/) page.
2. Ask the community update the [toolkit](https://digital.gov/resources/improving-the-accessibility-of-social-media-in-government/). Or, alternatively, archive it too.
