### ISSUE TITLE
Broken link, missing file: Resources Checklist page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#341]
@jeremyzilar 

A user emailed us -- on https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/, the single link for **United States Government Works and Copyright Act of 1976** points to: https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/CDN/files/2014/01/United-States-government-works-and-copyright.doc but it does not work. 

I found this https://s3.amazonaws.com/digitalgov/_legacy-img/2014/01/United-States-government-works-and-copyright.doc via Google, but the .doc file extension is old; I saved with the newer .docx and attached file below: 

[United-States-government-works-and-copyright.docx](https://github.com/GSA/digitalgov.gov/files/1656627/United-States-government-works-and-copyright.docx)

**Comment by jeremyzilar** [comment]
I am looking into this.

**Comment by jeremyzilar** [comment]
Done. Here is the file @ToniBonittoGSA 
https://s3.amazonaws.com/digitalgov/_legacy-img/2014/01/United-States-government-works-and-copyright.docx

Can you replace it out in the document?
