### ISSUE TITLE
Bug: Number of Views (Lightning Bolt) Not Accurate

### ISSUE THREAD

**Issue by RhettSkelton** [GSA/digitalgov.gov#3411]
**Describe the bug**
Number of views on News items (next to the yellow lightning bolt) is only showing pageviews from clicks within the Digital.gov site. It does not count the total sessions or pageviews for the page for people coming from other referrals or links. This number should be hooked into our Google Analytics session numbers for the page.

**Steps to Reproduce**
1. Go to 'https://digital.gov/news/'
2. Click on 'any news item in the list'
3. Look at the left nav/column on the page under Authors.
4. See the yellow lightning bolt, number and "views"

**Screenshots**
N/A

**Comment by saracope** [comment]
@Krithisree Why did this get closed?

**Comment by Krithisree** [comment]
Hi Sara,

I was working on this bug, I think I accidentally closed it.

Thanks,
Krithika

**Comment by Krithisree** [comment]
@RhettSkelton , @saracope  I do not see the yellow lighting bolt with view numbers. Could you send me screenshot ?

**Comment by saracope** [comment]
Here is an example: https://digital.gov/2020/09/08/how-serving-in-government-made-me/
