### ISSUE TITLE
Share event page on Facebook + meta data

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#346]
I was going to share the new Events page https://www.digitalgov.gov/events/ to Facebook but noticed that title and summary are wrong. 

@jeremyzilar Can  
```
summary: ''
authors: 
featured_image: 
  uid: 
  alt: ''
```
be added to the Events page so that it overrides the meta info? It would seem so; works on Post pages when shared to FB (example: https://www.digitalgov.gov/2017/09/28/finding-usability-testers-tips-from-an-army-recruiter/ -- in FB, I just turn off the 2 extra images to get correct featured image to show)

**Comment by jeremyzilar** [comment]
This is a good question, and related to https://github.com/GSA/digitalgov.gov/issues/448.
I will likely fix this with that fix

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar it looks like everything but _authors_ was added.. which we may not need. 
Should this be marked done?

**Comment by jeremyzilar** [comment]
Nah,... this still needs to be fixed

**Comment by ToniBonittoGSA** [comment]
[Social media image size guides](https://sproutsocial.com/insights/social-media-image-sizes-guide/) (updated every 3-6 months)

DGU logo .png at 1200 x 628: 
![digitalgov_university 1200x628](https://user-images.githubusercontent.com/19961574/42571361-e9410afe-84e4-11e8-8979-0416a6e19db2.png)

---
For Facebook and Twitter, https://digital.gov/events/ should have: 
**title**: Events | DigitalGov
**description** [shorten if need be]: We provide a range of free online and in-person trainings and events for people and teams across the federal government, highlighting innovations, case studies, tools, and resources. All of our events are recorded and archived on YouTube. Trainings are open to anyone working in the government or for a government agency.
**image**: see above/below
**image alt**: DigitalGov University logo

---
In case you need.. the original DGU logo .png file from Ogilvy (2993 x 632): 
![digitalgov_university](https://user-images.githubusercontent.com/19961574/42571422-19cfef1e-84e5-11e8-8cd1-4413e8bed731.png)

**Comment by ToniBonittoGSA** [comment]
@thisisdano if you get a moment, can you upload the 1200 x 628 image in the comment above? (the rest is for @jeremyzilar ) 
Thank you!

**Comment by thisisdano** [comment]
@ToniBonittoGSA the image is uploaded and available now: https://digital.gov/images/

**Comment by ToniBonittoGSA** [comment]
Thanks!

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
