### ISSUE TITLE
Bug: mobile styles of touchpoints buttons

### ISSUE THREAD

**Issue by saracope** [GSA/digitalgov.gov#3463]
**Describe the bug**
These buttons needs some tweaks to better visually distinguish them. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2197515/101194791-72f43500-362c-11eb-8857-14f1fd6b526d.png)

**Comment by saracope** [comment]
@ryanwoldatwork I believe this needs to be addressed in Touchpoints by using a [USWDS button group](https://designsystem.digital.gov/components/button-groups/). 
I modified the code in Chrome Inspector and it seemed to fix the issue:
```
    <p class="usa-button-group submit-button">
    <input type="hidden" class="fba-touchpoints-page-form" name="answer_01" value="">
    <input type="submit" class="usa-button usa-button-group__item" value="yes">
    <input type="submit" class="usa-button usa-button-group__item" value="no">
  </p>
```
Is this a change you can make? Should I move this Issue to another repo?


<img width="1233" alt="Screen Shot 2020-12-04 at 2 04 02 PM" src="https://user-images.githubusercontent.com/2197515/101204370-1c8df300-363a-11eb-9638-1afdb128e4ee.png">

**Comment by ryanwoldatwork** [comment]
@saracope - I've noted this in the Touchpoints backlog.

**Comment by ryanwoldatwork** [comment]
![yes-no](https://user-images.githubusercontent.com/64987852/101235851-d8721100-3680-11eb-9e3b-b08cbde31022.png)

this has been fixed

**Comment by saracope** [comment]
Thanks!
