### ISSUE TITLE
Bug: Some images are broken on DG's Images page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#3579]
DG's images page: https://digital.gov/images/ 

The layout looks different; shaded box with ID, alt text, caption, etc. is below images now
Some of the images are not displaying on this page ~ example: 

<img width="1440" alt="Screen Shot 2021-01-29 at 10 55 01 AM" src="https://user-images.githubusercontent.com/19961574/106297579-d9f32c00-6220-11eb-997f-5455585ae350.png">

For these two, the images are showing on the blog post, https://digital.gov/2019/02/14/introducing-2019-presidential-innovation-fellows/ -- but is some sort of bug to not display on the Images page

**Comment by brunerae** [comment]
@ToniBonittoGSA it appears that this issue can be closed

**Comment by nick-mon1** [comment]
This will be refactored with a future card.
