### ISSUE TITLE
DG's feed is not displaying correcly

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#362]
https://www.digitalgov.gov/feed/ — this is the old WordPress FEED URL
https://digital.gov/feed/ — is also the old WordPress FEED URL

And the XML is not formatted correctly.

**Comment by jeremyzilar** [comment]
This can be fixed when we have a viable 301 redirect solution in place

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar just fyi ~ just got an email in the DG acct:

> Your RSS feed 
> 
> https://www.digitalgov.gov/feed/
> 
> generated obsolete URLs e.g.,
> 
> https://digitalgov.gov/2018/02/13/why-your-team-needs-its-own-style-guide-where-start/
> 
> which should be:
> 
> https://www.digitalgov.gov/2018/02/13/why-your-team-needs-its-own-style-guide-where-start/

I thanked them for writing and noted that we are aware of issues with the feed since migration and are working on them

**Comment by jeremyzilar** [comment]
We also have
https://digital.gov/index.xml which is an actual FEED XML file
