### ISSUE TITLE
code, filename typos for Peace Corps image

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#365]
For https://www.digitalgov.gov/2018/01/30/making-customer-satisfaction-data-actionable-at-peace-corps/ 

2 typos: "peacecore" and "capton"

```
featured_image:
  uid: peacecore
  alt: 'peacecore logo'
```

`{{< img-right src="peacecore" capton="" alt="" >}}
`

also in the image filename: https://s3.amazonaws.com/digitalgov/peacecore.jpg

**Comment by ToniBonittoGSA** [comment]
When this is updated, corrections will need to be made here https://www.digitalgov.gov/2018/01/30/making-customer-satisfaction-data-actionable-at-peace-corps/

**Comment by jeremyzilar** [comment]
Looking at this now @ToniBonittoGSA 🎉
