### ISSUE TITLE
Twitter image URLs have odd string in both new posts

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#366]
Is this string
> %!s(&lt;nil&gt;)

in the Twitter filenames a bug?

1) On https://www.digitalgov.gov/2018/01/30/making-customer-satisfaction-data-actionable-at-peace-corps/ 

Twitter image is set to: https://s3.amazonaws.com/digitalgov/peacecore%!s(&lt;nil&gt;).jpg
but should be: https://s3.amazonaws.com/digitalgov/peacecore.jpg

~ related Issue should be fixed first: https://github.com/GSA/digitalgov.gov/issues/365 

---
2) On https://www.digitalgov.gov/2018/01/30/updated-it-accessibility-standards/ 

Twitter image is set to: https://s3.amazonaws.com/digitalgov/508-refresh%!s(&lt;nil&gt;).jpg 
should be: https://s3.amazonaws.com/digitalgov/508-refresh.jpg

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar FYI: 

I tried adding to Facebook again, but no image appeared for the post. 
I added the URL to the Facebook Debugger to get it to recognize it (does; yay) -- but got 3 "warnings that should be fixed"
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.digitalgov.gov%2F2018%2F01%2F30%2Fmaking-customer-satisfaction-data-actionable-at-peace-corps%2F 

> **Extraneous properties specified**
> The following properties are specified on the webpage but NOT supported for the specified 'og:type': article:publisher, article:published_time
> 
> **Missing Properties**
> The following required properties are missing: fb:app_id
> 
> **Invalid OG URL**
> The given value '/2018/01/30/making-customer-satisfaction-data-actionable-at-peace-corps/' for property 'og:url' was not a valid absolute URL.

--- 

I also tried adding to Twitter on my account, but no image loaded ...  

<img width="465" alt="screen shot 2018-02-08 at 1 33 14 pm" src="https://user-images.githubusercontent.com/19961574/35991309-d4dd2ee0-0cd4-11e8-80d1-dc319adcdd1a.png">

Until I ran the URL thru: https://cards-dev.twitter.com/validator 

<img width="1005" alt="screen shot 2018-02-08 at 1 40 52 pm" src="https://user-images.githubusercontent.com/19961574/35991692-f8e049fc-0cd5-11e8-8f8c-dfd8f3934c49.png">

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
