### ISSUE TITLE
Bug: Broken Link

### ISSUE THREAD

**Issue by mgifford** [GSA/digitalgov.gov#3675]
**Describe the bug**
Broken Link in the Additional Resources section of https://digital.gov/resources/introduction-accessibility/

Accessibility How-to — A second DigitalGov playlist on YouTube 

This Playlist on Youtube does not exist
https://www.youtube.com/playlist?list=PLd9b-GuOJ3nH01BSXgJZv6uoCDJMyVvuT

**Comment by ToniBonittoGSA** [comment]
Looking into it, thanks!

**Comment by ToniBonittoGSA** [comment]
Fixing here https://github.com/GSA/digitalgov.gov/pull/3763
