### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/digitalgov.gov#3690]
**Checklist of Requirements for Federal Websites and Digital Services**

https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/

---

**Please describe the issue clearly. Include a screenshot if needed**

The link https://www.justice.gov/opcl/1974privacyact-overview.htm is invalid.

**Comment by ToniBonittoGSA** [comment]
Thanks
fixing here https://github.com/GSA/digitalgov.gov/pull/3765
