### ISSUE TITLE
Add an Open Data section to Req Content/Links page

### ISSUE THREAD

**Issue by RachelF** [GSA/digitalgov.gov#3714]
### Tell us how we can make this page better
While reviewing current federal web policy and guidance,  I realized that there are several required links/content related to open data that are not reflected on the "required content" page. This info is called out in [M-17-06 Section 4](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf).

Can we please create a new section on that page called "Open Data" and include the following info:

Agencies must provide:
- A continually updated Data Publication Process at [agency].gov/digitalstrategy.
- A machine-readable Public Data Listing at [agency].gov/data.json in accordance with the Project Open Data metadata schema.
- A human-readable Public Data Listing at [agency].gov/data.
- A public two-way feedback mechanism available via www.[agency].gov/data.
- Existing and new web APIs and relevant open source documentation at www.[agency].gov/developer.

**Comment by ToniBonittoGSA** [comment]
Hi @RachelF 

What would you like us to put in the highlighted gray/silver section? see https://digital.gov/resources/required-web-content-and-links/ 

> Suggested link text: 
> 
> 
> Required on: 
> 
> 
> Required by:
> 
>

**Comment by RachelF** [comment]
Oops, sorry, forgot that part! Thanks - here's my rec:

Suggested link text: Data Publication Process 
Required on: [agency].gov/digitalstrategy

Suggested link text: Machine-Readable Public Data Listing
Required on: [agency].gov/data.json

Suggested link text: View [agency] datasets
Suggested link text: [List contact info for the agency's Chief Data Officer, Chief Statistical Officer, and Chief Evaluation Officer.]
Required on: [agency].gov/data

Suggested link text: APIs and open source documentation
Required on: [agency].gov/developer.

Required by: [OMB M-17-06, Policies for Federal Agency Public Websites and Digital Services](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf) (PDF, 1.2 MB, 18 pages, November 2016)
