### ISSUE TITLE
Bug: https://guidelines.usability.gov/

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#3754]
**Describe the bug**
Broken Link - Usability.gov Guidelines (not found)

**Steps to Reproduce**
1. Go to 'https://www.usability.gov/'
2. Click on 'Guidelines'
3. See error

**Comment by ToniBonittoGSA** [comment]
We don't have the right platform to take this subdomain live; is on hold.

**Comment by saracope** [comment]
This is already listed on the usability.gov repo. Closing out.
