### ISSUE TITLE
Bug: Broken link / 404 Error within https://digital.gov/2013/06/26/making-multimedia-section-508-compliant-and-accessible/

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#3756]
**Broken Link**
Within https://digital.gov/2013/06/26/making-multimedia-section-508-compliant-and-accessible/ there is a link that is creating a 404 error message: https://digital.gov/2013/11/21/create-section-508-compliant-videos-on-your-government-websites-2/

**Steps to Reproduce**
1. Go to 'https://digital.gov/2013/06/26/making-multimedia-section-508-compliant-and-accessible/'
2. Click on 'Create Section 508-Compliant Videos on Your Government Websites: https://digital.gov/2013/11/21/create-section-508-compliant-videos-on-your-government-websites-2/'
3. See error: 404

Possibly add the following link instead: https://digital.gov/2014/06/30/508-accessible-videos-why-and-how-to-make-them/

**Comment by ToniBonittoGSA** [comment]
Fixed https://github.com/GSA/digitalgov.gov/pull/3757
