### ISSUE TITLE
Bug: Broken link (404 Error) Security is Everyone’s Responsibility: Delivering Secure, Usable Login for Government

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#3773]
**Describe the bug**
Link out to, "To begin to understand IAL2, we created a user flow that shows all of the paths the user may take in order to get verified (GitHub PDF).", is broken
**Steps to Reproduce**
1. Go to 'https://digital.gov/2021/03/02/security-is-everyones-job-delivering-secure-usable-login-for-government/'
2. Click on ' we created a user flow that shows all of the paths the user may take in order to get verified, https://github.com/18F/identity-design-assets/blob/master/Projects/Identity/IAL2%20Flowchart/IAL2_Flowchart.pdf'
3. See error

**Comment by Gabr1elleKING** [comment]
Flagging. Email from 3/17 from a member of the public agency employee to the DG inbox about this page: https://www.digital.gov/2021/03/02/security-is-everyones-job-delivering-secure-usable-login-for-government/
The error/problem is broken link under the “Creating user flows for IAL2” subhead that should show a user flow on Git Hub

**Comment by saracope** [comment]
Fixed by #3786
