### ISSUE TITLE
Bug: Deck text in front matter is replacing Summary text

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#3782]
**Describe the bug**
Sometime this week, the deck code in the front matter started to replace the summary code -- for both blog posts, and event pages. 
** Here, "deck" is the subtitle or intro line on an individual blog or event page; not a "presentation deck."

Two examples:

1. **Chatbots blog post** 

**LIVE: I had to remove the deck from the front matter so that the summary will display -- which means then deck can't be used on blog page**

<img width="1148" alt="deck issue - DG hp live" src="https://user-images.githubusercontent.com/19961574/114087710-35294680-9882-11eb-9aa7-0fcc115cfe4c.png">

**PREVIEW: both deck and summary are in front matter ([closed PR](https://github.com/GSA/digitalgov.gov/pull/3780)), but the deck text appears where the summary should be on the homepage (_note_: the summary text is also the copy shown in social media shares)**

<img width="1145" alt="deck issue - DG hp PREVIEW" src="https://user-images.githubusercontent.com/19961574/114087704-3490b000-9882-11eb-8912-31627a5040f7.png">

---

2. **Challenge/NIST 4/21 event**: On the live Events listing page https://digital.gov/events/ the deck text is here instead of the summary text (below). 

**Events list page** the deck line is showing on the 4/21 event instead of the summary that's coded in the front matter.

<img width="1133" alt="Screen Shot 2021-04-08 at 3 58 21 PM" src="https://user-images.githubusercontent.com/19961574/114089192-d8c72680-9883-11eb-9597-c1c6f451fcae.png">

**4/21 Event page** deck appears, as it should, below the title.

<img width="1141" alt="Screen Shot 2021-04-08 at 3 58 28 PM" src="https://user-images.githubusercontent.com/19961574/114089188-d82e9000-9883-11eb-9117-1b57a611935d.png">

**front matter code, shows summary text that should be on the Events list page**

<img width="1319" alt="Screen Shot 2021-04-08 at 3 58 39 PM" src="https://user-images.githubusercontent.com/19961574/114089184-d795f980-9883-11eb-91ba-73fb2822fd5f.png">

**Comment by saracope** [comment]
I looked at the code for the event layouts:

If an event has a deck then that is shown on the events list page. If no deck, then the summary is shown. 
The summary is not shown on the individual event page.

Added this info to the wiki:
https://github.com/GSA/digitalgov.gov/wiki/Event-Content-Type
