### ISSUE TITLE
Issue: Feature request; Non-PDF Files

### ISSUE THREAD

**Issue by mara-goldberg** [GSA/digitalgov.gov#3791]
**Is your feature request related to a problem? Please describe.**
At this moment it seems we are only able to upload PDFs to the platform, no other file types (i.e. PowerPoint slides or anything from Google Drive). The problem with this is when presenters send us accessible slides in non-PDF format, we have to convert them to PDFs, which in turn diminishes the accessibility.

**Describe the solution you'd like**
We would like to be able to upload and post the original accessible slides (as PPT, etc.) to our event pages.

**Comment by saracope** [comment]
Added a static folder for files and updated the `Adding PDFs` page in the wiki to `Uploading Files`. 
https://github.com/GSA/digitalgov.gov/wiki/Uploading-Files
