### ISSUE TITLE
Bug:  Privacy-Preserving Collaboration Using Cryptography Resource

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#3821]
**Describe the bug**
The link to the 2017 the Report of the U.S. Commission on Evidence-Based Policymaking is broken.

**Steps to Reproduce**
1. Go to 'https://digital.gov/resources/privacy-preserving-collaboration-using-cryptography/'
2. Click on '2017 the Report of the U.S. Commission on Evidence-Based Policymaking'
3. Error, https://www.cep.gov/cep-final-report.html (site can't be reached)

**Comment by afeijoo** [comment]
Fixed link in https://github.com/GSA/digitalgov.gov/pull/4899
