### ISSUE TITLE
Bug: Host an Event Button Redirect Link

### ISSUE THREAD

**Issue by lchidlow** [GSA/digitalgov.gov#3854]
**Describe the bug**
The "Host an Event" button links are redirecting to the "Contribute to Digital.gov" page. 

**Steps to Reproduce**
1. Go to Digital.gov
2. Scroll down to News and Event section
3. Click on "Host an Event" button
3. This takes you to the "Contribute to Digital.gov" page instead of the "Digital.gov/digitalgov-university/" page (which we may want to rename)
4. This button also exists on Digital.gov/news/  and Digital.gov/Events/ pages

**Screenshots**

**Comment by saracope** [comment]
These 'host an event' buttons should be removed as we don't accept events from outside our communities anyway.

**Comment by afeijoo** [comment]
@nick-mon1 Please remove the buttons on Digital.gov, /news, and /events.
