### ISSUE TITLE
Update" the  about page on Digital.gov to reflect personnel changes.

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#3887]
### Tell us how we can make this page better
Update the Our Team Section by removing Sara, adding Ammie, adding Mara, adding Laurie

Digital.gov: Sara Cope, Toni Bonitto
Communities: Jacob Parcell
Video and Events: Alexandar Schulte, Gabrielle Fratanduono
U.S. Web Design System: Dan Williams

**Comment by Gabr1elleKING** [comment]
Let me know what you think @ToniBonittoGSA and I can make the updates if you'd like :)

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/digitalgov.gov/pull/4020
