### ISSUE TITLE
broken link to performance.gov/cx

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/digitalgov.gov#3895]
page: https://digital.gov/resources/customer-experience-toolkit/
link: http://www.performance.gov/clear_goals?page=1&stra_goal=1&prio_goal=0&fed_goal=0&goal_type=ASG
link text: Agency Strategic Goals – Performance.gov

**Comment by ToniBonittoGSA** [comment]
thanks; that's now https://obamaadministration.archives.performance.gov/clear_goals.1.html 
will add PR

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/digitalgov.gov/pull/3913
