### ISSUE TITLE
[Content Cleanup] for GUIDE TO THE DIGITAL ANALYTICS PROGRAM  Overview

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#4025]
### There is a typo on the page
"Have a questions for the DAP team? Send an email to dap@support.digitalgov.gov and we’ll get back to you."
Update to, "Have a question...." or, "Have questions...."

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/*/digitalgov.gov

**Comment by ToniBonittoGSA** [comment]
same on https://digital.gov/guides/dap/common-questions-about-dap/ 

fixes: 
https://github.com/GSA/digitalgov.gov/pull/4044 
https://github.com/GSA/digitalgov.gov/pull/4045
