### ISSUE TITLE
Add Web Analytics Playbook to resources

### ISSUE THREAD

**Issue by RachelF** [GSA/digitalgov.gov#4029]
**Metrics**
https://digital.gov//topics/metrics/

---

Please add a link to https://digital.gov/guides/web-analytics-playbook/ to https://digital.gov//topics/metrics/.
Also add as first link on https://digital.gov/resources/#metrics
Also add somewhere on https://digital.gov/guides/dap/
(It's very hard to find this guide!)

**Comment by Schultea** [comment]
Using https://github.com/GSA/digitalgov.gov/pull/4102
