### ISSUE TITLE
"Past Events" list error(s)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#423]
1) When you click the "View past events" button at the end of https://www.digitalgov.gov/events/ 
you get some of the old events (11), and all of the upcoming events (14), a 2nd time, below that: 

An Around the World Recap PLAIN Monthly Meeting
October 11, 2017 2:00 PM - 3:00 PM ET
Event details

DAP Learning Series – Visualizing Analytics Data Part 2
October 12, 2017 2:00 PM - 3:00 PM ET
Event details

Connect with your Spanish-language audience on Social Media
October 24, 2017 2:00 PM - 3:00 PM ET
Event details

FedRAMP Tailored: Overview of the Finalized New Baseline
November 15, 2017 1:00 PM - 2:00 PM ET
Event details

Workshop: Making Government Websites with GitHub, Federalist & U.S. Web Design Standards
December 12, 2017 9:00 AM - 12:00 PM ET
Event details

Inter-agency Federal Emerging Citizen Technologies Forum
December 13, 2017 10:30 AM - 12:00 PM ET
Event details

Responding to a Disaster: How USAGov Helped Shape the Digital Response in Puerto Rico
January 09, 2018 12:00 PM - 12:30 PM ET
Event details

U.S. Digital Registry Open Office Hours
January 10, 2018 10:00 AM - 10:30 AM ET
Event details

January PLAIN Monthly Meeting
January 10, 2018 2:00 PM - 3:00 PM ET
Event details

How to Better Serve Your LEP Audience by Meeting the Federal Requirements
January 18, 2018 2:00 PM - 3:00 PM ET
Event details

U.S. Web Design Standards Monthly Users Call
January 26, 2018 1:00 PM - 1:30 PM ET
Event details

Customer Relationship Management - Government Sector Best Practices, Pitfalls and Tips
**February 13, 2018** 10:00 AM - 12:00 PM ET
Event details

U.S. Digital Registry Open Office Hours
February 14, 2018 10:00 AM - 10:30 AM ET
Event details

Plain Language Community Meeting
February 14, 2018 2:00 PM - 3:30 PM ET
Event details

DAP Learning Series: An Introduction to the Basics
February 15, 2018 1:00 PM - 4:00 PM ET
Event details

Federal Challenge & Prize Community of Practice Quarterly Meeting
February 27, 2018 9:00 AM - 12:00 PM ET
Event details

New Release of FedRAMP Continuous Monitoring Documents
March 13, 2018 1:00 PM - 2:00 PM ET
Event details

DAP Learning Series: A Deep Dive into Analytics Events
March 22, 2018 2:00 PM - 3:00 PM ET
Event details

DAP Learning Series: Creating Your Own Campaign URL builder
April 18, 2018 3:00 PM - 4:00 PM ET
Event details

DAP Learning Series: Advanced Concepts
May 23, 2018 1:00 PM - 4:00 PM ET
Event details

DAP Learning Series: Using the Search Console
June 07, 2018 2:00 PM - 3:00 PM ET
Event details

DAP Learning Series: Analytics and Accessibility
July 18, 2018 2:00 PM - 3:00 PM ET
Event details

DAP Learning Series: An Introduction to the Basics
August 15, 2018 1:00 PM - 4:00 PM ET
Event details

DAP Learning Series: Writing Custom Javascript for Tag Managers
September 20, 2018 2:00 PM - 3:00 PM ET
Event details

DAP Learning Series: Creating Goals and Conversions
**October 17, 2018** 2:00 PM - 3:00 PM ET
Event details

_(**emphasis** mine)_

2) There is no way to close/collapse that list -- can a button for that be added as well?

**Comment by jeremyzilar** [comment]
This is a bug with the events loop that I wrote. I am working on this now.
