### ISSUE TITLE
Preview tab not working in new pages/PRs

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#426]
After making new posts in https://demo.digitalgov.gov/new-post/ the preview tab in GitHub doesn't work until **_after_** the PR is created, but is needed here, too
(preview tab is fine in Issues)

<img width="1166" alt="screen shot 2018-02-13 at 7 34 53 am" src="https://user-images.githubusercontent.com/19961574/36150194-e06482da-1090-11e8-9e39-2b63aa4f92e9.png">

**Comment by jeremyzilar** [comment]
This is a GitHub Issue and I am not sure that there is a whole lot we can do here.
