### ISSUE TITLE
Event page didn't clear yesterday's past event

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#429]
https://www.digitalgov.gov/events/  
Dan, not sure if this is related to the Issue entered yesterday; https://github.com/GSA/digitalgov.gov/issues/423 

<img width="1280" alt="screen shot 2018-02-14 at 11 24 02 am" src="https://user-images.githubusercontent.com/19961574/36215273-a207b4a0-1179-11e8-91e7-c3c9d8056353.png">

**Comment by jeremyzilar** [comment]
I can look at this now

**Comment by jeremyzilar** [comment]
I am curious — since we are on a static site, there is nothing running or building that would remove an event from the listing.

So I am triggering a build to see if that removes it.

**Comment by jeremyzilar** [comment]
And I am sure it will... which makes me winder if we should ask the Federalist team to see if they can implement a feature that would auto-build `MASTER` once a day or even every 12hrs.

**Comment by jeremyzilar** [comment]
Another possible solution to this would be to write a bit of javascript to hide events that are stale. But this would not be ideal, as there might be multiple places where event listings appear on the site.

**Comment by jeremyzilar** [comment]
OK, so Federalist will not be able to implement this feature at this time...
We'll need to add a Javascript feature that will remove past events from listings.

**Comment by ToniBonittoGSA** [comment]
gracias!

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar just fyi: yesterday's is still up

**Comment by jeremyzilar** [comment]
Thank you @ToniBonittoGSA !
So yes, at the moment, we'll have to log in to Federalist and manually restart the build for `master`.
I just did that. The site will rebuild, and the old event will not be surfaced.

The federalist team is going to work on something that will re-build the site on a regular basis.

**Comment by jthalls** [comment]
@jeremyzilar @ToniBonittoGSA is there a way to also remove the registration button and the add to calendar button once an event has taken place?

**Comment by jeremyzilar** [comment]
@jthalls That is a great idea! Yes, of course. Can you add a new issue about that?

**Comment by jthalls** [comment]
@jeremyzilar yes, just did 👍
