### ISSUE TITLE
Images & edits for style guide post

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#430]
Apologies, that 2nd image on [Why Your Team Needs Its Own Style Guide and Where to Start](https://www.digitalgov.gov/2018/02/13/why-your-team-needs-its-own-style-guide-where-start/) wasn’t named correctly.

---

1) **Delete** the first/top image here:
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/new-post-why-your-team-needs-its-own-style-guidewhere-start/images/ 
 ~ file: ustpo-ui-design-gallery-primary-ui-color-swatches.png 

---
### this is just the _Featured Image_; _not_ used in/with the post copy

2) **Add**: CFPB-secondary-color-palette-swatches.png
alt, caption: `CFPB Design Manuel: [Secondary Colors Palette](https://cfpb.github.io/design-manual/brand-guidelines/color-principles.html).`

<img width="872" alt="cfpb-secondary-color-palette-swatches" src="https://user-images.githubusercontent.com/19961574/36221395-f0d67df2-118b-11e8-97ce-0cbf2bbb65dd.png">

---
### this is supposed to be the 2nd image in the post

3) **Add**: USPTO UI Design Gallery Primary UI color swatches.png

file: uspto-ui-design-gallery-primary-ui-color-swatches.png
uid: uspto-ui-design-gallery-primary-ui-color-swatches
attribution:
caption: `USPTO UI Design Library: 10 [Primary UI colors](https://uspto.github.io/designpatterns/1.x/docs/foundation/colors.html)`
alt: USPTO UI Design Library: 10 Primary UI colors

`{{< img src="uspto-ui-design-gallery-primary-ui-color-swatches" caption="USPTO UI Design Library: 10 [Primary UI colors](https://uspto.github.io/designpatterns/1.x/docs/foundation/colors.html)" alt="USPTO UI Design Library: 10 Primary UI colors" >}}`

`{{< img-right src="uspto-ui-design-gallery-primary-ui-color-swatches" caption="USPTO UI Design Library: 10 [Primary UI colors](https://uspto.github.io/designpatterns/1.x/docs/foundation/colors.html)" alt="USPTO UI Design Library: 10 Primary UI colors" >}}`

<img width="987" alt="uspto ui design gallery primary ui color swatches" src="https://user-images.githubusercontent.com/19961574/36221458-26850216-118c-11e8-97ac-3d13686f58af.png">

---

4) **Update** 2 images on https://www.digitalgov.gov/2018/02/13/why-your-team-needs-its-own-style-guide-where-start/ 
 a - featured image will need to be: CFPB-secondary-color-palette-swatches.png (number 2 above)
 b - 2nd content image will need to be: USPTO UI Design Gallery Primary UI color swatches.png (number 3 above)

---

5) **Fix typo** in "Reduce, Reuse, Remix:" bullet; the link text on: "US**TP**O UI Design Gallery" should be US**PT**O UI Design Gallery

**Comment by jeremyzilar** [comment]
So 1 and 2 is the same image, but different filename and caption?

**Comment by ToniBonittoGSA** [comment]
yeah, somehow I named it the wrong thing

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
