### ISSUE TITLE
FB OG image not working in new post

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#432]
[Why Your Team Needs Its Own Style Guide and Where to Start](https://www.digitalgov.gov/2018/02/13/why-your-team-needs-its-own-style-guide-where-start/) 

This is in the code:

> `<meta property="og:image" content="https://s3.amazonaws.com/digitalgov/ustpo-ui-design-gallery-primary-ui-color-swatches_w1200.png" />`

and [the image works](https://s3.amazonaws.com/digitalgov/ustpo-ui-design-gallery-primary-ui-color-swatches_w1200.png), **_but_**, when I try to add the post to Facebook, I only get: 

<img width="1280" alt="screen shot 2018-02-14 at 12 11 49 pm" src="https://user-images.githubusercontent.com/19961574/36222494-74fa0e02-118f-11e8-89ca-f9df127fe8c2.png">

Also, when I put the post URL in the [FB Debugger](https://developers.facebook.com/tools/debug/), it still doesn't recognize/scrape the image and I get 4 error warnings: 
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.digitalgov.gov%2F2018%2F02%2F13%2Fwhy-your-team-needs-its-own-style-guide-where-start%2F 

![screen shot 2018-02-14 at 2 15 26 pm 2](https://user-images.githubusercontent.com/19961574/36223225-b96f56da-1191-11e8-8b45-447fd123dc4f.png)

**Comment by jeremyzilar** [comment]
This has been fixed.
