### ISSUE TITLE
New Blog Post: Go-Live Checklist for Federal Websites

### ISSUE THREAD

**Issue by RachelF** [GSA/digitalgov.gov#4404]
@ToniBonittoGSA THANK YOU for posting the checklist! This issue is to submit the content for the related checklist blog.
I'm out of the office 12/6-17, back 12/20, so if you have any questions on this, please just tag me here and I'll respond upon my return. Thank you!

**What is this post about? 1-2 sentence summary:**
A checklist to help federal agencies understand and meet federal policy requirements for websites and digital services.

**Expected publish date:**
Before the end of December

**Google Docs URL:**
https://docs.google.com/document/d/1IQ9bdvR5huevFtfPW9NcCT22vkzxHvRZ00T-vN2PPIo/edit#

**Images (updated 12/22)**
image is attached 
![web checklist_1200x630](https://user-images.githubusercontent.com/2413403/147110699-dc93536b-569f-4f65-a8a9-68beaa5d8e91.png)

@afeijoo FYI here's the blog to accompany the checklist.
Thanks!

**Comment by RachelF** [comment]
OSC may provide a different image for this but I haven't received it yet. If they do, I'll attach here.

**Comment by ToniBonittoGSA** [comment]
Hey @RachelF -- so glad to get that one up :-) 
Thanks for adding this -- yes, a different image would probably work better, plus, for accessibility, we try to not use images that have a lot of text. Will keep an eye on this one

**Comment by ToniBonittoGSA** [comment]
Hi @RachelF I will be out 12/20 - 12/31. If you get another image, pls post it in DG's Slack channel (with link to this page) so someone can take a look. Pls have them make the dimensions: 1200 x 630. Thank you!
cc: @lchidlow @jarahameador @afeijoo

**Comment by RachelF** [comment]
@ToniBonittoGSA Thanks, just posted to slack

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/digitalgov.gov/pull/4526
