### ISSUE TITLE
Help Search Engines Help You: How SEO-Friendly... 

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#4522]
### Received this feedback from the Digital.gov inbox on 12/7/2022 from us tax courts

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/20160607193515/https://www.digitalgov.gov/2016/06/03/help-search-engines-to-help-you-how-seo-friendly-url-structure-can-boost-your-rankings/

**Comment by ToniBonittoGSA** [comment]
Updated Wayback Machine URL
