### ISSUE TITLE
[Suggestion] Note that the mobile testing program has been discontinued

### ISSUE THREAD

**Issue by jkreft-usgs** [GSA/digitalgov.gov#4572]
### URL / Link to page
https://github.com/GSA/digitalgov.gov/blob/main/content/services/service_mobile-testing-program.md

https://digital.gov/services/mobile-application-testing-program/

### Tell us how we can make this page better

I was just told that this program was discontinued after I followed the links to inquire about it.  It would probably be good to note that on the page as well

**Comment by ToniBonittoGSA** [comment]
> This page is still describing the mobile testing program as a real thing.

This is connected to other updates that we were able to start working on last week; I will clear this when it's completed
~ thanks for adding and checking in on it!

**Comment by ToniBonittoGSA** [comment]
Our standard Alert added to top of page until redirects can be added.
