### ISSUE TITLE
Content Suggestion: Update DG Resource Page - Sample Position Descriptions for Dig Gov Jobs 

### ISSUE THREAD

**Issue by Gabr1elleKING** [GSA/digitalgov.gov#4637]
### Provided positive feedback and attached recent job postings for Digital vacancies at NGA that were recently filled. Offered 4 samples (included in email) that can go on the page. 

(Docs look good + most content seems about 10 years old)

**Comment by NaingLinnKyaw** [comment]
> ### [URL / Link to page](https://digital.gov/resources/sample-position-descriptions-for-digital-government-jobs/)
> ### "Email on Feb 23rd from a National Gallery of Art (NGA) employee to the DG inbox about this page: https://digital.gov/resources/sample-position-descriptions-for-digital-government-jobs/
> ### Provided positive feedback and attached recent job postings for Digital vacancies at NGA that were recently filled. Offered 4 samples (included in email) that can go on the page.
> (Docs look good + most content seems about 10 years old)
gave me help

**Comment by NaingLinnKyaw** [comment]
gave me help
