### ISSUE TITLE
Fix event page "add to calendar" button settings

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#465]
## Fix so that "add to calendar" button doesn't autofill with the text on the page. 

Update the calendar description to include:
- [x] summary from the event page file
- [x] link to the DG event page
- [x] YT Live link (when online only)

Update the calendar location to include:
- [ ] autofill the location to say "Online" for online-only events (most are YouTube, but some are not)
- [ ] autofill the location to say "In-person" or name/address of location for in-person-only events

## it's done when …
- [ ] the "add to calendar" button auto generator includes the above improvements

**Comment by jeremyzilar** [comment]
Working on this now....

**Comment by jeremyzilar** [comment]
@jthalls 

I was not able to modify the `location` field to include ONLINE or IN-PERSON because we are using an off-the-shelf script to make the add to cal button.

Everything else has been fixed.
