### ISSUE TITLE
Remove "register" and "add to calendar button" for past event pages

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#466]
## Remove "register" and "add to calendar button" once an event has past
- [x] create formula (?) to remove the register button 
- [x] create formula (?) remove  the add to calendar button 

## it's done when …
- [x] an event takes place and the next day those two buttons are removed on the event page.

**Comment by jeremyzilar** [comment]
This is being worked on here: https://github.com/GSA/digitalgov.gov/pull/490

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
