### ISSUE TITLE
fix outdated link

### ISSUE THREAD

**Issue by RachelF** [GSA/digitalgov.gov#4717]
**Content Management Systems Toolkit**
https://digital.gov//2013/10/30/content-management-systems-toolkit/

---

Under "Choose a CMS / Open Source CMS in Government"

Update the paragraph to read:
Many federal agencies already use open-source content management systems, and if you’re considering it for your agency, GSA offers a secure and compliant self-service content management platform, [Federalist/cloud.gov Pages](https://federalist.18f.gov/), available for all federal agencies as a shared service. This is a great, cost-effective solution to help your agency move to open-source.

**Comment by ToniBonittoGSA** [comment]
https://github.com/GSA/digitalgov.gov/pull/5638
