### ISSUE TITLE
wireframe top-level resource page

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#473]
## it should include …
- [ ] a range of ideas for how to layout a top-level resource page

## possible ideas
- Video playlist
- SME contact info
- relevant communities
- related posts/links
- tools

## it's done when …
- [ ] there are 3 separate ideas to look at and discuss

**Comment by ToniBonittoGSA** [comment]
Maybe have room for an icon/graphic on each page for visual cues, grouping
