### ISSUE TITLE
bug: broken links

### ISSUE THREAD

**Issue by Schultea** [GSA/digitalgov.gov#4909]
**Describe the bug**
I noticed a broken link on "https://digital.gov/open-data-policy-m-13-13/". The link "View M13-13: Open Data Policy" [https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2013/m-13-13.pdf] returns a 404.

**Steps to Reproduce**
1. Go to https://digital.gov/open-data-policy-m-13-13/
2. Click on View M13-13: Open Data Policy

**Comment by ToniBonittoGSA** [comment]
Fixed
