### ISSUE TITLE
Determine which Sections of the Style Guide we'll need for the MVP

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#492]
## it should include …
- [x] a list of the sections that we need as part of the MVP (see https://github.com/GSA/digitalgov.gov/issues/484)
- [x] a plan for how to write for them and update them

## it's done when …
- [x] we have determined how this work will get done
- [x] when there is a deadline set for doing this work

**Comment by thisisdano** [comment]
Good advice here: https://content-guide.18f.gov/style-guides/

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
