### ISSUE TITLE
Grey Screen error on YouTube LIVE

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#494]
There is a bug in **YouTube LIVE** where when we invite a person to join as a presenter for a live streaming event using a google hangouts on air link, they are faced with a grey overlay on their screen that they cannot remove.

This happens infrequently and introduces a considerable amount of risk to our live video operation because it can strike right as an event is going live. It only happens with people who are not managers on our YouTube account. 

When the bug does strike, it surfaces right as one of our guests joins our broadcast. They click to 'join' the broadcast, then a gray overlay appears across their whole screen with the error message —  `“this person isn’t in your circle”`. Unfortunately, there is no way for the user or the channel admin to remove this screen.

The only way to we've managed to get around this is to make this person a manager on our standard YouTube channel. Once they are made a manager of our YouTube channel, this error goes away.

Again, this happens infrequently, and introduces a considerable amount of risk to our live video operation. For example: Before an event, we’ll do a tech check with the 3-4 people who’ll be live streaming, and everything appears to be working fine. Then on the day of the event (usually moments before we go live), there is a 20% chance that the gray overlay will appear on one of the presenters screens. 

Because we receive the error `“this person isn’t in your circle”` As an organization, we do not have access to Google+, thus we cannot add people to our circles.

**Steps to repeat this bug**
1. Create a live event (quick event type using google hangouts on air) in YouTube
2. We click ‘start hangout on air” 
3. Get the link to send to participants
4. Send the ‘hangout on air’ link to the participants (via email/Slack). 
5. Ask everyone to join the event.
6. 20% chance that someone (who is not a manager of our account) has this bug.

---

**Related**
- YouTube page: http://youtube.com/digitalgov

**Comment by jthalls** [comment]
I tested with several GSA folks now. @JacquelineSnee got the message several times when she joined about "DigitalGov isn't in your circles, join anyway?" When she clicked ok, there wasn't a gray overlay. She took a screenshot so adding it here.

**Comment by jthalls** [comment]
![yt live message](https://user-images.githubusercontent.com/9658310/37060611-d4e18960-215e-11e8-9609-8312b5f25169.png)

**Comment by jeremyzilar** [comment]
@jthalls can you get a larger screenshot? A full-screen shot?

**Comment by jthalls** [comment]
![screen shot 2018-03-07 at 12 55 41 pm](https://user-images.githubusercontent.com/9658310/37109243-660da84e-2207-11e8-9648-676fe93aea3f.png)

**Comment by jthalls** [comment]
@jeremyzilar same error message.

**Comment by jthalls** [comment]
<img width="1234" alt="screen shot 2018-03-15 at 1 05 28 pm" src="https://user-images.githubusercontent.com/9658310/37490276-8bd29e4e-2870-11e8-940e-4e9ebf3293d9.png">

@jeremyzilar encountered another gray overlay issue. Screen shot above from the user who had the error. A couple of notes about this:
-person was joining with a personal gmail account
-when there is a gray overlay, there is no option to even just unmute them to speak.

**Comment by jeremyzilar** [comment]
This has been FIXED 🎉👾
