### ISSUE TITLE
Add event audience when producing a new event page

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#497]
## it should include …
- [ ] add a field on https://www.digitalgov.gov/new-event/ to include "Intended Audience"
- [ ] options to include: 
- Federal employees only (with a .gov or .mil email)
- Federal employees and federal contractors (with a .gov or .mil email)
- US Government employees-only (federal, tribal, state, local)
- Government employees-only (federal, tribal, state, local, international)
- Community of Practice Members

## it's done when …
- [ ] the event generator is updated

**Comment by jeremyzilar** [comment]
@jthalls Should this also be output on the event page?

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar @jthalls 
Between date line and Register button?
With an icon so it stands out? Maybe one of these -- 

 - http://www.thinkstockphotos.com/image/stock-illustration-group-of-people-vector-icon-persons/825091664 

 - http://www.thinkstockphotos.com/image/stock-illustration-people-icon/690462912 

 - http://www.thinkstockphotos.com/image/stock-illustration-people-icon/919318556 

(which reminds me.. we should develop/standardize icons as design moves fwd)

**Comment by jthalls** [comment]
@jeremyzilar @ToniBonittoGSA I really like that idea to add an icon at the top so it stands out. And the simpler the language next to the icon, the better :)

**Comment by jthalls** [comment]
@ToniBonittoGSA I think we should add something to the option "Federal employees and federal contractors." We should maybe include the following since there are a lot of federal contractors who aren't embedded at agencies (or who have a federal badge)

Federal employees and federal contractors with a .gov or .mil email

Maybe there is a better way to say that though?

**Comment by ToniBonittoGSA** [comment]
@jthalls I like that

Federal employees and federal contractors (with a .gov or .mil email)
