### ISSUE TITLE
Add FAQs to bottom of in-person event pages

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#500]
## it should include …
- [ ] creating and editing DGU In-person FAQ document: https://docs.google.com/document/d/1-qFS3XlmV71uIb15gt72-lHAxvMGpjWFZTvi6UorSUg/edit?usp=sharing

## it's done when …
- [ ] start adding the reviewed FAQ doc to event pages

**Comment by jeremyzilar** [comment]
@jthalls Can we do this well in advance of the next `in-person` event?

**Comment by jeremyzilar** [comment]
This is not all that different than the work we did here https://github.com/GSA/digitalgov.gov/pull/2338
Quite easy to do once we have text we agree upon

**Comment by saracope** [comment]
Added a comment to the doc asking @Gabr1elleKING and/or @RhettSkelton to review the text for inclusion.
