### ISSUE TITLE
Update text for Resources search box

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#502]
The word "Search" is on the [Resources page](https://www.digitalgov.gov/resources/) 4 times; 3 in close proximity. Synonyms/alternate phrases can be used. 

## it should include … 
- [ ] "search" placeholder text is changed to "Enter keywords"
- [ ] "Search Resources:" to "Find Resources:"

## question ... 
Would "Find Resources:" look good if made bold?

<img width="1163" alt="screen shot 2018-03-12 at 11 04 54 am" src="https://user-images.githubusercontent.com/19961574/37291858-f752c8d4-25e5-11e8-8dfe-01c114db30e1.png">

## it's done when … 
- [ ] the above things are updated

**Comment by jeremyzilar** [comment]
Good catch @ToniBonittoGSA !

Maybe the "Search Resources:" can be removed all together. I will take a look at this

**Comment by jeremyzilar** [comment]
That will be fixed in the new site on https://demo.digital.gov/ 👍
