### ISSUE TITLE
Past event showing in current event feed

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#511]
## it should include …
- [ ] fixing why an event from yesterday (3/14) is showing in the upcoming event feed today (3/15). Event is: https://www.digitalgov.gov/event/infographics-plain-language-considerations/

## it's done when …
- [ ] A past event doesn't show in the feed the day after the event

**Comment by jeremyzilar** [comment]
This cannot be fully fixed at this time. 
The work around is to trigger a new build of the site in the morning, after the event.

As a temporary fix, I thought about javascript hide the event from listing if it is stale, but it will not put the event in the old events listing. I worry that the day after the event, people will be looking for the link to the thing they missed, or attended. In short, I'd rather not hide the event. We should fix this right.
