### ISSUE TITLE
Community Page: APIs

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#521]
## the community page should include …
- [x] **A brief description** of the community — with a focus on telling readers what problems the community aims to help people overcome
- [x]  **Who is the community manager?**
- [x] **How to join** the community — including any rules, requirements or expectations for joining

## good to haves
- [x] a plan to spread the news about the community across social media
- [ ] an announcement sent to GSA Comms (OSC) in advance

## nice to haves
- [ ] **a 2-3 min video** or blog post announcing the community — (talk to @jthalls about the video)
- [x] OR a 30-min online, YouTube live event _(scheduled through DigitalGov)_ to kick off the community and give an overview of the core concepts and problems the community aims to help people overcome
- [ ] OR a playlist of excellent, curated YouTube videos on your topic (http://youtube.com/digitalgov)

## it's done when …
- [x] there is a new page on digitalgov.gov
- [ ] it has been promoted

🎉

**Comment by gbinal** [comment]
Description: This community of practice for anyone who is interested in government APIs and developer outreach, with a focus on the federal government.  APIs are as important to digital government as they are are esoteric and sometimes difficult to understand.  This forum exists to help federal agencies share news, ask for help, and expand the use of APIs in government.  
Community Manager: Gray Brooks, GSA
How to Join: Join the [group mailing list](https://groups.google.com/forum/?nomobile=true#!forum/us-government-apis). The mailing list is open to anyone, in or out of government.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
