### ISSUE TITLE
Is it possible to add a universal "prefix" to the Feedback mailto subject?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#528]
Is it possible to code the subject on the 

> Send us an email >>

link at the end of every page to begin with **Feedback:** or **Site Feedback:** so that they can be filtered into their own folder our email client? If so, anyone on the team can easily find them all in one spot in the DG email account. 

Not urgent; just would be really nice to have for better email organization. (maybe we need a **Wish List** label?)

## it should include …
- [ ] an edit to code to make that happen

## it's done when …
- [ ] code is added
- [ ] testing the link works

**Comment by jeremyzilar** [comment]
Looking at this now.

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA What about this as an email?

```
Subject:
Feedback: [PAGE TITLE]
Body:

[enter feedback/questions here]

We value your feedback and open questions. They help us to make our pages better.
-----
[PAGE TITLE]
[PAGE URL]
#digitalgov_feedback
```

**Comment by jeremyzilar** [comment]
See this link: https://github.com/GSA/digitalgov.gov/pull/532

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
