### ISSUE TITLE
Bug: Broken link to ccPlayer

### ISSUE THREAD

**Issue by lchidlow** [GSA/digitalgov.gov#5295]
This page contains an incorrect link: https://digital.gov/2014/06/30/508-accessible-videos-use-a-508-compliant-video-player/ 

(508 Accessible Videos – Use a 508-Compliant Video Player) 

In the section, Embedded vs. Stand-Alone Video Players under 1. Browser Embedded Players, the link to ccPlayer goes to WGBH (a Boston radio station).   https://www.wgbh.org/ 

I believe the correct link is: https://www.microsoft.com/en-us/p/ccplayer/9wzdncrfjljx?activetab=pivot:overviewtab

**Comment by ToniBonittoGSA** [comment]
The WGBH domain is right; the original URL http://ncam.wgbh.org/invent_build/web_multimedia/tools-guidelines/ccplayer redirects to the homepage. 

I can't tell if their **cc**Player (which still has info here http://ncamftp.wgbh.org/ncam-old-site/invent_build/web_multimedia/tools-guidelines/ccplayer.html) was acquired by Microsoft (it styles theirs as **CC**Player).
There's also a "CC Player" from a third entity.. 

Will have to look into it a bit more
