### ISSUE TITLE
Add "Add This" social share icons to Pages & Events

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#531]
## it should include …
- [ ] Options to share the page via social media, like on Posts ([example](https://www.digitalgov.gov/2018/03/07/redesigning-an-intranet-site-final-stages-launch-lessons-learned/))

## it's done when …
- [ ] Add This is added to all other page types below the title

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
