### ISSUE TITLE
Properly attribute Zint Barcode Generator

### ISSUE THREAD

**Issue by fulldecent** [GSA/digitalgov.gov#5323]
**Describe the bug**
The page https://digital.gov/2013/02/14/qr-codes/ inaccurately attributed development of the Zint Barcode Generator project to SourceForge. Actually SourceForge is just the website that hosts it.

Recommend to reach out on https://sourceforge.net/p/zint/mailman/ introduce yourself and ask how they would like to be attributed.

**Steps to Reproduce**
1. Load page
1. It's wrong

**Screenshots**

<img width="1136" alt="Screen Shot 2022-09-04 at 13 25 39" src="https://user-images.githubusercontent.com/382183/188325822-47e492a4-234a-4dc6-a9c8-9f571f6fdb9b.png">

**Comment by ToniBonittoGSA** [comment]
Thank you for submitting this issue.
https://github.com/GSA/digitalgov.gov/pull/5637
