### ISSUE TITLE
Social media errors in code for 4/2 post

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#540]
@jeremyzilar For the new post that just went up, [New USAGov Program Aims to Help Agencies Market Within the Federal Government](https://www.digitalgov.gov/2018/04/02/marketing-government-through-agency-partnerships/) (Related: https://github.com/GSA/digitalgov.gov/pull/538)

1) Facebook:
The og image is missing, and the wrong title and summary are displaying when I try to share it in Facebook. 
Add https://www.digitalgov.gov/2018/04/02/marketing-government-through-agency-partnerships/ to the FB Debugger https://developers.facebook.com/tools/debug/ to see errors.

2) Twitter: 
Title & summary are correct, but the wrong image is attached in Twitter. 
Add https://www.digitalgov.gov/2018/04/02/marketing-government-through-agency-partnerships/ to the Twitter Card Validator: https://cards-dev.twitter.com/validator to see error.

Fixed when: 

 - Both use this image: https://s3.amazonaws.com/digitalgov/usagov-marketing_w600.png 
 - Title for both Facebook and Twitter is: New USAGov Program Aims to Help Agencies Market Within the Federal Government
 - Description for both Facebook and Twitter is: The Outreach and Marketing team from USAGov helps agencies amplify their key messages through a variety of channels.

**Comment by jeremyzilar** [comment]
looking at this... 👁

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Here are some observations — 

#### Twitter image + Featured Image
The **Featured image** in the front-matter is the same image that gets used on the Homepage of digitalgov.gov and in the `og:image` url. That is currently set to the USAGov logo image: https://s3.amazonaws.com/digitalgov/featured-usagov-logo-new-2017.jpg
If you would like, we can change it to https://s3.amazonaws.com/digitalgov/usagov-marketing_w600.png.

#### Twitter Cards
These appear to be loading fine, with no errors.
If you would like, we can change the featured image in the blog post.

#### Facebook Cards
Looks like Facebook is picking up the `meta` information about the page from the canonical URL we put in the page, which is the USAGov url. And they currently do not have the right `og:` tags set up on their page. When we copy over whole blog posts, we need to use the canonical URL in the `<head>` of our our pages. This will improve SEO for our site and USAGov.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar 

Twitter
Yes, the title and summary and title for Twitter were fine, I was just concerned about the image size ~ the Featured Image ends up stretched and fuzzy. Yes, if you can change it to https://s3.amazonaws.com/digitalgov/usagov-marketing_w600.png that'd be great. 

Facebook
Hmm, that is most unfortunate.. I will find out who can make those corrections on their end; they may need it across the board.

**Comment by jeremyzilar** [comment]
This is done.
