### ISSUE TITLE
Broken Link - Language Data by Region -->src="https://lang-map.mla.org/"

### ISSUE THREAD

**Issue by DCruz-FS** [GSA/digitalgov.gov#5410]
**Multilingual Digital Content**
https://digital.gov//2014/07/01/multilingual-digital-content/

---

**Please describe the issue clearly. Include a screenshot if needed**

I discovered that you have a broken link on this page for the:

 [Language Data by Region](http://arcgis.mla.org/mla/)—The Modern Language Association has created a language map that shows where speakers of 33 languages live in the United States.

The correct link is src="[https://lang-map.mla.org/]"
![Screenshot 2022-09-27 102146-Digital gov-Broken Link-LanguageDataByRegion](https://user-images.githubusercontent.com/114434473/192595631-e9efe5f4-741d-479a-bb49-765ba3acee59.png)

**Comment by ToniBonittoGSA** [comment]
Thank you, @DCruz-FS 
Fixing in https://github.com/GSA/digitalgov.gov/pull/5412
