### ISSUE TITLE
Typo in Feedback box

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#551]
## it should include …
- [x] Typo correction on the word _questions_: Have feedback or questsions about this page?

## it's done when …
- [x] it reads: Have feedback or questions about this page?

---
Feedback form was used to submit:
> There is a typo in your feedback request at bottom of page.  Please change "Have feedback or questsions about this page?"​ to "Have feedback or questions about this page?"
> 
> - - - - - 
> Page: Resources 
> URL: https://www.digitalgov.gov/resources/

**Comment by jeremyzilar** [comment]
😲😭

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
