### ISSUE TITLE
Update DAP email address

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/digitalgov.gov#5581]
replace all instances of `dap@support.digitalgov.gov` with `dap@gsa.gov`

### Background

Per the DAP team on 2022-11-14:

> As of today, GSA DAP has turned off [dap@support.digitalgov.gov](mailto:dap@support.digitalgov.gov). Please update your email and contact us going forward at our current email address -- [dap@gsa.gov](mailto:dap@gsa.gov).

**Comment by ToniBonittoGSA** [comment]
thx, updated
