### ISSUE TITLE
Measure how long readers are watching video on digitalgov

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#561]
## The problem we're trying to solve

**From @jthalls —**

> I'm still trying to get a better grasp on understanding the analytics from [our] events. Is there something that can tell us that they were watching a video embedded on a page? What I'm trying to understand is if people are in fact watching the video on the page or going and watching on YT

## How we're going to try solving it

**From @tdlowden —**

> We have an option in DAP which allows you to see if people clicked an embedded youtube video and the how much of the video they watched. Not sure how it works with YT live but worth a try.

> We'd have to make a small tweak to the DAP `<script>` on digitalgov.gov to test it

```
<!-- DAP — Digital Analytics Program | Learn more: https://digitalgov.gov/dap/ -->
 <script language="javascript" id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?ver=true&agency=GSA&*yt=true*"></script>
```

**Comment by jeremyzilar** [comment]
I would likely insert this in the footer _(with all the other JS includes)_ if the `youtube_id` data is present in the page. At the moment, this only appears on event pages.

**Comment by tdlowden** [comment]
@jeremyzilar just be careful with the `<script>` you copied above. I added asterisks in Slack around `&yt=true` for emphasis only. The script you'll want to use is:

```<!-- DAP — Digital Analytics Program | Learn more: https://digitalgov.gov/dap/ -->
 <script language="javascript" id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?ver=true&agency=GSA&yt=true"></script>```

**Comment by jeremyzilar** [comment]
@tdlowden should the `&yt=true` parameter be applied on all the pages, or only the ones where there is a YouTube video embedded?

**Comment by tdlowden** [comment]
All is fine, that way you don't have to find a way to make it dynamic. Won't hurt anything to be on all pages, regardless of YT vid presence.

**Comment by jeremyzilar** [comment]
We still need to check that this is added into Google Tag manager. From the looks of it, it is not.
