### ISSUE TITLE
Bug: Broken links in https://s3.amazonaws.com/digitalgov/static/10-2021-checklist-for-federal-websites-and-digital-services.xlsx

### ISSUE THREAD

**Issue by fulldecent** [GSA/digitalgov.gov#5640]
**Describe the bug**
This file https://s3.amazonaws.com/digitalgov/static/10-2021-checklist-for-federal-websites-and-digital-services.xlsx

Referenced by https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/?dg

Includes broken links, including this one: https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2010/m10-23.pdf

**Comment by fulldecent** [comment]
Issue is still applicable

**Comment by mejiaj** [comment]
@fulldecent, thanks for creating the issue. Do you have a list of replacement links?

**Comment by fulldecent** [comment]
For this link I found https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf

**Comment by ToniBonittoGSA** [comment]
Thank you.. 
This Checklist spreadsheet is currently being updated by the content owner; we expect to publish the new version in late July or August.
