### ISSUE TITLE
redirect to www is missing on DG sub-pages

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#576]
A user wrote the DG email account ~ the redirect on https://digitalgov.gov/ to https://www.digitalgov.gov/ works fine, but not on sub-pages, like: 

https://digitalgov.gov/about/ 
https://digitalgov.gov/resources/ 

they get a 404

(@jeremyzilar if there's a better title for this Issue, feel free to change)

**Comment by jeremyzilar** [comment]
This should be fixed today.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
