### ISSUE TITLE
Implement USWDS breadcrumb

### ISSUE THREAD

**Issue by mejiaj** [GSA/digitalgov.gov#5805]
We should create a breadcrumb component that uses [USWDS breadcrumb](https://designsystem.digital.gov/components/breadcrumb).

This will allow us to:

- Create a partial for a single component (instead of per template)
- Improve accessibility
- Improve maintainability (single place to update)
- Simplify template HTML

https://github.com/GSA/digitalgov.gov/blob/f931e82d5b9b1773388c467cc25b747d669922da/themes/digital.gov/layouts/resources/single.html#L7-L14

**Comment by nick-mon1** [comment]
Closed by #6057
