### ISSUE TITLE
Feedback box with Edit button missing from all Author pages

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#581]
It is missing from: 
- main page https://www.digitalgov.gov/authors/ 
- all individual pages, like https://www.digitalgov.gov/authors/jparcell/ 

## it should include …
- [ ] a Feedback Box with Edit button at the end of the page; [example](https://www.digitalgov.gov/services/search/). 

## it's done when …
- [ ] it has been added to all "Authors" pages

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
