### ISSUE TITLE
Fix migration error - broken table code and image alignment

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#5818]
For https://digital.gov/2014/08/18/how-to-choose-a-user-experience-technique/ 

1) Fix table code
2) Fix image alignment
3) Remove image link

Pre-migration reference: https://web.archive.org/web/20170629051659/https://www.digitalgov.gov/2014/08/18/how-to-choose-a-user-experience-technique/ 

Submitted via PR, https://github.com/GSA/digitalgov.gov/pull/5814

**Comment by nick-mon1** [comment]
@ToniBonittoGSA Fix for image alignment is here https://github.com/GSA/digitalgov.gov/pull/6263

**Comment by ToniBonittoGSA** [comment]
This was fixed in March; forgot to close.
