### ISSUE TITLE
Revisit use of hugo function "shuffle"

### ISSUE THREAD

**Issue by drewbo** [GSA/digitalgov.gov#5831]
There are ~2 places where the [`shuffle` function is used in the site build](https://github.com/GSA/digitalgov.gov/search?q=shuffle). Because this function can create new output with no changed input, it's a source of slower builds/prevents caching content for the whole site. Each use can possibly be changed to create a similar effect without suffering the drawbacks of slower builds:
- Sometimes the `shuffle` function is used to select a light/dark placeholder avatar for authors. Instead of shuffling, we could choose light/dark based on the even/odd parity of the place in the array. This results in deterministic behavior and a potentially pleasing visual effect. (example of current behavior: https://digital.gov/authors/)
- The function is also used to show related [communities and services on posts](https://github.com/GSA/digitalgov.gov/blob/6e024ca60ac054bc8cbfdaa5e1e6884b17b5143c/themes/digital.gov/layouts/partials/core/get_related.html#L16). The function works well as written when there are more than five related options, but if there are fewer, we shuffle the data for no reason (since all of the options will be shown). When there are five or fewer related items, we could "return early" from this function and get deterministic builds with similar visual results

Would love to hear what others think about this potential improvement cc: @mejiaj

**Comment by mejiaj** [comment]
@drewbo thanks for creating the issue. I've added it to our internal backlog!

**Comment by drewbo** [comment]
@mejiaj Proposed solution on this branch: https://github.com/drewbo/digitalgov.gov/tree/db-no-shuffle
