### ISSUE TITLE
Resources CMS page update via feedback email

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#587]
5/4/18: 

> ---enter your feedback/questions here---
> 
> Good Morning,
> 
> I am very pleased to share and announce that, as of April 18, 2018 – CFTC is no longer using Stellent!
> 
> We are managing all CFTC public websites in Drupal 8; provided as a software as a service (SaaS) in the Acquia Cloud environment.
> 
> CFTC.gov:  https://www.cftc.gov 
> 
> SmartCheck.gov:  https://www.smartcheck.gov 
> 
> Whistleblower.gov:  https://www.whistleblower.gov 
> 
>  
> 
> Would you please update the “CMS Used by Government Agencies” page with this updated information?
> 
>  
> 
> Thank you in advance,
> 
> ===
> 
> LaSharn Dozier
> IT Project Manager
> Office of Data and Technology
> U.S. Commodity Futures Trading Commission
> 
> 
> - - - - - 
> Page: Content Management Systems Used by Government Agencies 
> URL: https://www.digital.gov/resources/content-management-systems-used-by-government-agencies/ 
> - - - - -

## it's done when …
- [ ] the 3 websites are updated on the CMS page

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
