### ISSUE TITLE
Bug: "Join community" buttons not working

### ISSUE THREAD

**Issue by juliaklindpaintner** [GSA/digitalgov.gov#5897]
**Describe the bug**
'Mailto' links in call to action buttons to join communities of practice aren't working.
Bug seems to be a problem across all community pages.

**Steps to Reproduce**
1. Go to 'https://digital.gov/communities/plain-language/'
2. Click on '[Join 2,031 Plain Language community members'
3. Nothing happens

**Comment by nick-mon1** [comment]
Marking as done
