### ISSUE TITLE
Additional Resources to Link To

### ISSUE THREAD

**Issue by CM805** [GSA/digitalgov.gov#5955]
**Style Guides by Government Agencies**
https://digital.gov//resources/style-guides-by-government-agencies/

---

**Please describe the issue clearly. Include a screenshot if needed**

Hi,

I'd like to recommend that a link to the [GPO Style Manual](https://www.govinfo.gov/collection/gpo-style-manual?path=/GPO/U.S.%20Government%20Publishing%20Office%20Style%20Manual) be added to this page.

Additionally, BIA has a great [Indian Affairs Web Standards](https://www.bia.gov/page/indian-affairs-web-standards) page that includes style and content guides (I am not with BIA; not sure if you need their approval).

**Comment by nick-mon1** [comment]
@CM805 Thanks for adding your suggestion, prioritizing this issue with our team.
