### ISSUE TITLE
page with broken links - User Experience Program Speaking Opportunities

### ISSUE THREAD

**Issue by jthalls** [GSA/digitalgov.gov#598]
https://digital.gov/resources/digitalgov-user-experience-resources/digitalgov-user-experience-program-speaking-opportunities/

Not sure if this page should even exist since the program doesn't exist. If it should, there are several broken slide share links and YouTube video links

**Comment by saracope** [comment]
Follow-up with current UX CoP leads to see if this page should be updated or retired.
