### ISSUE TITLE
Dead link on Social Media Accessibility Toolkit Hackpad

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#609]
## it should include … 
On https://digital.gov/resources/federal-social-media-accessibility-toolkit-hackpad/ the one link to Disability.gov is broken. According to [Wikipedia](https://en.wikipedia.org/wiki/Disability.gov), the site was sunset December 2016:

> Disability.gov and its associated social media accounts were sunset in December 2016 and are no longer available. Disability.gov currently redirects to a page of disability related-resources available from the U.S. Department of Labor's Office of Disability Employment Policy (ODEP). Federal resources on disability and employment can be found on the website of the Campaign for Disability Employment (CDE) at https://www.whatcanyoudocampaign.org/index.php 

**But**, the redirect no longer works.

## it's done when …
found the ODEP site, https://www.dol.gov/odep/ -- but there isn't one "Resources" section (and Wikipedia person neglected to include a link on 'a page of disability related-resources')

Should we just link to https://www.dol.gov/odep/ ?

**Comment by saracope** [comment]
@ToniBonittoGSA will have a look at this.

**Comment by saracope** [comment]
@ToniBonittoGSA Any updates?
