### ISSUE TITLE
broken links in API blog post

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#627]
I recently stumbled upon your API Resources page (https://digital.gov/2013/03/12/resources-and-tools-for-apis/) and found a few broken links. 

The broken links I found included:
the link to "SBA" which links to: https://www.sba.gov/about-sba/sba-performance/sba-data-store/web-service-api
the link to "Department of Labor SDKs" that links to: https://digitalgov.sites.usa.gov/2012/11/19/case-study-how-dol-created-software-development-kits-sdks/
"API release kit" which links to: https://digitalgov.sites.usa.gov/2013/05/16/api-release-kit/

**Comment by kellermack** [comment]
So for the SBA link, I feel like the SBA link on the API resource page should be the following URL 

https://www.sba.gov/about-sba/sba-performance/open-government/digital-sba/open-data/open-data-sources

**Comment by kellermack** [comment]
And if you look at Line 412 for the source code on the API resource page you will find the a href link that should be replaced

view-source:https://digital.gov/2013/03/12/resources-and-tools-for-apis/    thats the url for that

**Comment by saracope** [comment]
Mine this page for current resources and add them to the API topic.
