### ISSUE TITLE
Explore using GitHub Issues as a way to leave a comment on a page

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#63]
Explore using GitHub Issues as a way to leave a comment on a page
One Issue per page

---

### [Slack AMA Connect Standards Team with Public](https://www.digitalgov.gov/2017/09/25/slack-ama-connects-standards-team-with-public/)
Published **September 25, 2017**

- - -

Authors
- @donjo
- @msecret
- @yowill
- @rtwell
- @toolness

- - -

✏️✏️✏️✏️✏️✏️✏️✏️✏️✏️ 
Use this issue to discuss the article. 
Edits and corrections can be posted here or filed as their own issues. [View this post in Github](https://github.com/GSA/digitalgov.gov/blob/master/content/posts/2017/09/2017-09-18-slack-ama-connect-standards-team-with-public.md)

**Comment by thisisdano** [comment]
Testing comments

**Comment by jeremyzilar** [comment]
Hmmm, this is interesting. So there would be a button at the bottom of the article sending people here?

**Comment by jeremyzilar** [comment]
@thisisdano I like this idea

**Comment by thisisdano** [comment]
Commenting again.

**Comment by thisisdano** [comment]
@ToniBonittoGSA Hey!

**Comment by ToniBonittoGSA** [comment]
test comment

**Comment by ToniBonittoGSA** [comment]
@thisisdano howdy!

**Comment by jeremyzilar** [comment]
What about GitHub permissions?
What if I am not part of this repo? Can I still comment?

**Comment by thisisdano** [comment]
![giphy](https://user-images.githubusercontent.com/11464021/31095736-ba87cf08-a76e-11e7-876b-4123d5edd223.gif)

**Comment by jthalls** [comment]
@thisisdano that is a pretty good gif!

**Comment by ToniBonittoGSA** [comment]
- [ grgrbrgb] 

- [45323467 ]

**Comment by jeremyzilar** [comment]
Why does @jthalls name have a `collaborator` label, when mine is `member`?

**Comment by ToniBonittoGSA** [comment]
read

**Comment by jeremyzilar** [comment]
Testing @ToniBonittoGSA as a `read` level.
She cannot edit people's comments anymore...

**Comment by ToniBonittoGSA** [comment]
write

**Comment by jeremyzilar** [comment]
Testing @ToniBonittoGSA as a write level.
She can edit people's comments...

**Comment by gbinal** [comment]
Test comment

**Comment by jeremyzilar** [comment]
Thanks @gbinal

**Comment by maya** [comment]
Testing this

**Comment by jeremyzilar** [comment]
Wondering if comments are open to anyone with a GitHub account

**Comment by jeremyzilar** [comment]
Taking a look at this guide: https://guides.github.com/features/issues/

**Comment by thisisdano** [comment]
I'm 99.999999999% sure they are

**Comment by jeremyzilar** [comment]
wild

**Comment by jeremyzilar** [comment]
Still a wild idea.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
