### ISSUE TITLE
connect.digital.gov is not working

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#635]
Both https://connect.digital.gov/ and https://connect.digitalgov.gov/ do not go to the Newsletter Signup page, and they should.

## it's done when …
- [ ] https://connect.digital.gov/ is working.

**Comment by jeremyzilar** [comment]
It is working on https://connect.digitalgov.gov/subscribe
I am looking at making it work on the root domain

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA  Here is a Preview of the newsletter signup page https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/newsletter-signup-page/newsletter/

**Comment by saracope** [comment]
Assigned to @jeremyzilar

**Comment by saracope** [comment]
Should connect.digital.gov be added to our [list of domains](https://github.com/GSA/digitalgov.gov/wiki/Domains-and-DNS) in the wiki?
