### ISSUE TITLE
Bug: broken link to memo M-10-23 on "Guidance for Agency Use of Third-Party Websites and Applications"

### ISSUE THREAD

**Issue by jpadilla-usgs** [GSA/digitalgov.gov#6357]
**Describe the bug**
I found a broken link on the following page: [Guidance for Agency Use of Third-Party Websites and Applications](https://digital.gov/resources/guidance-for-agency-use-of-third-party-websites-and-applications/)

**Steps to Reproduce**
1. Go to [Guidance for Agency Use of Third-Party Websites and Applications](https://digital.gov/resources/guidance-for-agency-use-of-third-party-websites-and-applications/)
2. Click on ['*View Guidance for Agency Use of Third-Party Websites and Applications*'](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2010/m10-23.pdf)
3. You should see a 404/Page not found error

I was able to find a copy of the memo at [this](https://obamawhitehouse.archives.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf) URL. I intend to submit a PR that fixes it shortly (after checking your submission guidelines).

**Screenshots**
![image](https://github.com/GSA/digitalgov.gov/assets/110246316/889f2df2-1a86-48ad-863a-f8664ef8cda0)

**Comment by ToniBonittoGSA** [comment]
Thanks for submitting this, @jpadilla-usgs  

It is now on the new WH website. The current page for Memos on WH.gov is here: https://www.whitehouse.gov/omb/information-for-agencies/memoranda/ (Circulars, Bulletins, etc. are linked in the side navigation), and the new location of OMB's M-10-23 is here: `https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2010/m10-23.pdf`.

[M-10-23, Guidance for Agency Use of Third-Party Websites and Applications (PDF, 78 KB, 9 pages, June 2010)](https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2010/m10-23.pdf)

I will update in your pull request (https://github.com/GSA/digitalgov.gov/pull/6358).
