### ISSUE TITLE
Create an enhanced Author bio

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#641]
**502 people**  have contributed to digital.gov over the years. How do we improve the presence of these people?

## the immediate need to get started
- make it easy way for someone to update their bio
- an easy way for someone to add in a photo
  - This can be through a GitHub Account

## it should include …
- [x] a photo of the author
- [x] a short, one-line bio
- [x] agency they work for
- [x] where they live
- [x] email (optional)
- [x] Twitter (optional)
- [x] GitHub (optional)

## Other things we'll need to make this happen
- [ ] pull a photo from GitHub
- [ ] a page on how to sign up for a GitHub account

## it's done when …
- [ ] it is possible for someone to edit their bio
- [ ] there is a path for someone to add a photo to their bio
- [ ] there is an enhanced bio and a basic bio

**Comment by jeremyzilar** [comment]
That will be fixed in the new site on https://demo.digital.gov/ 👍

**Comment by jeremyzilar** [comment]
Looks like you found the workflow through https://workflow.digital.gov/edit/authors/?page=https://digital.gov/authors/sara-cope/ would love to know what could be better...

**Comment by saracope** [comment]
It all seemed pretty smooth. Just could use some documentation I think.
