### ISSUE TITLE
Blog post URL ends in .md

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#643]
Found https://digital.gov/2015/04/06/using-personas-to-better-understand-customers-usa-gov-case-study.md/ in search results for _personas_.

Issues: 
* That URL shouldn't end in .md 
* Link on first word in first paragraph, _Personas_, goes to https://digital.gov/2015/01/09/personas-101.md/ but it should be https://digital.gov/2015/01/09/personas-101/ -- which gives a 404 error.

It is finished when: 

A
- [x] anything linking to _personas-101.md_ is updated to link to https://digital.gov/2015/01/09/personas-101/ 
- [x] when https://digital.gov/2015/01/09/personas-101/ works

B
- [x] anything linking to _using-personas-to-better-understand-customers-usa-gov-case-study.md_ is updated to be https://digital.gov/2015/04/06/using-personas-to-better-understand-customers-usa-gov-case-study/ 
- [x] when https://digital.gov/2015/04/06/using-personas-to-better-understand-customers-usa-gov-case-study/ works

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
