### ISSUE TITLE
Consent checkbox fail gracefully

### ISSUE THREAD

**Issue by alexcarous** [GSA/digitalgov.gov#6648]
**Is your feature request related to a problem? Please describe.**
When certain content blockers are used (e.g., Hush), the checkbox to give consent for the newsletter signup disappears. This appears to be due to the website crazyegg.com being blocked by the content blocker.

<img width="344" alt="Screenshot 2023-09-27 at 6 20 32 PM" src="https://github.com/GSA/digitalgov.gov/assets/24810057/5da78321-ced0-4c83-8131-32bd808ac6f2">

<img width="868" alt="Screenshot 2023-09-27 at 6 09 39 PM" src="https://github.com/GSA/digitalgov.gov/assets/24810057/f8cf5483-6e23-4ec2-bffe-0d15adb8fc39">

**Describe the solution you'd like**
It would be ideal if this failed more gracefully and the consent checkbox loaded properly, even when crazyegg.com is blocked. Perhaps a first-party pop up window or an alt text of some kind could be used to improve accessibility.

**Comment by ToniBonittoGSA** [comment]
Thank you, I have added this to our backlog

**Comment by alexcarous** [comment]
Thanks @ToniBonittoGSA :)
