### ISSUE TITLE
Event: What You Need to Know: Required Prize Reporting to Congress #663

### ISSUE THREAD

**Issue by twgsa16** [GSA/digitalgov.gov#668]
## it should include:
- text update highlighted in red in Google doc: https://docs.google.com/document/d/1h-MOW2dvTKcv5qzh5UoY3PiCII0CQTAySMzDvcaDuNg/edit

## it's done when:
- please let me know when updated. we would like to get this out to the community 6.28.

**Comment by ToniBonittoGSA** [comment]
@twgsa16 

Done: https://digital.gov/event/2018/07/10/what-you-need-know-required-prize-reporting-congress/
