### ISSUE TITLE
List all the pages we could or should update to the new resources template

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#679]
We have a new template that useful for long pages or resources that span multiple pages. Let's determine what pages might benefit from this new template.

- [ ] Create a list of pages (or page types) we should update to the new template
- [ ] Share this list with the team
- [ ] Create a final list and make new issues as necessary to implement the new template

**Comment by ToniBonittoGSA** [comment]
Starting list: 
https://docs.google.com/document/d/1WOBBj7xxK72tkW7Ce2Ch-IL2OHjgchxJz6Rgp3Urm64/edit
