### ISSUE TITLE
Bug: typo "A step-by-step guide to picking metrics and tools for tracking performance on your siteundefined"

### ISSUE THREAD

**Issue by JimCollinsDC** [GSA/digitalgov.gov#6806]
**Describe the bug**
"[How to track performance](https://digital.gov/topics/uswds/)
A step-by-step guide to picking metrics and tools for tracking performance on your siteundefined"

**Steps to Reproduce**
1. Go to 'https://digital.gov/topics/uswds/'
2. Scroll down to 'How to track performance'
4. See error - "on your siteundefined"

**Screenshots**

**Comment by nick-mon1** [comment]
This topics page is currently being removed from the site. Marking as closed.
