### ISSUE TITLE
Add Top 6 instructions to wiki

### ISSUE THREAD

**Issue by thisisdano** [GSA/digitalgov.gov#681]
We now have more control over what we can put at the top of our homepage. Let's capture some information about this new functionality on our wiki so any team member knows what it can do and how to do it.

- [ ] Add information about how to edit the Top 6 to the wiki
- [ ] Make it clear what kinds of pages can be featured
- [ ] Outline any display options available
- [ ] Develop rough guidelines around how we determine which pages to feature
- [ ] Publish all guidelines to our wiki

**Comment by jeremyzilar** [comment]
This will be out of date shortly with the new site. Closing.
