### ISSUE TITLE
Broken YouTube shortcodes

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#688]
## Fix
Additional broken YouTube shortcodes, switch to the [Hugo shortcode in the Wiki](https://github.com/GSA/digitalgov.gov/wiki/Hugo-shortcodes). 

## Fixed 
- [x] https://digital.gov/2014/05/12/video-blog-sarah-crane-usa-gov/ 
- [x] https://digital.gov/2016/05/05/how-to-create-portable-content-with-structured-content-models/ 
- [x] https://digital.gov/2016/05/03/an-introduction-to-open-data-and-apis/ (image alignment)
- [x] https://digital.gov/2015/09/16/using-plain-language-to-write-for-the-web/ (missing video)
- [x] https://digital.gov/2014/05/22/how-to-make-a-mobile-paper-prototype/ 
- [x] https://digital.gov/2014/11/19/young-entrepreneurs-hang-out-with-government-virtually-and-in-spanish/ (image alignment)
- [x] https://digital.gov/2014/06/25/case-studies-in-thunderclap/ 
- [x] https://digital.gov/2014/06/30/u-s-gov-releases-new-collaborative-social-media-services/ (image alignment)
- [x] https://digital.gov/2014/08/01/video-blog-alison-lemon-fda.md/ (and .md end)
- [x] https://digital.gov/2013/06/12/take-your-social-media-program-from-rags-to-riches/ (image alignment)
- [x] https://digital.gov/2016/09/12/the-content-corner-using-social-media-to-promote-enhance-preparedness-for-the-public-we-serve/ (+ Twitter, 3 broken images)
- [x] https://digital.gov/2010/10/22/tell-compelling-stories-with-data-visualization/ 
- [x] https://digital.gov/2015/04/24/sharing-the-essentials-of-animated-gifs-for-public-services/ (image alignment)

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
