### ISSUE TITLE
All page types have same incorrect timestamp

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#690]
@thisisdano all have at the end of the page:

> Last updated by ToniBonittoGSA on Jul 09, 2018 at 0:59 pm ET

I've never seen 0 time before

Samples ~ 
**Post**: https://digital.gov/2018/02/05/using-journey-mapping-streamline-processes-across-agencies/ 
**Event**: https://digital.gov/event/2018/05/31/this-how-we-work-together-with-brad-frost/ 
**Page**: https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/  || https://digital.gov/services/ || https://digital.gov/communities/web-content-managers/ || https://digital.gov/about/ 

I don't know if this error related to the Top 6 update I made: 
1) This is live: https://digital.gov/ || https://github.com/GSA/digitalgov.gov/tree/master/data 
**_but_**, 
2) JZ also edited the Top 6 file in here: https://github.com/GSA/digitalgov.gov/pull/662 (it now has a conflict on the top 6 file)
 -- It had 7 items in there and I updated it; removed the 7th one, and updated it so it would have the USWDS video that I added this morning.

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA — this has been fixed on `master` — can you verify?

**Comment by ToniBonittoGSA** [comment]
Looks great, @jeremyzilar!
