### ISSUE TITLE
Should we have tags for events, resource pages, etc. again?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#692]
On WordPress, we were able to tag event pages, resources, etc.

Should we have them again so that events, communities, etc. are included on those pages? 

Example:
The [video tag](https://digital.gov/tag/video/) only includes articles; not the upcoming 7/12 DGU webinar, "[An Inside Look at How the FBI Develops Engaging Video](https://digital.gov/event/2018/07/12/an-inside-look-at-how-fbi-develops-engaging-video/)" nor the "[Video Production Pros Community of Practice](https://digital.gov/communities/video-production/)" Community page

related?: https://github.com/GSA/digitalgov.gov/issues/120 

## it's done when …
- [ ] thing
- [ ] and another thing

**Comment by jeremyzilar** [comment]
This is done on the DEMO site
