### ISSUE TITLE
Upgrade HUGO to v0.44

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#705]
We would like to upgrade HUGO on Federalist to take advantage of better processing and functionality.
At the moment, we are running `v0.23`, and we'd like to upgrade it to `v0.44`.

**Comment by jeremyzilar** [comment]
This is waiting on the Federalist team to upgrade HUGO on their end.

**Comment by Nerotool** [comment]
I'll love to learn more
