### ISSUE TITLE
Bug: og:url doesn't have complete top-level domain

### ISSUE THREAD

**Issue by lukefretwell** [GSA/digitalgov.gov#7168]
**Describe the bug**

It looks like the og:url doesn't include top-level domain which could pose problems for indexing and sharing.

How Digital.gov displays (doesn't include top-level domain):

`<meta property="og:url" content="/resources/an-introduction-to-domain-management/" />`

Ideal display (includes top-level domain):

`<meta property="og:url" content="https://www.whitehouse.gov/briefing-room/speeches-remarks/2023/12/21/remarks-by-president-biden-after-marine-one-arrival-21/" />`

Reference: https://ogp.me/#url

**Steps to Reproduce**
1. Go to 'https://digital.gov/resources/an-introduction-to-domain-management/'
2. Click on 'View source' in browser
3. Scroll down to '`<meta property="og:url" content="/resources/an-introduction-to-domain-management/" />`'

**Screenshots**

**Comment by nick-mon1** [comment]
@lukefretwell Thanks for creating this issue, our team will add this to our backlog to address.

**Comment by lukefretwell** [comment]
@ToniBonittoGSA @nick-mon1 @RileySeaburg @mejiaj! 🇺🇸
