### ISSUE TITLE
Measure # of print intents on digital.gov

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#722]
### In our user research, we heard that people regularly print our pages on digital.gov and distribute them to their teams. 🖇📄

**We'd like to know:**  
- how often does this actually happen?
- what pages are bring printed the most?
- is this _really_ happening?

So I reached out to @tdlowden who heads up the Digital Analytics Program for advice on how to track print metrics 🖨. Tim sent over this link: [**"How to Fully Track the Print Page Action with Google Analytics"**](https://www.blastam.com/blog/tracking-print-page-action-google-analytics )

more to come soon...

**Comment by saracope** [comment]
This may have been completed. @jz will check.

**Comment by jeremyzilar** [comment]
We still need to do this. The tracking code will need to be added to Google Tag manager
