### ISSUE TITLE
Service pages: DAP (notes, questions)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#729]
1. Five DAP sub-pages: 
 - https://digital.gov/services/dap/common-questions-about-dap-faq/ 
lots of code errors; from WP migration

 - https://digital.gov/services/dap/analytics-tool-instructions/ 
seems ok (code-wise); not sure if any updates are needed

 - https://digital.gov/services/dap/dap-digital-metrics-guidance-and-best-practices/ 
seems ok (code-wise)

 - https://digital.gov/services/dap/guidance-for-dap-gov-wide-data/ 
title and md file should say government-wide, not gov-wide; jargon

 - https://digital.gov/services/dap/incorporating-the-digital-analytics-program-tool-into-your-agencys-metric-program/ 
use _or_, not the forward slash / symbol

2. Two additional DAP sub-pages below are live, but shouldn’t be

 - https://digital.gov/services/dap/digital-analytics-program-universal-analytics-migration/ 
Deadline to complete was May 2015.. is anything linking to this page? Can we archive it?

 - https://digital.gov/services/dap/digital-analytics-program-user-community/ 
Live empty page, created 1/16/14. Am not sure why this exists under Services instead of Communities.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
