### ISSUE TITLE
md file and blog post appear in search results

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#731]
I searched for **_atomic_** to find mention of Atomic Design.

The results include both:

- https://digital.gov/2015/08/24/the-content-corner-modular-design-and-structured-content/ 
- https://digital.gov/2015/08/24/the-content-corner-modular-design-and-structured-content.md/

When you click the .md link, page gives a 404

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar  3rd and 4th links

<img width="906" alt="screen shot 2018-08-14 at 11 57 23 am" src="https://user-images.githubusercontent.com/19961574/44103160-7d52d6f2-9fb9-11e8-890e-ff248cae1ac7.png">

**Comment by jeremyzilar** [comment]
I reached out to the Search.gov team to see if they could re-index our content.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
