### ISSUE TITLE
Bug: No Communicators Clearly page or references on page

### ISSUE THREAD

**Issue by TateGunning** [GSA/digitalgov.gov#7407]
**Steps to Reproduce**

Go to main site
Blue button on landing 
Upon click through no communication op appears only an email 

Does one have to join via email? Is this site real? Please confirm... thanks.

**Comment by ToniBonittoGSA** [comment]
There are multiple blue buttons on our homepage.
If you are referring to the Community of Practice buttons, only U.S. government employees and contractors can join a community of practice. An official, government-issued work email address is required to join.
