### ISSUE TITLE
to fix: Image alignment on blog posts

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#743]
## it should include …
 https://digital.gov/2016/05/03/an-introduction-to-open-data-and-apis/ (image alignment)
  https://digital.gov/2014/11/19/young-entrepreneurs-hang-out-with-government-virtually-and-in-spanish/ (image alignment)
  https://digital.gov/2014/06/30/u-s-gov-releases-new-collaborative-social-media-services/ (image alignment)
  https://digital.gov/2013/06/12/take-your-social-media-program-from-rags-to-riches/ (image alignment)
  https://digital.gov/2015/04/24/sharing-the-essentials-of-animated-gifs-for-public-services/ (image alignment)

## it's done when …
- [ ] thing
- [ ] and another thing

**Comment by jeremyzilar** [comment]
This might be a little hard to fix at this time.
I would like to wait till we have a new article template and new image sizes in place before making this fix. That way, we can apply these within a bigger system of changes

**Comment by ToniBonittoGSA** [comment]
Markdown alignment ok here 
https://digital.gov/2018/01/30/making-customer-satisfaction-data-actionable-at-peace-corps/ 

> {{< img-right src="peace-corps" capton="" alt="" >}}
> 
> For the past couple of years, the [Peace Corps](https://www.peacecorps.gov/) has used online-based intercept surveys on peacecorps.gov to measure user satisfaction. The data captured over time has been interesting, but has not varied much month-to-month, which has made it difficult to translate insight into actionable enhancements on the website.

**Comment by monkeywithacupcake** [comment]
The first one is an issue because the following text (after the image) is not within a container. There is an empty p, then the image, then text. If you float the image right, the text comes up to wrap on the left, and you can't clear it because it is not in a container.

**Comment by jeremyzilar** [comment]
Happy to look at this now
