### ISSUE TITLE
Plain Lang video is missing from blog, YouTube

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#744]
https://digital.gov/2015/09/16/using-plain-language-to-write-for-the-web/ 

## it's done when …
- [ ] thing
- [ ] and another thing

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA I am not sure where that video is in YouTube. :/
https://www.youtube.com/watch?v=gesKoT-5Tjg

We could link to/embed this one, which looks similar (but is not the same)
https://www.youtube.com/watch?v=j9FCji6-UJE

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar Either JT or SB was going to look at a list of vids DGU has to try to see what happened to it -- do you have access to all DGU files/folders in Drive/recall seeing such a list?
