### ISSUE TITLE
blog: 3 broken/missing images (migration error)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#745]
https://digital.gov/2016/09/12/the-content-corner-using-social-media-to-promote-enhance-preparedness-for-the-public-we-serve/ 

Wayback Machine: https://web.archive.org/web/20161225134438/https://www.digitalgov.gov/2016/09/12/the-content-corner-using-social-media-to-promote-enhance-preparedness-for-the-public-we-serve/ 

## it's done when …
- [ ] thing
- [ ] and another thing

**Comment by jeremyzilar** [comment]
We need to:

- [ ] Check to see if [this file exists on the server](https://s3.amazonaws.com/digitalgov/_legacy-img/2016/09/600-x-340-EQanimation/_8/_Plan/_091114/_medium.jpg)
- [ ] modify it's permissions
- [ ] Check the paths
