### ISSUE TITLE
Link to YouTube PDF is broken on TOS page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#747]
@jeremyzilar we rec'd an email to the DG acct about https://digital.gov/resources/negotiated-terms-of-service-agreements/ 

the link to the YouTube PDF displays XML; it is set to:
https://s3.amazonaws.com/digitalgov/_legacy-img//2014/01/youtube-tos-amendment.pdf 
~ Looks like there's an extra forward slash in the URL

## it's done when …
- [x] PDF for YouTube TOS displays/is launched

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar can I close this? the link works now, the extra / is gone.

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
