### ISSUE TITLE
Duplicate author files, odd list order on Author page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#752]
https://digital.gov/authors/ 

**1) Issue: hyphens in display, lowercase letters**

- claire-loxsom (1) _(need to fix)_ 
- jamie-albrecht (1) _(need to fix)_ 
- us-department-of-homeland-security (1) _(need to fix)_ 
- bill-brantley (1) _(is in duplicate list below; will need to delete file once this one blog post is moved to his correct Author file)_ 

**2) Sorting** 

There may be a bug... Surprised to see

> - 18F Team (3)
> - Meghan Lazier (1)
> - us-department-of-homeland-security (1)
> - Aaron Snow (1)

and

> - Tyrus Manuel (47)
> - Tyrone Grandison (2)
> - Tyrus Manuel (7) _(noted as part of duplicates below)_ 

and

> - Tammy White (1)
> - 10 names...
> - Tammi Marcoullier (24)

**3) Duplicates found:** 
- [x] Meghan Lazier 
- [x] Ty Manuel 
- [x] Bill Brantley 
- [x] Will Sullivan 

> Meghan Lazier (1)
> 346 names...
> Meghan Lazier (4)

> Tyrus Manuel (47)
> Tyrone Grandison (2)
> Tyrus Manuel (7)

> Bill Brantley (114)
> 8 names...
> bill-brantley (1)

> Will Sullivan (2)
> Will Sullivan (50)

## it's done when …
- [ ] thing
- [ ] and another thing

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA I fixed Claire, Jamie and Bill.

Is there no specific author that we can use for this post? An actual person?
https://digital.gov/2017/08/03/cutting-edge-new-virtual-training-prepares-first-responders-for-active-shooter-incidents/

Also, it is not clear if there are issues with the other authors you listed above. Can you clarify?

**Comment by jeremyzilar** [comment]
Oh I see 👀 I fixed the duplicates as well.

**Comment by jeremyzilar** [comment]
Are `Tammy White` and `Tammi Marcoullier` the same person?

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
