### ISSUE TITLE
Three duplicate COPs in right sidebar in one blog post

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#761]
## on blog post https://digital.gov/2017/04/04/color-in-digital-design/ 

but is fine on some other blog posts.. like
https://digital.gov/2017/09/11/cfpb-serves-up-financial-tips-to-seniors/
and https://digital.gov/2018/08/30/collaborating-for-better-design-technology-user-experience/ 

It has:

> **Join the community**
> Multilingual Community of Practice — We are a group of federal, state and local government content managers, formerly known as the Federal Multilingual Websites Committee, who are working to expand and improve digital content in languages other than English. Join »
> 
> Web Content Managers Forum — The Web Content Managers Forum is a community of government employees who share ideas, challenges, lessons learned, and best practices in managing the content of government websites. Join »
> 
> Plain Language Community of Practice — Our goal is to promote the use of plain language for all government communications. Join »
> 
> Multilingual Community of Practice — We are a group of federal, state and local government content managers, formerly known as the Federal Multilingual Websites Committee, who are working to expand and improve digital content in languages other than English. Join »
> 
> Web Content Managers Forum — The Web Content Managers Forum is a community of government employees who share ideas, challenges, lessons learned, and best practices in managing the content of government websites. Join »
> 
> Plain Language Community of Practice — Our goal is to promote the use of plain language for all government communications. Join »
> 
> User Experience Community of Practice — Join other federal user experience practitioners and learn how to make better user-centered products. Join »
> 
> All communities »

The first 3 of the 7 are repeated; only the last 4 should be showing.

## it's done when …
- [ ] first 'block' of 3 COPs is no longer visible

**Comment by jeremyzilar** [comment]
I am not seeing this anymore. I think this was fixed when I was looking at a categorization issue a while back... closing for now
