### ISSUE TITLE
Should we add an RSS/Subscribe page?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#762]
## Maybe something similar to https://www.congress.gov/rss ?

JZ noted: 
add `index.xml` to any URL and you’ll get the RSS feed for that page
https://digital.gov/categories/mobile/index.xml

## it's done when …
- [ ] thing
- [ ] and another thing

**Comment by jeremyzilar** [comment]
I think we should put this at `/feeds` in the new site and put all the JSON feeds and RSS feeds etc...
