### ISSUE TITLE
Bug (?): 3 of 4 links have odd code showing on post

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#768]
## on [A Deeper Look into the USDA.gov Website Redesign](https://digital.gov/2017/04/26/a-deeper-look-into-the-usda-gov-website-redesign/)
3 of the 4 links have odd code in curly brackets appearing after [and flush with] the link

> It also provides us with a centralized location to host all of our content, including [the USDA blog](https://www.usda.gov/media/blog){#anch_55}. 

> Using agile project management methods, strategic planning, workshops and user testing, and a combination of web development and accessibility tools, the [new USDA.gov embodies the best of government and industry expertise with our audience—you—in mind](https://www.usda.gov/media/blog/2017/03/06/complete-redesign-you-mind){#anch_56}.

> We want you to continue to explore the new site and continue to [share feedback with us](feedback@oc.usda.gov){#anch_57.}.

@jeremyzilar  is it safe to just delete, or does this indicate an error or some sort?

**Comment by jeremyzilar** [comment]
I bet we can do a find-and-replace for `{#anch_` with a regex patter and remove these. I can do this.

**Comment by jeremyzilar** [comment]
I will see how big the problem is first, and let you know.
