### ISSUE TITLE
json links in search results

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#769]
## I searched for `HIV.gov` and got 2 pages of results. 

[On the 2nd page](https://find.digitalgov.gov/search?affiliate=digitalgov&page=2&query=HIV.gov&sort_by=&utf8=%E2%9C%93), the last 2 results shouldn't be visible. 

<img width="1280" alt="screen shot 2018-09-11 at 3 29 36 pm" src="https://user-images.githubusercontent.com/19961574/45382916-c73c1600-b5d7-11e8-8300-5f27d20a8f82.png">

<img width="1280" alt="screen shot 2018-09-11 at 3 33 42 pm" src="https://user-images.githubusercontent.com/19961574/45383066-1eda8180-b5d8-11e8-82bc-a9655856f96c.png">
(this scrolls down for 5 pages)

## it's done when …
- [ ] those 2 links are not part of search results

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar another one:

https://find.digitalgov.gov/search?utf8=%E2%9C%93&affiliate=digitalgov&sort_by=&query=Education%2C+FAFSA 

<img width="895" alt="screen shot 2018-09-26 at 9 39 44 am" src="https://user-images.githubusercontent.com/19961574/46083854-4ef55900-c170-11e8-94c7-dabd33a93b55.png">

**Comment by saracope** [comment]
Still an issue.
