### ISSUE TITLE
The css for bullet list are mismatched in the footer

### ISSUE THREAD

**Issue by eddietejeda** [GSA/digitalgov.gov#773]
The "Recent Posts" footer list does not match the "Events" footer list.

As it stands, the "Events" section:
- [ ] Is missing an actual bullet symbol
- [ ] Has a different color for heading than "Recent Posts"
- [ ] Has much larger indendation than"Recent Posts"

<img width="745" alt="screen shot 2018-09-12 at 1 11 12 pm" src="https://user-images.githubusercontent.com/669988/45441704-c8c81580-b68d-11e8-89b0-97e62fd76f45.png">

**Comment by ToniBonittoGSA** [comment]
Hi @eddietejeda,

Yes, we are aware; it was a migration error (from old CMS to GitHub); we are fixing soon.

Thanks!
 Toni

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
This has been completed 🎉👾
