### ISSUE TITLE
[Suggestion] Pages point to the wrong search.gov email

### ISSUE THREAD

**Issue by jimkreft** [GSA/digitalgov.gov#7815]
### URL / Link to page
https://github.com/search?q=repo%3AGSA%2Fdigitalgov.gov%20search%40support.digitalgov.gov&type=code

### Tell us how we can make this page better

Need to change the search.gov support email to search@gsa.gov

**Comment by nick-mon1** [comment]
Resolved by https://github.com/GSA/digitalgov.gov/pull/7816 on 7/26/2024.
