### ISSUE TITLE
Banner sometimes overflows in mobile

### ISSUE THREAD

**Issue by RileySeaburg** [GSA/digitalgov.gov#7905]
Just noticed this as port of the review @nick-mon1 ![image](https://github.com/user-attachments/assets/2980bb5b-e0f9-4521-bffb-ef5d2e34e81d)

_Originally posted by @RileySeaburg in https://github.com/GSA/digitalgov.gov/pull/7903#issuecomment-2315801616_

**Comment by tesawalker** [comment]
Not received my money deposits

**Comment by clmedders** [comment]
This issue has been addressed and has been pushed to main
