### ISSUE TITLE
Bug: Header image not loading

### ISSUE THREAD

**Issue by anatecture** [GSA/digitalgov.gov#7932]
**Describe the bug**
[Header image](https://digital.gov/guides/hcd/discovery-concepts/recruit-participants/#content-start) isn't loading 

**Steps to Reproduce**
1. Go to [recruit page](https://digital.gov/guides/hcd/discovery-concepts/recruit-participants/#content-start)
2. Wait for load
![Screenshot 2024-09-11 at 8 38 37 AM](https://github.com/user-attachments/assets/1637105a-dfc9-4e59-824b-e649710af80c)

**Screenshots**

**Comment by nick-mon1** [comment]
@anatecture Thanks for creating this issue, it is now fixed.
