### ISSUE TITLE
Categories alphabetization is off for Emerging Tech posts

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#796]
## it should include …
Categories should be automatically displayed in alphabetical order; most here https://digital.gov/authors/jherman/  are not

to fix: 
- [x] all multi-word slugs must use hyphens so that Categories will display in alphabetical order at the top of a blog post

## it's done when …
- [x] all are correctly alphabetized

**Comment by jeremyzilar** [comment]
I need to look into the Emerging Tech topic in general...

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
