### ISSUE TITLE
Migration error: missing author needed on blog posts

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#799]
## it should include …
- [x] create yml file for **MobileGov Team**
- [ ] Add author code and slug to 68 blog posts ~ reference Wayback Machine https://web.archive.org/web/20160104194539/https://www.digitalgov.gov/author/clerxn/ 

## it's done when …
- [x] yml file for author https://digital.gov/authors/mobilegov-team/ 
- [ ] all 68 blog posts have the author assigned

**Comment by jeremyzilar** [comment]
This will have to be done by hand.
