### ISSUE TITLE
Title Cards for Digital.gov Videos

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#803]
Title Cards need to be created for the following videos:

**DAP Learning Series: Advanced Concepts**
https://www.youtube.com/watch?v=limXoQVPw2A

**DAP Learning Series: Analytics and Accessibility**
https://www.youtube.com/watch?v=y0HD0baIIP0

**DAP Learning Series: Writing custom javascript for tag managers**
https://www.youtube.com/watch?v=iKBCY7tfxSY

**DAP Learning Series: An Introduction to the Basics**
https://www.youtube.com/watch?v=ph-ixyzCVbc

**A Conversation with Evan Papp of Power Africa**
https://www.youtube.com/watch?v=BQlgGotFUlQ

**Comment by thisisdano** [comment]
![dap-advanced-concepts](https://user-images.githubusercontent.com/11464021/46980466-811c1b80-d089-11e8-8afa-3673a930afa1.png)

**Comment by thisisdano** [comment]
![dap-analytics-and-accessibility](https://user-images.githubusercontent.com/11464021/46980491-909b6480-d089-11e8-9db9-9e482bdd544d.png)

**Comment by thisisdano** [comment]
![dap-writing-custom-javascript](https://user-images.githubusercontent.com/11464021/46980508-9d1fbd00-d089-11e8-973c-2f17a3869c09.png)

**Comment by thisisdano** [comment]
![dap-introduction-to-the-basics](https://user-images.githubusercontent.com/11464021/46980516-a577f800-d089-11e8-8246-4542c230d844.png)

**Comment by thisisdano** [comment]
![a-conversation-with-evan-papp](https://user-images.githubusercontent.com/11464021/46980560-cc362e80-d089-11e8-98cc-7d9d672fe9b5.png)

**Comment by jeremyzilar** [comment]
Wonderful 😍 Thank you @thisisdano !
