### ISSUE TITLE
Gather baseline measurements about DigitalGov.gov on WordPress

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digitalgov.gov#81]
We are moving `digitalgov.gov` from a database-driven, memcached version of WordPress to static-file version of our site that is built and supported by Hugo, Federalist and Cloud.gov.

Over the last few months, we’ve done our best to replicate the site _as is_. Why?
1. Because we don't have easy access to our code 
2. Because we prefer to solve one problem at a time.

But before we make the move and start making the site better, we'd like to capture a baseline set of  diagnostics around the current site so that we have great data to measure future changes against.

**What automated tests should we run on the existing site?**

DigitalGov.gov on WordPress — [https://www.digitalgov.gov](https://www.digitalgov.gov)
demo.digitalgov.gov on Federalist — [https://demo.digitalgov.gov](https://demo.digitalgov.gov) 

We migrated around 1902 posts, pages and events from WordPress to Hugo/Federalist.

**Comment by jeremyzilar** [comment]
**Performance:**
At last check, our site takes around 3.8 seconds to load 1.16MB of content over 88 separate connections web connections on a desktop computer. And for mobile, this nets out at a **D+** rating according to Google page.

**digitalgov.gov (WP)**
10/9 19:58pm ET — https://gtmetrix.com/reports/digitalgov.gov/prXcMWOw

**demo.digitalgov.gov**
10/9 19:58pm ET — https://gtmetrix.com/reports/demo.digitalgov.gov/NW0Zkazr
10/9 19:58pm ET — https://developers.google.com/speed/pagespeed/insights/?url=demo.digitalgov.gov

**Comment by jeremyzilar** [comment]
### Mobile

According to Google's mobile testing tool, our site loads in around `8s` on a 3G connection and it likely results in a `28%` loss in traffic due to loading time.

https://testmysite.thinkwithgoogle.com/

**Comment by afeld** [comment]
* Uptime
* Operations cost
* Second page load time (will let you know how well the caching’s working)

Others: https://www.keycdn.com/blog/website-performance-metrics/

**Comment by jeremyzilar** [comment]
**Lighthouse/ Chrome Devtools** — https://developers.google.com/web/tools/lighthouse/#devtools

**Performance**

- Overall score: 45/100
- First Meaningful paint: 4060 ms
- First Interactive: 11,660 ms
- Perpetual Speed Index: 26,877 ms
- Estimated Input Latency: 28 ms

**Comment by thecapacity** [comment]
In addition to @afeld 's "operational metrics" (which are good) - I'd also think about "management metrics" (e.g. time to update, auditability, ...) just an idea.

**Comment by chriscct7** [comment]
Just curious, was static page caching WordPress discussed? If so, is the advantage of moving to Federalist more from a performance standpoint (benefit over static page caching) or from a compliance standpoint?

**Comment by chriscct7** [comment]
Just spotted https://github.com/GSA/digitalgov.gov/issues/180. Is that going to be explained on the site or on that ticket?

**Comment by jeremyzilar** [comment]
Good question @chriscct7 — yes, I will discuss more in #180 in the coming week. This was mostly a ticket to start capturing the measurements we were taking from the WP version of the site.
