### ISSUE TITLE
Demo QA - Universal

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#82]
**Footer**
Huge gap = Missing Twitter feed (widget broke in WP)

**DG’s Social icons** (header & footer)
RSS 
current: https://www.digitalgov.gov/feed/ 
change to: ?

**YouTube** 
current: http://www.youtube.com/user/howtogov
change to: http://www.youtube.com/c/DigitalGov

**Pages nav**:
Each main menu page name is missing colored highlight/visual cue for Compliance

**Keyboard Tabbing**
Both nav menus: on the drop down items, the bottom side of dashed outline is missing/not visible (all except last one)

**Recent Posts lists don't match**
Live (9 to match homepage):
3 Ways to Manage Research Projects Remotely
Machine Learning Paired with Skilled Data Scientists is the Future of Data-Driven Decision Making
Finding Usability Testers: Tips from an Army Recruiter
The Data Briefing: How to Build a Chatbot in a Weekend
Slack AMA Connects Standards Team with Public
Managing Custom Software Development in Government When You’re Not a Software Engineer
A Conversation With ITIF About the State of Federal Government Websites
The Data Briefing: Will Artificial Intelligence Tools Replace or Augment Federal Employees?
Design and Conflict: Do You Know Your Conflict Style?

Demo (10): 
3 Ways to Manage Research Projects Remotely 
Machine Learning Paired with Skilled Data Scientists is the Future of Data-Driven Decision Making 
Finding Usability Testers: Tips from an Army Recruiter 
The Data Briefing: How to Build a Chatbot in a Weekend 
Slack AMA Connect Standards Team with Public 
Managing Custom Software Development in Government When You’re Not a Software Engineer 
 _the 'A Conversation With ITIF...' post is missing_
The Data Briefing: Will Artificial Intelligence Tools Replace or Augment Federal Employees? 
Design and Conflict: Do You Know Your Conflict Style? 
The Data Briefing: How Blockchain’s Future Growth Will Affect Federal Agencies 
USA.gov and GobiernoUSA.gov Measure Content Efficiency With New KPI Metric ( _would be removed_ )

**Comment by ToniBonittoGSA** [comment]
FYI: the Twitter feed is still visible and working on the HubSpot subscribe page footer 
https://connect.digitalgov.gov/subscribe

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA I am closing these as they all seem to be completed. Feel free to re-open a new issue if there are things here that are outstanding bugs.
