### ISSUE TITLE
11/2 Blog draft: Health Tech Sprint Aims at Improving Care Access and Experience

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#826]
GH PR: 

**Headline**: Health Tech Sprint Aims at Improving Care Access and Experience
**Deck**: Federal agencies and technology teams work together to pilot digital tools for artificial intelligence and health innovation. 
**Summary**: This sprint is designed to improve care by assisting in access to novel therapeutics and improving clinical trials. 
**Topics**: pif, hhs, va, open-data, artificial-intelligence, innovation, emerging-tech

By Gil Alterovitz, Ph.D., Presidential Innovation Fellow; Justin Koufopoulos, Presidential Innovation Fellow; Kristen Honey, Ph.D., Innovator in Residence, HHS Office of the CTO

Deck: 

Starting October 2018, [Presidential Innovation Fellows](https://www.presidentialinnovationfellows.gov) (PIF) kicked-off and will lead a 14-week tech sprint with the [U.S. Department of Health and Human Services](https://www.hhs.gov/) (HHS) and other digital enthusiasts. 

The goal of this tech sprint is to transform [federal open data](https://www.data.gov/) from HHS, the [U.S. Department of Veterans Affairs](https://www.va.gov/) (VA), and other agencies into digital tools. Modeled after [The Opportunity Project](https://opportunity.census.gov/) (TOP) at [U.S. Department of Commerce](https://www.commerce.gov/), the [TOP Health tech sprint](http://tophealth.github.io) is specifically designed to improve the patient experience, for example, by assisting in novel therapeutics accessibility and improving clinical trials.

Presidential Innovation Fellows will lead a cohort of tech teams that are developing an ecosystem that leverages artificial intelligence (AI) technologies to help patients find new types of treatments. Several unique aspects of this tech sprint include cross-agency participation to create an ecosystem around a specific challenge, AI-centric data design, iteratively released data for training and testing, health-specific cohort, and access to specialized resources to foster a new AI-centric ecosystem. As part of this process, several industry partners have been chosen to participate. 

## Tech Sprint 

Federal open data is a key driver for health innovation. In addition to research and development dollars, the federal government provides key datasets to startups, academia, and industry. In this tech sprint, this federal open-data ecosystem is used as a platform for industry to create value for Americans. Participating tech teams will pilot use of novel federal open-data datasets designed specifically for this sprint, build tools around them, and present results at a public “Demo Day” event in 2019 with leadership across agencies. The results will also provide feedback on the types of dataset creation and design that federal agencies and others can do to promote use of AI and data in this space, and in general. 

## Artificial Intelligence (AI) for Novel Therapeutics Accessibility

In this sprint, teams will focus on using a collection of specially released datasets for training Artificial intelligence is transforming healthcare. The promise of AI is to provide better experiences for patients, unburden physicians, and drive down the costs of drugs. Already, one is beginning to see an exciting ecosystem of software companies building technologies and brands that can help America’s health systems. 

Novel therapeutics, such as those under development in clinical trials, are often a treatment option for those patients with serious and life threatening diseases such as cancer. Increasing patient awareness of clinical trials is believed to be a factor in reducing time for participant recruitment, a very large cost categories in clinical trials. Thus, applying AI to help patients find clinical trials studying novel therapeutics, may have the potential to improve patient care and, by aiding in recruitment, reduce drug development costs. 

![robot with education hud 3d rendering robot learning or machine learning with education hud interface phonlamaiphoto istock getty images plus-950196458](https://user-images.githubusercontent.com/19961574/47919735-800b2c80-de86-11e8-9e85-ef3d165a6c37.jpg)
_Alt text: 3D rendering of a robot learning on an education HUD (head-up display) interface with mathematical and chemical equations. 
Caption: PhonlamaiPhoto iStock Getty Images Plus_

## AI-Centric Data Design 

For the past year, the Presidential Innovation Fellows program has been working with the National Institutes of Health and others on reducing the costs of clinical trials and improving the patient experience. A key outcome of this work has been the creation of AI ecosystem-empowering datasets that can form the foundation for training and testing AI for improving patient access to novel therapeutics.

Presidential Innovation Fellows engage with federal agencies to help solve some of their most pressing challenges around artificial intelligence, cybersecurity, product management, and organizational design—all to improve the lives of the American people. A key goal of this project is to convene federal expertise, patients and user advocates, and technology organizations. 

The AI project will be done in parallel with another tech sprint track on Lyme and tick-borne
diseases, led by Dr. Kristen Honey and the [HHS Office of the CTO](https://www.hhs.gov/about/agencies/cto/). The latter will focus on
leveraging crowd- and patient-based data insights. 

## Tech Organizations Selected 

- The AI ecosystem project will be piloted by these tech organizations: Flatiron Health, Microsoft Healthcare, Oracle, Philips (Research), and Rush Medical, and TrialX (in collaboration with the Global Lyme Alliance). 
- The Lyme and tick-borne diseases track will include: TickTracker, LivLyme Foundation, and Clyme Health. 

## Getting Involved 

The time for leveraging AI in improving access to novel therapeutics is now. If you are interested in learning more, downloading the ecosystem data, being a data steward, sharing experiences, or learning about the tech sprint’s results, please visit the site at: [tophealth.github.io](https://tophealth.github.io/). 

To contact us on the overall TOP Health tech sprint, please email the Presidential Innovation Fellows, [gil.alterovitz@pif.gov](gil.alterovitz@pif.gov) and [justin.koufopoulos@pif.gov](justin.koufopoulos@pif.gov), or the HHS Office of the CTO, [cto@hhs.gov](cto@hhs.gov). Please use subject line: **_TOP Health: inquiry from DigitalGov blog_**. 

*** 

_All references to specific brands and/or companies are used only for illustrative purposes and do not imply endorsement by the U.S. federal government or any federal government agency._

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
