### ISSUE TITLE
Timestamp for updates needs correction

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#832]
**Describe the bug**
Daylight Saving Time ended last week (clocks set back one hour); the timestamp for updates is now appearing ahead one hour. 

**To Reproduce**
1. Go to any page; [example](https://digital.gov/resources/mobile/principles/) 
2. To see errors, view both timestamps - at top of content, and in Feedback box below content

**Expected behavior**
Time is one hour ahead; should be one hour behind
Notice the laptop's clock time and update timestamp in screencaps below

**Screenshots**
<img width="505" alt="screen shot 2018-11-09 at 4 31 59 pm" src="https://user-images.githubusercontent.com/19961574/48289438-8298f380-e43d-11e8-81e0-31501439a807.png">
<img width="560" alt="screen shot 2018-11-09 at 4 30 17 pm" src="https://user-images.githubusercontent.com/19961574/48289439-8298f380-e43d-11e8-85a0-268cb51b6d16.png">

**Comment by jeremyzilar** [comment]
This has been fixed @ToniBonittoGSA. Can you verify?

**Comment by ToniBonittoGSA** [comment]
Yep, @jeremyzilar 
Thanks!!
