### ISSUE TITLE
Is -0500 necessary in time code?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#837]
In right box on https://digital.gov/new-post/ 

noticed b/c update timestamps don't auto update to "spring ahead" or "fall back" when time change occurs every 6 months

**Comment by jeremyzilar** [comment]
Good question — I would like to look at it at some point, but at the moment it is not causing a 🔥

**Comment by jeremyzilar** [comment]
Looking at this... Very unclear from the HUGO documentation

**Comment by jeremyzilar** [comment]
Discussion here: 
https://discourse.gohugo.io/t/document-dates-in-front-matter/19123/3

**Comment by jeremyzilar** [comment]
Apparently, you need the `-500` or `-400` in the date/time in HUGO :/
I even explored ways to include the timezone offset via the config, but to no go...
I should report this as a bug or feature request in HUGO core
