### ISSUE TITLE
Demo QA - Events & DGU pages

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#84]
**Events**
https://demo.digitalgov.gov/events/
https://demo.digitalgov.gov/event/an-around-world-recap-plain-monthly-meeting/
https://demo.digitalgov.gov/event/dap-learning-series-visualizing-analytics-data-part-2/
https://demo.digitalgov.gov/event/connect-with-your-spanishlanguage-audience-on-social-media/

Featured images missing; need for social sharing

The 3 above are all online.. can we embed Google Maps for those with physical locations?

Pages menu to archive points to https://www.youtube.com/user/howtogov
should be https://www.youtube.com/c/DigitalGov 

**DGU page**
live: https://www.digitalgov.gov/digitalgov-university/ (not 2-column)
demo: https://demo.digitalgov.gov/digitalgov-university/ (2-column)

Form link now to Google doc, but many agencies block them.. what's Plan B?
Original in WP: https://www.digitalgov.gov/digitalgov-university/digitalgov-university-event-and-training-request-form/ 

Image on Demo is too small and should be centered https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2017/06/600-x-445-SocialGov.jpg

The Add This/Share icons missing

Link on Recaps button is broken - 
live: https://www.digitalgov.gov/tag/recap/ 
demo: https://demo.digitalgov.gov/tag/recap (404 page)

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
