### ISSUE TITLE
search for odd slideshow code

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#857]
look for odd code: {.j-slideshow-url.title}

seen in https://digital.gov/2015/04/24/sharing-the-essentials-of-animated-gifs-for-public-services/ 

> [Animated Gif Tutorials with 18F](http://www.slideshare.net/DigitalGov/animated-gif-tutorials-with-18-f-melody-kramer "Animated Gif Tutorials with 18F"){.j-slideshow-url.title} (.pptx PowerPoint Presentation, 105 kb)

was not there before migration..

**Comment by jeremyzilar** [comment]
I am not sure why this is there, but can look into it. `{.j-slideshow-url.title}`
And see if it was something we embedded after migration

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Hmm, I am going to guess that this was in there before the migration and was a WP shortcode that was never working `{.j-slideshow-url.title}` and it came over as text.

- There are no mentions of this or parts of this in any of our posts
- There are no mentions of this or parts of this on the internet...

Closing for now
