### ISSUE TITLE
Live site: title text overlaps byline on Author pages

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#880]
**Describe the bug**
On Author pages, the title line is overlapping the byline

**To Reproduce**
1. Go to examples: 
https://digital.gov/authors/tlowden/ 
https://digital.gov/authors/lmartinez/ 
2. Scroll down to see errors

**Expected behavior**
there should be no overlap on these author pages
 (titles display correctly on blog & resource pages; only seeing issue on Author pages)

**Screenshots**

### A) iPhone 7, iOS 12.1.2, Safari

![image from ios](https://user-images.githubusercontent.com/19961574/50343067-98e1a700-04f3-11e9-8ff2-850d52617edf.png)

### B) Galaxy S9+, Android 8.0.0, Chrome

![screenshot_20181220-155422_chrome](https://user-images.githubusercontent.com/19961574/50343090-a139e200-04f3-11e9-8432-fbe3f189a965.jpg)

### A) Safari, Version 12.0.2 (13606.3.4.1.4)

<img width="623" alt="mac safari" src="https://user-images.githubusercontent.com/19961574/50342996-6172fa80-04f3-11e9-83b0-9fd96a2ad6ba.png">

### B) Chrome, Version 71.0.3578.98 (Official Build) (64-bit) 

<img width="638" alt="mac chrome" src="https://user-images.githubusercontent.com/19961574/50343016-6fc11680-04f3-11e9-9a95-e49f6cfca188.png">

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
