### ISSUE TITLE
Demo QA - main Communities page links/URLs

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#89]
**Communities** main page
**_live_**: https://www.digitalgov.gov/communities/ (not 2-column)
**_demo_**: https://demo.digitalgov.gov/communities/ (2-column)

Add This/Share missing (this, and individual pages)

page links - 

**Agile/Lean**: 
**_live_**: https://www.digitalgov.gov/agile-lean-community-of-practice/
**_demo_**: https://demo.digitalgov.gov/communities/agile-lean/

**Artificial Intelligence for Citizen Services**: 
live: https://www.gsa.gov/portal/content/168110
demo: https://www.gsa.gov/technology/government-it-initiatives/emerging-citizen-technology/artificial-intelligence-for-citizen-services

**Blockchain**: 
live: https://www.gsa.gov/portal/content/168102
demo: https://www.gsa.gov/technology/government-it-initiatives/emerging-citizen-technology/blockchain

**BusinessUSA**: 
live: none
demo: https://demo.digitalgov.gov/communities/business-usa/

**Challenges & Prizes**: 
live: https://www.digitalgov.gov/communities/challenges-prizes-community/
demo: https://demo.digitalgov.gov/communities/challenges-prizes/

**Community Solutions**: 
live: https://www.digitalgov.gov/communities/community-solutions/
demo: https://demo.digitalgov.gov/communities/community-solutions/

**Crowdsourcing and Citizen Science**: 
live: https://www.digitalgov.gov/communities/federal-crowdsourcing-and-citizen-science/
demo: https://demo.digitalgov.gov/communities/crowdsourcing-and-citizen-science/

**G3C**: 
live: https://www.digitalgov.gov/communities/government-contact-center-council-g3c/
demo: https://demo.digitalgov.gov/communities/government-contact-center-council/

**Government Customer Experience**: 
live: https://www.digitalgov.gov/communities/customer-experience-community/
demo: https://demo.digitalgov.gov/communities/customer-experience-community/

**MobileGov**: 
live: https://www.digitalgov.gov/communities/mobile/
demo: https://demo.digitalgov.gov/communities/mobile/

**Multilingual Digital Group**: 
live: https://www.digitalgov.gov/communities/government-multilingual-websites-community/
demo: https://demo.digitalgov.gov/communities/multilingual/

 **_Note_**: Laura Godfrey request: Mass find-and-replace after launch: Change tag https://www.digitalgov.gov/tag/multilingual-digital-group/, all text in posts & pages from "Multilingual Digital Group" to "Multilingual Community of Practice"

**Open Data**: 
live: https://www.digitalgov.gov/communities/open-data-community-of-practice/
demo: https://demo.digitalgov.gov/communities/open-data/

**OpenGov**: 
live: https://www.digitalgov.gov/communities/open-government-opengov-community-of-practice/
demo: https://demo.digitalgov.gov/communities/open-government/

**Plain Language Action and Information Network**: 
live: https://www.digitalgov.gov/communities/plain-language-community-of-practice/
demo: https://demo.digitalgov.gov/communities/plain-language/

**SocialGov**: 
_**original**_: https://www.digitalgov.gov/communities/social-media/
live: https://www.gsa.gov/portal/content/168114
demo: https://demo.digitalgov.gov/communities/social-media/

**User Experience**: 
live: https://www.digitalgov.gov/communities/federal-user-experience-community-of-practice/
demo: https://demo.digitalgov.gov/communities/user-experience/

**Video CoP**: 
live: https://www.digitalgov.gov/communities/video-production-pros-community-of-practice/
demo: https://demo.digitalgov.gov/communities/video-production/

**Virtual/Augmented Reality**: 
live: https://www.gsa.gov/portal/content/168118
demo: https://www.gsa.gov/technology/government-it-initiatives/emerging-citizen-technology/virtual-and-augmented-reality

**Web Content Managers**: 
live: https://www.digitalgov.gov/communities/web-managers-forum/
demo: https://demo.digitalgov.gov/communities/web-content-managers/

**Comment by jeremyzilar** [comment]
We're not going to work on this at this time. 
We either don't have the bandwidth, or the idea/issue is no longer relevant.
