### ISSUE TITLE
Demo QA - WP Tools > Redirection (list, settings)

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#91]
13 redirects (12, plus 1 vanity URL) listed on 
https://www.digitalgov.gov/wp-admin/tools.php?page=redirection.php 

Menu has links for: Redirects | Groups | Modules | Log | 404s | Options | Support

There is an "RSS Token" under Options, and I see a button to import redirections from an existing .htaccess file, or a CSV file, but not to export.

**Comment by ToniBonittoGSA** [comment]
As of 10/10/2017:

## 1 Vanity URL

From - www.digitalgov.gov/resources/checklist 
To - www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/


## 12 URL Redirects

**Source**: /2017/09/07/usdas-foodkeeper-app-update-features-food-safety-recall-information/
**_Target_**: /2017/09/07/usda-foodkeeper-app-update-expands-content-offerings/ (**title change**)
Hits: 105
Last Access: October 9, 2017


**Source**: /2017/09/06/five-ways-federal-leaders-can-build-the-will-skill-and-velocity-needed-for-digital-transformation/
**_Target_**: /2017/09/06/how-federal-leaders-can-build-the-will-skill-and-velocity-needed-for-digital-transformation/ (**title change**)
Hits: 69
Last Access: October 9, 2017


**Source**: /event/online-far-faqs-expert-answers-your-questions-on-running-competitions-in-line-with-law/
**_Target_**: /event/online-far-faqs-contracting-expert-shares-best-practices-for-running-competitive-challenges/ (**event title change**)
Hits: 59
Last Access: October 10, 2017


**Source**: /communities/digital-audio-video-community-of-practice/
**_Target_**: /communities/video-production-pros-community-of-practice/ (**name change**)
Hits: 171
Last Access: October 10, 2017


**Source**: /resources/2012-digital-government-strategy-2/ (**HowTo duplicate was published**)
**_Target_**: /resources/2012-digital-government-strategy/
Hits: 124
Last Access: October 10, 2017


**Source**: /resources/federal-social-media-analytics-toolkit-hackpad/
**_Target_**: /2013/04/19/social-media-metrics-for-federal-agencies/ (**IT blocked Hackpad; had to create new page**)
Hits: 852
Last Access: October 10, 2017


**Source**: /2012/08/12/top-10-best-practices-for-multilingual-websites/ (**old HowTo article**)
**_Target_**: /resources/top-10-best-practices-for-multilingual-websites/ (**created new page we can update as needed**)
Hits: 2,026
Last Access: October 10, 2017


**Source**: /resources/digitalgov-user-experience-program/
**_Target_**: /digitalgov-user-experience-resources/ (**name change**)
Hits: 1,551
Last Access: October 10, 2017


**Source**: /communities/web-managers-forum/web-content-managers-listserv/ (**extra subfolder**)
**_Target_**: /communities/manage-your-listserv-subscription/ (**removed extra subfolder, better SEO for title/URL**)
Hits: 4,159
Last Access: October 8, 2017


**Source**: /resources/dot-gov-domain-freeze-and-waivers/
**_Target_**: /resources/checklist-of-requirements-for-federal-digital-services/#dotgov-domain-freeze-update (**bookmark location on page [ _WP forces extra_** / **_before the_** # **]**)
Hits: 323
Last Access: October 10, 2017


**Source**: /services/the-federal-mobile-apps-registry/
**_Target_**: /services/u-s-digital-registry/ (**name change/product merge**)
Hits: 984
Last Access: October 5, 2017


**Source**: /services/social-media-registry/
**_Target_**: /services/u-s-digital-registry/ (**name change/product merge**)
Hits: 1,501
Last Access: October 10, 2017

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Are there things here that are still open and need to be redirected?

**Comment by jeremyzilar** [comment]
Does this still need to be worked on @ToniBonittoGSA ?
