### ISSUE TITLE
HTML formatting error in contact-center-guidelines page

### ISSUE THREAD

**Issue by LindsayYoung** [GSA/digitalgov.gov#917]
**Describe the bug**
HTML is not getting rendered
<img width="987" alt="Screen Shot 2019-03-11 at 11 14 25 AM" src="https://user-images.githubusercontent.com/4406333/54134948-4081bd80-43ef-11e9-8ea5-d6aec6de0350.png">

**To Reproduce**
1. Go to 
File in github:
        digitalgov.gov/content/resources/contact-center-operation-and-management.md
Web link to error on page:
https://digital.gov/resources/contact-center-guidelines/contact-center-operation-and-management/#call  
3. Scroll down to
        How to identify fraudulent calls (#call should get you there)
The page is rendering raw HTML

**Expected behavior**
The page should render the HTML

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeremyzilar** [comment]
Thank you @LindsayYoung —— fixing !

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾

**Comment by LindsayYoung** [comment]
Nice! Thanks
