### ISSUE TITLE
Link in yellow bar at top of Demo homepage doesn't appear

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#92]
Link to the live site is not visible like it is on other pages (see https://demo.digitalgov.gov/communities/), but on https://demo.digitalgov.gov/index.html if you hit tab key once and then hit enter, the live site opens in new tab

- - -

### todo
- [x] homepage link should appear as `digitalgov.gov`

**Comment by thisisdano** [comment]
Related to #123

**Comment by thisisdano** [comment]
Fixed in #137 
Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/dw-update-banner/

**Comment by jeremyzilar** [comment]
This has been completed
