### ISSUE TITLE
[page error] Resource page, Guidelines for Improving Digital Services

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digitalgov.gov#965]
### 
Live: https://digital.gov/resources/guidelines-for-improving-digital-services/ 
Demo: https://demo.digital.gov/resources/guidelines-for-improving-digital-services/ 

### Table/code and text formatting errors

Have a look at what this page used to be like in the Wayback Machine
https://web.archive.org/web/20160331210750/http://www.digitalgov.gov/resources/guidelines-for-improving-digital-services/

**Comment by jeremyzilar** [comment]
This has been completed 🎉👾
