### ISSUE TITLE
Console Error: https://dap.digitalgov.gov/Federated.js.map

### ISSUE THREAD

**Issue by co16353sidak** [GSA/digitalgov.gov#999]
**Describe the bug**
A console error is found on the particular resource `https://dap.digitalgov.gov/Federated.js.map` is found on loading the website

**To Reproduce**
1. Navigate to the link
2. Open up browser console to check the error

**Expected behavior**
Hopefully no console error regarding the resource not being found

**Screenshots**
<img width="429" alt="Screenshot 2019-04-26 at 7 54 44 PM" src="https://user-images.githubusercontent.com/35738138/56814735-6bb85300-685d-11e9-9d8c-0f0de1b7d698.png">

**Not Device Dependent**

**Comment by jeremyzilar** [comment]
Thanks @co16353sidak — This has been completed 🎉👾
